/*
 * gen_method_protos.c: 
 *
 * Copyright (C) 2013 alloc <alloc.young@gmail.com>
 * Skyeye Develop Group, for help please send mail to
 * <skyeye-developer@lists.gro.clinux.org>
 *
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 */
#include "gen_method_protos.h"
#include "gen_implement.h"
extern FILE *out;
void gen_obj_method_protos(object_t *obj) {
	struct list_head *p;
	struct method_name *mn;
	tree_t *method;
	object_t *tmp;
	context_t context;
	obj_ref_t obj_ref;
	obj_ref.obj = obj;
	obj_ref.ref = NULL;

	list_for_each(p, &obj->method_generated) {
		mn = list_entry(p, struct method_name, entry);
		method = mn->method;
		pre_gen_method(&obj_ref, method, &context);
		gen_dml_method_header(obj, method);
		post_gen_method(&obj_ref, method, &context);
		D(";\n");
	}
	list_for_each(p, &obj->childs) {
		tmp = list_entry(p, object_t, entry);
		gen_obj_method_protos(tmp);
	}
}

void gen_device_method_protos(device_t *dev, FILE *f) {
	out = f;
	/*gen device specifi method protos*/
	object_t *obj = &dev->obj;
	time_t timep;
	struct list_head *p;
	object_t *tmp;
	
	time(&timep);
	fprintf(f, "/* Generated by dmlc, don't edit it\n");
	fprintf(f, " * dml object method prototypes\n");
	fprintf(f, " * %s", asctime(localtime(&timep)));
	fprintf(f, " */\n");
	gen_obj_method_protos(obj);
	/*need to generate connect, implement ect method protos*/
	list_for_each(p, &dev->connects) {
		tmp = list_entry(p, object_t, entry);
		gen_obj_method_protos(tmp);
	}
	list_for_each(p, &dev->implements) {
		tmp = list_entry(p, object_t, entry);
		gen_obj_method_protos(tmp);
	}
	gen_device_implement_header(dev, f);
	list_for_each(p, &dev->obj.events) {
		tmp = list_entry(p, object_t, entry);
		gen_obj_method_protos(tmp);
	}
}
