/*
 * gen_method_protos.c: 
 *
 * Copyright (C) 2013 alloc <alloc.young@gmail.com>
 * Skyeye Develop Group, for help please send mail to
 * <skyeye-developer@lists.gro.clinux.org>
 *
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 */
#include "gen_method_protos.h"
#include "gen_implement.h"
#include "gen_port.h"
extern FILE *out;
void gen_obj_method_protos(object_t *obj);
static void gen_none_object(object_t* obj) {
	/* we do not need to do anything */
	return;
}

static void gen_bank_sepcial_obj(object_t* obj) {
	bank_t*  bank = (bank_t*)obj;
	struct list_head *p;
	object_t *t;

	list_for_each(p, &obj->events){
		t = list_entry(p, object_t, entry);
		gen_obj_method_protos(t);
	}
	list_for_each(p, &bank->attributes){
		t = list_entry(p, object_t, entry);
		gen_obj_method_protos(t);
	}
	list_for_each(p, &bank->implements){
		t = list_entry(p, object_t, entry);
		gen_obj_method_protos(t);
	}
	list_for_each(p, &bank->groups){
		t = list_entry(p, object_t, entry);
		gen_obj_method_protos(t);
	}
	return;
}

static void gen_group_special_obj(object_t* obj) {
	struct list_head* p;
	object_t* tmp;
	group_t* gp = (group_t*)obj;
	list_for_each(p, &obj->events){
		tmp = list_entry(p, object_t, entry);
		gen_obj_method_protos(tmp);
	}
	list_for_each(p, &gp->registers){
		tmp = list_entry(p, object_t, entry);
		gen_obj_method_protos(tmp);
	}
	list_for_each(p, &gp->groups){
		tmp = list_entry(p, object_t, entry);
		gen_obj_method_protos(tmp);
	}
}

static void gen_port_special_object(object_t* obj) {
	struct list_head *p;
	object_t *tmp;
	dml_port_t* port = (dml_port_t*)obj;
	list_for_each(p, &obj->events){
		tmp = list_entry(p, object_t, entry);
		gen_obj_method_protos(tmp);
	}
	list_for_each(p, &port->connects){
		tmp = list_entry(p, object_t, entry);
		gen_obj_method_protos(tmp);
	}
	list_for_each(p, &port->attributes){
		tmp = list_entry(p, object_t, entry);
		gen_obj_method_protos(tmp);
	}
	list_for_each(p, &port->implements){
		tmp = list_entry(p, object_t, entry);
		gen_obj_method_protos(tmp);
	}
	return;
}

static void (*gen_obj_special[])(object_t* obj) = {
	[Obj_Type_None] = gen_none_object,
	[Obj_Type_Device] = gen_none_object,
	[Obj_Type_Bank] = gen_bank_sepcial_obj,
	[Obj_Type_Register] = gen_none_object,
	[Obj_Type_Field]  = gen_none_object,
	[Obj_Type_Attribute] = gen_none_object,
	[Obj_Type_Connect]  = gen_none_object,
	[Obj_Type_Port]    = gen_port_special_object,
	[Obj_Type_Implement] = gen_none_object,
	[Obj_Type_Interface] = gen_none_object,
	[Obj_Type_Data]     = gen_none_object,
	[Obj_Type_Event]    = gen_none_object,
	[Obj_Type_Group]    = gen_group_special_obj
};

/**
 * @brief gen_obj_method_protos : generate the prototype of method
 *
 * @param obj : the object of containing method
 */
void gen_obj_method_protos(object_t *obj) {
	struct list_head *p;
	struct method_name *mn;
	tree_t *method;
	object_t *tmp;
	context_t context;
	obj_ref_t obj_ref;
	obj_ref.obj = obj;
	obj_ref.ref = NULL;

	
	list_for_each(p, &obj->method_generated) {
		mn = list_entry(p, struct method_name, entry);
		method = mn->method;
		pre_gen_method(&obj_ref, method, &context);
		gen_dml_method_header(obj, method);
		post_gen_method(&obj_ref, method, &context);
		D(";\n");
	}
	list_for_each(p, &obj->childs) {
		tmp = list_entry(p, object_t, entry);
		gen_obj_method_protos(tmp);
	}
	list_for_each(p, &obj->events) {
		tmp = list_entry(p, object_t, entry);
		gen_obj_method_protos(tmp);
	}
	gen_obj_special[obj->encoding](obj);
}

/**
 * @brief gen_device_method_protos : generate all prototypes of methods in device
 *
 * @param dev : the object of device
 * @param f : file to be generated
 */
void gen_device_method_protos(device_t *dev, FILE *f) {
	out = f;
	/*gen device specifi method protos*/
	object_t *obj = &dev->obj;
	time_t timep;
	struct list_head *p;
	object_t *tmp;
	int i;
	
	time(&timep);
	fprintf(f, "/* Generated by dmlc, don't edit it\n");
	fprintf(f, " * dml object method prototypes\n");
	fprintf(f, " * %s", asctime(localtime(&timep)));
	fprintf(f, " */\n");
	gen_obj_method_protos(obj);
	/*need to generate connect, implement ect method protos*/
	list_for_each(p, &dev->connects) {
		tmp = list_entry(p, object_t, entry);
		gen_obj_method_protos(tmp);
	}
	list_for_each(p, &dev->implements) {
		tmp = list_entry(p, object_t, entry);
		gen_obj_method_protos(tmp);
	}
	list_for_each(p, &dev->attributes) {
		tmp = list_entry(p, object_t, entry);
		gen_obj_method_protos(tmp);
	}
	list_for_each(p, &dev->ports) {
		tmp = list_entry(p, object_t, entry);
		gen_obj_method_protos(tmp);
		dml_port_t *port;
		port = (dml_port_t *)tmp;	
		for(i = 0; i < port->num; i++) {
			gen_obj_method_protos(port->impls[i]);
		}
	}
	gen_device_implement_header(dev, f);
}
