# Written by Michael.Kang(blackfin.kang@gmail.com)
CC = gcc
#CFLAGS = -g
CFLAGS = -g -O2 -Werror-implicit-function-declaration -Werror=return-type \
		-Wmissing-field-initializers -Wuninitialized
INCLUDE = -I. -I./backend/
BUILD_DIR = build
BUILD_DIRS_SKYEYE = $(patsubst %,$(BUILD_DIR)/skyeye/%,$(shell find backend -type d))
BUILD_DIRS_QEMU = $(patsubst %,$(BUILD_DIR)/qemu/%,$(shell find backend -type d))
TARGET_NAME = dmlc

# remove DEBUG information
ifeq ($(RELEASE),yes)
CFLAGS += -D RELEASE
endif

# select platform: qemu skyeye
PLATFORM ?= all
ifeq ($(PLATFORM),skyeye)
BACKEND_NUM = 2
TARGETS = $(TARGET_NAME)_skyeye
else
ifeq ($(PLATFORM),qemu)
BACKEND_NUM = 1
TARGETS = $(TARGET_NAME)_qemu
else
ifeq ($(PLATFORM),all)
TARGETS = $(TARGET_NAME)_skyeye $(TARGET_NAME)_qemu
else
$(error PLATFORM="$(PLATFORM)" not found, PLATFORM is qemu or skyeye.)
endif # all
endif # qemu
endif # skyeye
CFLAGS_QEMU = $(CFLAGS) -D backend=1
CFLAGS_SKYEYE = $(CFLAGS) -D backend=2

# args is diffent on windows or linux
ifeq ($(shell uname),Linux)
	# on linux
	LIBRARY_DIR = 
	LIBRARY = 
else
	# on windows
	LIBRARY_DIR = -L/include
	LIBRARY = -lregex
endif

# find all c files
TOP_FILES := $(wildcard *.c)
BACKEND_FILES  = $(wildcard backend/*.c)
BACKEND_SKYEYE_FILES += $(wildcard backend/skyeye/*.c)
BACKEND_QEMU_FILES += $(wildcard backend/qemu/*.c)
SPECIAL_FILES = Parser.c Lexer.c

# link all c_files string
C_FILES := $(TOP_FILES) $(BACKEND_FILES) $(BACKEND_QEMU_FILES) $(BACKEND_SKYEYE_FILES) $(SPECIAL_FILES)
C_SKYEYE_FILES := $(TOP_FILES) $(BACKEND_FILES) $(BACKEND_SKYEYE_FILES) $(SPECIAL_FILES)
C_QEMU_FILES := $(TOP_FILES) $(BACKEND_FILES) $(BACKEND_QEMU_FILES) $(SPECIAL_FILES)

OBJECTS := $(patsubst %.c,$(BUILD_DIR)/%.o,$(C_FILES))
OBJECTS_SKYEYE := $(patsubst %.c,$(BUILD_DIR)/skyeye/%.o,$(C_SKYEYE_FILES))
OBJECTS_QEMU := $(patsubst %.c,$(BUILD_DIR)/qemu/%.o,$(C_QEMU_FILES))

all: Makefile.build $(BUILD_DIRS_SKYEYE) $(BUILD_DIRS_QEMU) $(TARGETS)
	@echo [ALL] build finished.

skyeye: Makefile.build $(BUILD_DIRS_SKYEYE) $(TARGET_NAME)_skyeye
	@echo [skyeye] build finished.

qemu: Makefile.build $(BUILD_DIRS_QEMU) $(TARGET_NAME)_qemu
	@echo [qemu] build finished.

ifneq ($(MAKECMDGOALS),clean)
ifneq ($(MAKECMDGOALS),distclean)
sinclude $(OBJECTS:.o=.d)
endif
endif

$(TARGET_NAME)_skyeye: $(OBJECTS_SKYEYE)
	@echo [LD] $@
	@$(CC) $(CFLAGS_SKYEYE) $^ -o $@ $(LIBRARY_DIR) $(LIBRARY)

$(TARGET_NAME)_qemu: $(OBJECTS_QEMU)
	@echo [LD] $@
	@$(CC) $(CFLAGS_QEMU) $^ -o $@ $(LIBRARY_DIR) $(LIBRARY)

$(BUILD_DIR)/%.d: %.c
	@set -e; rm -f $@
	@$(CC) $(INCLUDE) -MM $(CFLAGS) $< 2>/dev/null | sed 's#^.*:#$(patsubst %.d,%.o,$@):#' > $@
#	@echo $(CC) $(CFLAGS) -c $< -o $@ $(INCLUDE) $(LIBRARY_DIR) $(LIBRARY) | \
#		sed 's/\.d /\.o /g' | sed 's/^/\t/' >> $@
#	@$(CC) $(INCLUDE) -MM $(CFLAGS) $< | sed -e 's,.*/.o[ :]*,$*.o : ,g' > $@;

$(BUILD_DIR)/skyeye/%.o: %.c
	@echo [CC] $@
	@$(CC) $(CFLAGS_SKYEYE) -c $< -o $@ $(INCLUDE) $(LIBRARY_DIR) $(LIBRARY)

$(BUILD_DIR)/qemu/%.o: %.c
	@echo [CC] $@
	@$(CC) $(CFLAGS_QEMU) -c $< -o $@ $(INCLUDE) $(LIBRARY_DIR) $(LIBRARY)

Lexer.c: gdml.lex
	@echo [FLEX] $@
	@flex gdml.lex
Lexer.h: gdml.lex
	@echo [FLEX] $@
	@flex gdml.lex

Parser.c: gdml.y
	@echo [BISON] $@
	@bison -d gdml.y
Parser.h: gdml.y
	@echo [BISON] $@
	@bison -d gdml.y

install: $(TARGET_NAME)_skyeye $(TARGET_NAME)_qemu include/gdml
	@echo ===== start install =====
	@echo install $(TARGET_NAME)_skyeye $(TARGET_NAME)_skyeye [to /usr/bin]
	@cp -r $(TARGET_NAME)_skyeye /usr/bin
	@cp -r $(TARGET_NAME)_qemu /usr/bin
	@echo install include/gdml [to /usr/include]
	@cp -r include/gdml /usr/include

uninstall: /usr/bin/$(TARGET_NAME)_skyeye /usr/bin/$(TARGET_NAME)_qemu /usr/include/gdml
	@echo ===== start uninstall =====
	@echo uninstall $(TARGET_NAME)_skyeye $(TARGET_NAME)_qemu [from /usr/bin]
	@rm -rf /usr/bin/$(TARGET_NAME)_skyeye /usr/bin/$(TARGET_NAME)_qemu
	@echo uninstall lib/gdml [from /usr/include]
	@rm -rf /usr/include/gdml

check: $(TARGET_NAME)_skyeye $(TARGET_NAME)_qemu ../include/gdml output
	@echo ===== start check =====
	./$(TARGET_NAME)_skyeye testcase/simple-device.dml 1>/dev/null
	./$(TARGET_NAME)_qemu testcase/simple-device.dml 1>/dev/null

../include/gdml:
	cp -r include ../

output:
	mkdir -p output

$(BUILD_DIRS_SKYEYE):
	mkdir -p $(BUILD_DIRS_SKYEYE)

$(BUILD_DIRS_QEMU):
	mkdir -p $(BUILD_DIRS_QEMU)

clean:
	@echo ===== start clean =====
	-rm Parser.* Lexer.* dmlc_* tags -rf
	-rm output/* -rf
	-find . -name "*.d" | xargs rm -f
	-find . -name "*.o" | xargs rm -f

distclean: clean
	-rm build Makefile.build -rf
	-rm Makefile -rf

.PHONY: clean check install uninstall

#TOP_FILES := Parser.c Lexer.c symbol.c ast.c dmlc.c debug_color.c stack.c expression.c \
#			 decl.c parse_str.c pre_parse_dml.c import.c
#GEN_FILES := object.c ref.c $(wildcard gen_*.c) 
#dmlc: $(C_FILES) $(gen_objs) $(backend)
#	gcc $(CFLAGS) -g -o dml  Parser.c Lexer.c symbol.c ast.c  dmlc.c qemu_code_gen.c debug_color.c stack.c expression.c decl.c parse_str.c \
#		object.c qemu_platform.c gen_common.c ref.c qemu_object_headfile.c  gen_once_noplatform.c gen_object.c gen_utility.c gen_expression.c \
#		gen_method_protos.c pre_parse_dml.c import.c

#c_files: Parser.c Lexer.c symbol.c ast.c  dmlc.c qemu_code_gen.c debug_color.c stack.c expression.c decl.c parse_str.c object.c \
#		 gen_common.c qemu_platform.c ref.c qemu_object_headfile.c gen_once_noplatform.c gen_object.c gen_utility.c pre_parse_dml.c import.c
#module_test: symbol
#
#symbol: symbol.c
#	gcc -g -DSYMBOL_DEBUG -o symbol symbol.c
