/* Generated by dmlc, not to edit it */
/* Sat Oct 12 17:30:23 2013
 */

#ifndef UART_DEVICE_H
#define UART_DEVICE_H

#include <simics/base_types.h>
#include <simics/core/object_model.h>
#include <simics/core/object_class.h>
#include <simics/generic_transaction.h>
#include <simics/bank_access.h>
#include <simics/dev_iface.h>
#include "uart_device_struct.h"

typedef enum uart_device_log_group {
	Register_Read = 1,
	Register_Write = 2
} uart_device_log_group_t;

void uart_device_hard_reset(uart_device_t *_obj);
void uart_device_soft_reset(uart_device_t *_obj);

#endif
