/* 
 * uart_device.c
 * Generated by dmlc, not to edit it
 * Sat Oct 12 17:30:23 2013
 */

#include  <string.h>
#include "uart_device.h"
#include "uart_device_protos.c"

static exception_type_t
regs_read(conf_object_t *obj, physical_address_t addr, void *buf, size_t count) {
	uart_device_t *_dev = (uart_device_t *)obj;
	generic_transaction_t memop;
	bool ret = 0;
	UNUSED(ret);
	uint64_t val;

	memset(&memop, 0, sizeof(memop));
	SIM_set_mem_op(&memop, !SIM_Trn_Write);
	ret = _DML_M_regs__access(_dev, &memop, (physical_address_t)addr, (physical_address_t)count);
	val = SIM_mem_op_get_value(&memop);
	memcpy(buf, &val, count);
	return No_exp;
}

static exception_type_t
regs_write(conf_object_t *obj, physical_address_t addr, const void *buf, size_t count) {
	uart_device_t *_dev = (uart_device_t *)obj;
	generic_transaction_t memop;
	bool ret = 0;
	UNUSED(ret);
	uint64_t val = *(uint64 *)buf;

	memset(&memop, 0, sizeof(memop));
	SIM_set_mem_op(&memop, SIM_Trn_Write);
	SIM_mem_op_set_value(&memop, val);
	ret = _DML_M_regs__access(_dev, &memop, (physical_address_t)addr, (physical_address_t)count);
	return No_exp;
}

/*
static void
uart_device_mmio_setup(uart_device_t *_dev, const char *objname) {
	{
		_dev->mr_regs.conf_obj = &_dev->obj;
		_dev->mr_regs.read = regs_read;
		_dev->mr_regs.write = regs_write;
		SKY_register_interface(&_dev->mr_regs, objname, MEMORY_SPACE_INTF_NAME);
	}
}
*/

static conf_object_t  *uart_device_create(const char *name) {
	/*
	uart_device_t *_dev = skyeye_mm_zero(sizeof(*_dev));
	conf_object_register(&_dev->obj, name);
	bool v1_exec = 0;
	UNUSED(v1_exec);

	uart_device_hard_reset(_dev);
	v1_exec = _DML_M_init(_dev);
	uart_device_mmio_setup(_dev, name);
	*/
	uart_device_t *_dev = (uart_device_t*) MM_ZALLOC(sizeof(*_dev));
	conf_object_register(&_dev->obj, name);
	bool v1_exec = 0;
	UNUSED(v1_exec);

	uart_device_hard_reset(_dev);
	v1_exec = _DML_M_init(_dev);
	return &_dev->obj;
}

void uart_device_hard_reset(uart_device_t *obj) {
	bool v2_exec;
	UNUSED(v2_exec);

	v2_exec = _DML_M_hard_reset(obj);
}

void uart_device_soft_reset(uart_device_t *obj) {
	bool v3_exec;
	UNUSED(v3_exec);

	v3_exec = _DML_M_soft_reset(obj);
}

static bool
_DML_M_regs__read_access(uart_device_t *_dev, generic_transaction_t *memop, physical_address_t offset, physical_address_t size, bool *success, uint64 *readvalue)
{
	{
		{
			bool v4_exec = 0;
			{
				{
					uint64 v5_offset = offset;
					int64 v5_size = size;
					int64 v5_size2;
					*readvalue = 0;
					switch(v5_offset / 4)
					{
						case 0:
							{
								uint8 v6_lsb;
								uint8 v6_msb;
								v5_size2 = v5_size < 4 - v5_offset ? v5_size : 4 - v5_offset;
								v6_lsb = (v5_offset - 0) * 8;
								v6_msb = v6_lsb + v5_size2 * 8;
								{
									uint64 v7_ret_value  = 0;
									{
										v4_exec = _DML_M_regs__ulcon__read_access(_dev, memop, v6_msb, v6_lsb, &v7_ret_value);
										if(v4_exec)
											return 1;
									}
									*readvalue = v7_ret_value;
								}
								goto found;
							}
						case 1:
							{
								uint8 v8_lsb;
								uint8 v8_msb;
								v5_size2 = v5_size < 8 - v5_offset ? v5_size : 8 - v5_offset;
								v8_lsb = (v5_offset - 4) * 8;
								v8_msb = v8_lsb + v5_size2 * 8;
								{
									uint64 v9_ret_value  = 0;
									{
										v4_exec = _DML_M_regs__ucon__read_access(_dev, memop, v8_msb, v8_lsb, &v9_ret_value);
										if(v4_exec)
											return 1;
									}
									*readvalue = v9_ret_value;
								}
								goto found;
							}
						case 2:
							{
								uint8 v10_lsb;
								uint8 v10_msb;
								v5_size2 = v5_size < 12 - v5_offset ? v5_size : 12 - v5_offset;
								v10_lsb = (v5_offset - 8) * 8;
								v10_msb = v10_lsb + v5_size2 * 8;
								{
									uint64 v11_ret_value  = 0;
									{
										v4_exec = _DML_M_regs__ufcon__read_access(_dev, memop, v10_msb, v10_lsb, &v11_ret_value);
										if(v4_exec)
											return 1;
									}
									*readvalue = v11_ret_value;
								}
								goto found;
							}
						case 3:
							{
								uint8 v12_lsb;
								uint8 v12_msb;
								v5_size2 = v5_size < 16 - v5_offset ? v5_size : 16 - v5_offset;
								v12_lsb = (v5_offset - 12) * 8;
								v12_msb = v12_lsb + v5_size2 * 8;
								{
									uint64 v13_ret_value  = 0;
									{
										v4_exec = _DML_M_regs__umcon__read_access(_dev, memop, v12_msb, v12_lsb, &v13_ret_value);
										if(v4_exec)
											return 1;
									}
									*readvalue = v13_ret_value;
								}
								goto found;
							}
						case 4:
							{
								uint8 v14_lsb;
								uint8 v14_msb;
								v5_size2 = v5_size < 20 - v5_offset ? v5_size : 20 - v5_offset;
								v14_lsb = (v5_offset - 16) * 8;
								v14_msb = v14_lsb + v5_size2 * 8;
								{
									uint64 v15_ret_value  = 0;
									{
										v4_exec = _DML_M_regs__utrstat__read_access(_dev, memop, v14_msb, v14_lsb, &v15_ret_value);
										if(v4_exec)
											return 1;
									}
									*readvalue = v15_ret_value;
								}
								goto found;
							}
						case 5:
							{
								uint8 v16_lsb;
								uint8 v16_msb;
								v5_size2 = v5_size < 24 - v5_offset ? v5_size : 24 - v5_offset;
								v16_lsb = (v5_offset - 20) * 8;
								v16_msb = v16_lsb + v5_size2 * 8;
								{
									uint64 v17_ret_value  = 0;
									{
										v4_exec = _DML_M_regs__uerstat__read_access(_dev, memop, v16_msb, v16_lsb, &v17_ret_value);
										if(v4_exec)
											return 1;
									}
									*readvalue = v17_ret_value;
								}
								goto found;
							}
						case 6:
							{
								uint8 v18_lsb;
								uint8 v18_msb;
								v5_size2 = v5_size < 28 - v5_offset ? v5_size : 28 - v5_offset;
								v18_lsb = (v5_offset - 24) * 8;
								v18_msb = v18_lsb + v5_size2 * 8;
								{
									uint64 v19_ret_value  = 0;
									{
										v4_exec = _DML_M_regs__ufstat__read_access(_dev, memop, v18_msb, v18_lsb, &v19_ret_value);
										if(v4_exec)
											return 1;
									}
									*readvalue = v19_ret_value;
								}
								goto found;
							}
						case 7:
							{
								uint8 v20_lsb;
								uint8 v20_msb;
								v5_size2 = v5_size < 32 - v5_offset ? v5_size : 32 - v5_offset;
								v20_lsb = (v5_offset - 28) * 8;
								v20_msb = v20_lsb + v5_size2 * 8;
								{
									uint64 v21_ret_value  = 0;
									{
										v4_exec = _DML_M_regs__umstat__read_access(_dev, memop, v20_msb, v20_lsb, &v21_ret_value);
										if(v4_exec)
											return 1;
									}
									*readvalue = v21_ret_value;
								}
								goto found;
							}
						case 8:
							{
								uint8 v22_lsb;
								uint8 v22_msb;
								v5_size2 = v5_size < 36 - v5_offset ? v5_size : 36 - v5_offset;
								v22_lsb = (v5_offset - 32) * 8;
								v22_msb = v22_lsb + v5_size2 * 8;
								{
									uint64 v23_ret_value  = 0;
									{
										v4_exec = _DML_M_regs__utxh__read_access(_dev, memop, v22_msb, v22_lsb, &v23_ret_value);
										if(v4_exec)
											return 1;
									}
									*readvalue = v23_ret_value;
								}
								goto found;
							}
						case 9:
							{
								uint8 v24_lsb;
								uint8 v24_msb;
								v5_size2 = v5_size < 40 - v5_offset ? v5_size : 40 - v5_offset;
								v24_lsb = (v5_offset - 36) * 8;
								v24_msb = v24_lsb + v5_size2 * 8;
								{
									uint64 v25_ret_value  = 0;
									{
										v4_exec = _DML_M_regs__urxh__read_access(_dev, memop, v24_msb, v24_lsb, &v25_ret_value);
										if(v4_exec)
											return 1;
									}
									*readvalue = v25_ret_value;
								}
								goto found;
							}
						case 10:
							{
								uint8 v26_lsb;
								uint8 v26_msb;
								v5_size2 = v5_size < 44 - v5_offset ? v5_size : 44 - v5_offset;
								v26_lsb = (v5_offset - 40) * 8;
								v26_msb = v26_lsb + v5_size2 * 8;
								{
									uint64 v27_ret_value  = 0;
									{
										v4_exec = _DML_M_regs__ubrdiv__read_access(_dev, memop, v26_msb, v26_lsb, &v27_ret_value);
										if(v4_exec)
											return 1;
									}
									*readvalue = v27_ret_value;
								}
								goto found;
							}
						case 11:
							{
								uint8 v28_lsb;
								uint8 v28_msb;
								v5_size2 = v5_size < 48 - v5_offset ? v5_size : 48 - v5_offset;
								v28_lsb = (v5_offset - 44) * 8;
								v28_msb = v28_lsb + v5_size2 * 8;
								{
									uint64 v29_ret_value  = 0;
									{
										v4_exec = _DML_M_regs__ubrdivslot__read_access(_dev, memop, v28_msb, v28_lsb, &v29_ret_value);
										if(v4_exec)
											return 1;
									}
									*readvalue = v29_ret_value;
								}
								goto found;
							}
						case 12:
							{
								uint8 v30_lsb;
								uint8 v30_msb;
								v5_size2 = v5_size < 52 - v5_offset ? v5_size : 52 - v5_offset;
								v30_lsb = (v5_offset - 48) * 8;
								v30_msb = v30_lsb + v5_size2 * 8;
								{
									uint64 v31_ret_value  = 0;
									{
										v4_exec = _DML_M_regs__uintp__read_access(_dev, memop, v30_msb, v30_lsb, &v31_ret_value);
										if(v4_exec)
											return 1;
									}
									*readvalue = v31_ret_value;
								}
								goto found;
							}
						case 13:
							{
								uint8 v32_lsb;
								uint8 v32_msb;
								v5_size2 = v5_size < 56 - v5_offset ? v5_size : 56 - v5_offset;
								v32_lsb = (v5_offset - 52) * 8;
								v32_msb = v32_lsb + v5_size2 * 8;
								{
									uint64 v33_ret_value  = 0;
									{
										v4_exec = _DML_M_regs__uintsp__read_access(_dev, memop, v32_msb, v32_lsb, &v33_ret_value);
										if(v4_exec)
											return 1;
									}
									*readvalue = v33_ret_value;
								}
								goto found;
							}
						case 14:
							{
								uint8 v34_lsb;
								uint8 v34_msb;
								v5_size2 = v5_size < 60 - v5_offset ? v5_size : 60 - v5_offset;
								v34_lsb = (v5_offset - 56) * 8;
								v34_msb = v34_lsb + v5_size2 * 8;
								{
									uint64 v35_ret_value  = 0;
									{
										v4_exec = _DML_M_regs__uintm__read_access(_dev, memop, v34_msb, v34_lsb, &v35_ret_value);
										if(v4_exec)
											return 1;
									}
									*readvalue = v35_ret_value;
								}
								goto found;
							}
					}
					*success = 0;
					goto exit1;
				found:
					*success = v5_size == v5_size2;
				}
			exit1:;
			}
		}
		return 0;
	}
}

static bool 
_DML_M_regs__write_access(uart_device_t *_dev, generic_transaction_t *memop, physical_address_t offset, physical_address_t size, uint64 writevalue, bool *success)
{
	{
		{
			bool v36_exec = 0;
			{
				{
					uint64 v37_offset = offset;
					int64 v37_size = size;
					int64 v37_size2;
					switch(v37_offset / 4 )
					{
						case 0:
							{
								uint8 v38_lsb;
								uint8 v38_msb;
								v37_size2 = v37_size < 4 - v37_offset ? v37_size : 4 - v37_offset;
								v38_lsb = (v37_offset - 0) * 8;
								v38_msb = v38_lsb + v37_size2 * 8;
								{
									v36_exec = _DML_M_regs__ulcon__write_access(_dev, memop, v38_msb, v38_lsb, writevalue);
									if(v36_exec)
										return 1;
								}
								goto found;
							}
						case 1:
							{
								uint8 v40_lsb;
								uint8 v40_msb;
								v37_size2 = v37_size < 8 - v37_offset ? v37_size : 8 - v37_offset;
								v40_lsb = (v37_offset - 4) * 8;
								v40_msb = v40_lsb + v37_size2 * 8;
								{
									v36_exec = _DML_M_regs__ucon__write_access(_dev, memop, v40_msb, v40_lsb, writevalue);
									if(v36_exec)
										return 1;
								}
								goto found;
							}
						case 2:
							{
								uint8 v42_lsb;
								uint8 v42_msb;
								v37_size2 = v37_size < 12 - v37_offset ? v37_size : 12 - v37_offset;
								v42_lsb = (v37_offset - 8) * 8;
								v42_msb = v42_lsb + v37_size2 * 8;
								{
									v36_exec = _DML_M_regs__ufcon__write_access(_dev, memop, v42_msb, v42_lsb, writevalue);
									if(v36_exec)
										return 1;
								}
								goto found;
							}
						case 3:
							{
								uint8 v44_lsb;
								uint8 v44_msb;
								v37_size2 = v37_size < 16 - v37_offset ? v37_size : 16 - v37_offset;
								v44_lsb = (v37_offset - 12) * 8;
								v44_msb = v44_lsb + v37_size2 * 8;
								{
									v36_exec = _DML_M_regs__umcon__write_access(_dev, memop, v44_msb, v44_lsb, writevalue);
									if(v36_exec)
										return 1;
								}
								goto found;
							}
						case 4:
							{
								uint8 v46_lsb;
								uint8 v46_msb;
								v37_size2 = v37_size < 20 - v37_offset ? v37_size : 20 - v37_offset;
								v46_lsb = (v37_offset - 16) * 8;
								v46_msb = v46_lsb + v37_size2 * 8;
								{
									v36_exec = _DML_M_regs__utrstat__write_access(_dev, memop, v46_msb, v46_lsb, writevalue);
									if(v36_exec)
										return 1;
								}
								goto found;
							}
						case 5:
							{
								uint8 v48_lsb;
								uint8 v48_msb;
								v37_size2 = v37_size < 24 - v37_offset ? v37_size : 24 - v37_offset;
								v48_lsb = (v37_offset - 20) * 8;
								v48_msb = v48_lsb + v37_size2 * 8;
								{
									v36_exec = _DML_M_regs__uerstat__write_access(_dev, memop, v48_msb, v48_lsb, writevalue);
									if(v36_exec)
										return 1;
								}
								goto found;
							}
						case 6:
							{
								uint8 v50_lsb;
								uint8 v50_msb;
								v37_size2 = v37_size < 28 - v37_offset ? v37_size : 28 - v37_offset;
								v50_lsb = (v37_offset - 24) * 8;
								v50_msb = v50_lsb + v37_size2 * 8;
								{
									v36_exec = _DML_M_regs__ufstat__write_access(_dev, memop, v50_msb, v50_lsb, writevalue);
									if(v36_exec)
										return 1;
								}
								goto found;
							}
						case 7:
							{
								uint8 v52_lsb;
								uint8 v52_msb;
								v37_size2 = v37_size < 32 - v37_offset ? v37_size : 32 - v37_offset;
								v52_lsb = (v37_offset - 28) * 8;
								v52_msb = v52_lsb + v37_size2 * 8;
								{
									v36_exec = _DML_M_regs__umstat__write_access(_dev, memop, v52_msb, v52_lsb, writevalue);
									if(v36_exec)
										return 1;
								}
								goto found;
							}
						case 8:
							{
								uint8 v54_lsb;
								uint8 v54_msb;
								v37_size2 = v37_size < 36 - v37_offset ? v37_size : 36 - v37_offset;
								v54_lsb = (v37_offset - 32) * 8;
								v54_msb = v54_lsb + v37_size2 * 8;
								{
									v36_exec = _DML_M_regs__utxh__write_access(_dev, memop, v54_msb, v54_lsb, writevalue);
									if(v36_exec)
										return 1;
								}
								goto found;
							}
						case 9:
							{
								uint8 v56_lsb;
								uint8 v56_msb;
								v37_size2 = v37_size < 40 - v37_offset ? v37_size : 40 - v37_offset;
								v56_lsb = (v37_offset - 36) * 8;
								v56_msb = v56_lsb + v37_size2 * 8;
								{
									v36_exec = _DML_M_regs__urxh__write_access(_dev, memop, v56_msb, v56_lsb, writevalue);
									if(v36_exec)
										return 1;
								}
								goto found;
							}
						case 10:
							{
								uint8 v58_lsb;
								uint8 v58_msb;
								v37_size2 = v37_size < 44 - v37_offset ? v37_size : 44 - v37_offset;
								v58_lsb = (v37_offset - 40) * 8;
								v58_msb = v58_lsb + v37_size2 * 8;
								{
									v36_exec = _DML_M_regs__ubrdiv__write_access(_dev, memop, v58_msb, v58_lsb, writevalue);
									if(v36_exec)
										return 1;
								}
								goto found;
							}
						case 11:
							{
								uint8 v60_lsb;
								uint8 v60_msb;
								v37_size2 = v37_size < 48 - v37_offset ? v37_size : 48 - v37_offset;
								v60_lsb = (v37_offset - 44) * 8;
								v60_msb = v60_lsb + v37_size2 * 8;
								{
									v36_exec = _DML_M_regs__ubrdivslot__write_access(_dev, memop, v60_msb, v60_lsb, writevalue);
									if(v36_exec)
										return 1;
								}
								goto found;
							}
						case 12:
							{
								uint8 v62_lsb;
								uint8 v62_msb;
								v37_size2 = v37_size < 52 - v37_offset ? v37_size : 52 - v37_offset;
								v62_lsb = (v37_offset - 48) * 8;
								v62_msb = v62_lsb + v37_size2 * 8;
								{
									v36_exec = _DML_M_regs__uintp__write_access(_dev, memop, v62_msb, v62_lsb, writevalue);
									if(v36_exec)
										return 1;
								}
								goto found;
							}
						case 13:
							{
								uint8 v64_lsb;
								uint8 v64_msb;
								v37_size2 = v37_size < 56 - v37_offset ? v37_size : 56 - v37_offset;
								v64_lsb = (v37_offset - 52) * 8;
								v64_msb = v64_lsb + v37_size2 * 8;
								{
									v36_exec = _DML_M_regs__uintsp__write_access(_dev, memop, v64_msb, v64_lsb, writevalue);
									if(v36_exec)
										return 1;
								}
								goto found;
							}
						case 14:
							{
								uint8 v66_lsb;
								uint8 v66_msb;
								v37_size2 = v37_size < 60 - v37_offset ? v37_size : 60 - v37_offset;
								v66_lsb = (v37_offset - 56) * 8;
								v66_msb = v66_lsb + v37_size2 * 8;
								{
									v36_exec = _DML_M_regs__uintm__write_access(_dev, memop, v66_msb, v66_lsb, writevalue);
									if(v36_exec)
										return 1;
								}
								goto found;
							}
					}
					*success = 0;
					goto exit2;
				found:
					*success = v37_size == v37_size2;
				}
			exit2:;
			}
		}
		return 0;
	}
}

static bool				
_DML_M_init(uart_device_t *_dev)
{
	{
		{
			bool v68_exec = 0;
			UNUSED(v68_exec);
			{
				_dev->regs.utrstat = 0x6;
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_hard_reset(uart_device_t *_dev)
{
	{
		{
			bool v69_exec = 0;
			UNUSED(v69_exec);
			{
				{
					{
						v69_exec = _DML_M_regs__hard_reset(_dev);
						if(v69_exec) {
							return 1;
						} 
					} 
				} 

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_soft_reset(uart_device_t *_dev)
{
	{
		{
			bool v70_exec = 0;
			UNUSED(v70_exec);
			{
				{
					{
						v70_exec = _DML_M_regs__soft_reset(_dev);
						if(v70_exec) {
							return 1;
						} 
					} 
				} 

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__access(uart_device_t *_dev, generic_transaction_t *memop, uint32 offset, uint32 size)
{
	{
		{
			bool v71_exec = 0;
			UNUSED(v71_exec);
			{
				if ((size > 8)){
					
					
				} 
				if (SIM_mem_op_is_read(memop)){
					v71_exec = _DML_M_regs__read_access_memop(_dev, memop, offset, size);
					if(v71_exec) {
						return 1;
					} 

				} else {
					uint64 v72_writeval;
					v71_exec = _DML_M_regs__get_write_value(_dev, memop, &v72_writeval);
					if(v71_exec) {
						return 1;
					} 

					v71_exec = _DML_M_regs__write_access_memop(_dev, memop, offset, size, v72_writeval);
					if(v71_exec) {
						return 1;
					} 

				} 
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__hard_reset(uart_device_t *_dev)
{
	{
		{
			bool v73_exec = 0;
			UNUSED(v73_exec);
			{
				{
					{
						v73_exec = _DML_M_regs__ulcon__hard_reset_register(_dev);
						if(v73_exec) {
							return 1;
						} 
					} 
{
						v73_exec = _DML_M_regs__ucon__hard_reset_register(_dev);
						if(v73_exec) {
							return 1;
						} 
					} 
{
						v73_exec = _DML_M_regs__ufcon__hard_reset_register(_dev);
						if(v73_exec) {
							return 1;
						} 
					} 
{
						v73_exec = _DML_M_regs__umcon__hard_reset_register(_dev);
						if(v73_exec) {
							return 1;
						} 
					} 
{
						v73_exec = _DML_M_regs__utrstat__hard_reset_register(_dev);
						if(v73_exec) {
							return 1;
						} 
					} 
{
						v73_exec = _DML_M_regs__uerstat__hard_reset_register(_dev);
						if(v73_exec) {
							return 1;
						} 
					} 
{
						v73_exec = _DML_M_regs__ufstat__hard_reset_register(_dev);
						if(v73_exec) {
							return 1;
						} 
					} 
{
						v73_exec = _DML_M_regs__umstat__hard_reset_register(_dev);
						if(v73_exec) {
							return 1;
						} 
					} 
{
						v73_exec = _DML_M_regs__utxh__hard_reset_register(_dev);
						if(v73_exec) {
							return 1;
						} 
					} 
{
						v73_exec = _DML_M_regs__urxh__hard_reset_register(_dev);
						if(v73_exec) {
							return 1;
						} 
					} 
{
						v73_exec = _DML_M_regs__ubrdiv__hard_reset_register(_dev);
						if(v73_exec) {
							return 1;
						} 
					} 
{
						v73_exec = _DML_M_regs__ubrdivslot__hard_reset_register(_dev);
						if(v73_exec) {
							return 1;
						} 
					} 
{
						v73_exec = _DML_M_regs__uintp__hard_reset_register(_dev);
						if(v73_exec) {
							return 1;
						} 
					} 
{
						v73_exec = _DML_M_regs__uintsp__hard_reset_register(_dev);
						if(v73_exec) {
							return 1;
						} 
					} 
{
						v73_exec = _DML_M_regs__uintm__hard_reset_register(_dev);
						if(v73_exec) {
							return 1;
						} 
					} 
				} 

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__soft_reset(uart_device_t *_dev)
{
	{
		{
			bool v74_exec = 0;
			UNUSED(v74_exec);
			{
				{
					{
						v74_exec = _DML_M_regs__ulcon__soft_reset_register(_dev);
						if(v74_exec) {
							return 1;
						} 
					} 
{
						v74_exec = _DML_M_regs__ucon__soft_reset_register(_dev);
						if(v74_exec) {
							return 1;
						} 
					} 
{
						v74_exec = _DML_M_regs__ufcon__soft_reset_register(_dev);
						if(v74_exec) {
							return 1;
						} 
					} 
{
						v74_exec = _DML_M_regs__umcon__soft_reset_register(_dev);
						if(v74_exec) {
							return 1;
						} 
					} 
{
						v74_exec = _DML_M_regs__utrstat__soft_reset_register(_dev);
						if(v74_exec) {
							return 1;
						} 
					} 
{
						v74_exec = _DML_M_regs__uerstat__soft_reset_register(_dev);
						if(v74_exec) {
							return 1;
						} 
					} 
{
						v74_exec = _DML_M_regs__ufstat__soft_reset_register(_dev);
						if(v74_exec) {
							return 1;
						} 
					} 
{
						v74_exec = _DML_M_regs__umstat__soft_reset_register(_dev);
						if(v74_exec) {
							return 1;
						} 
					} 
{
						v74_exec = _DML_M_regs__utxh__soft_reset_register(_dev);
						if(v74_exec) {
							return 1;
						} 
					} 
{
						v74_exec = _DML_M_regs__urxh__soft_reset_register(_dev);
						if(v74_exec) {
							return 1;
						} 
					} 
{
						v74_exec = _DML_M_regs__ubrdiv__soft_reset_register(_dev);
						if(v74_exec) {
							return 1;
						} 
					} 
{
						v74_exec = _DML_M_regs__ubrdivslot__soft_reset_register(_dev);
						if(v74_exec) {
							return 1;
						} 
					} 
{
						v74_exec = _DML_M_regs__uintp__soft_reset_register(_dev);
						if(v74_exec) {
							return 1;
						} 
					} 
{
						v74_exec = _DML_M_regs__uintsp__soft_reset_register(_dev);
						if(v74_exec) {
							return 1;
						} 
					} 
{
						v74_exec = _DML_M_regs__uintm__soft_reset_register(_dev);
						if(v74_exec) {
							return 1;
						} 
					} 
				} 

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__read_access_memop(uart_device_t *_dev, generic_transaction_t *memop, uint32 offset, uint32 size)
{
	{
		{
			bool v75_exec = 0;
			UNUSED(v75_exec);
			{
				bool v76_success = 0;
				uint64 v77_val = 0;
				v75_exec = _DML_M_regs__read_access(_dev, memop, offset, size, &v76_success, &v77_val);
				if(v75_exec) {
					return 1;
				} 

				if (v76_success){
					v75_exec = _DML_M_regs__finalize_read_access(_dev, memop, v77_val);
					if(v75_exec) {
						return 1;
					} 

				} 
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__get_write_value(uart_device_t *_dev, generic_transaction_t *memop, uint64 *writeval)
{
	{
		{
			bool v78_exec = 0;
			UNUSED(v78_exec);
			{
				*writeval = SIM_mem_op_get_value(memop);
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__write_access_memop(uart_device_t *_dev, generic_transaction_t *memop, uint32 offset, uint32 size, uint64 value)
{
	{
		{
			bool v79_exec = 0;
			UNUSED(v79_exec);
			{
				bool v80_success = 0;
				v79_exec = _DML_M_regs__write_access(_dev, memop, offset, size, value, &v80_success);
				if(v79_exec) {
					return 1;
				} 

				if (v80_success){
					

				} 
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__finalize_read_access(uart_device_t *_dev, generic_transaction_t *memop, uint64 val)
{
	{
		{
			bool v81_exec = 0;
			UNUSED(v81_exec);
			{
				v81_exec = _DML_M_regs__set_read_value(_dev, memop, val);
				if(v81_exec) {
					return 1;
				} 

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__set_read_value(uart_device_t *_dev, generic_transaction_t *memop, uint64 value)
{
	{
		{
			bool v82_exec = 0;
			UNUSED(v82_exec);
			{
				SIM_mem_op_set_value(memop, value);
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__ulcon__read_access(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value)
{
	{
		{
			bool v83_exec = 0;
			UNUSED(v83_exec);
			{
				uint64 v84_readval;
				v83_exec = _DML_M_regs__ulcon__read_access_main(_dev, memop, msb1, lsb, &v84_readval);
				if(v83_exec) {
					return 1;
				} 

				*value = v84_readval;
				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__ulcon__write_access(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value)
{
	{
		{
			bool v85_exec = 0;
			UNUSED(v85_exec);
			{
				v85_exec = _DML_M_regs__ulcon__write_access_main(_dev, memop, msb1, lsb, value);
				if(v85_exec) {
					return 1;
				} 

				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__ulcon__hard_reset_register(uart_device_t *_dev)
{
	{
		{
			bool v86_exec = 0;
			UNUSED(v86_exec);
			{
				{
					v86_exec = _DML_M_regs__ulcon__hard_reset(_dev);
					if(v86_exec) {
						return 1;
					} 

				} 
				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__ulcon__soft_reset_register(uart_device_t *_dev)
{
	{
		{
			bool v87_exec = 0;
			UNUSED(v87_exec);
			{
				v87_exec = _DML_M_regs__ulcon__hard_reset_register(_dev);
				if(v87_exec) {
					return 1;
				} 

				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__ulcon__read_access_main(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value)
{
	{
		{
			bool v88_exec = 0;
			UNUSED(v88_exec);
			{
				uint32 v89_fieldval = 0;
				{
					v88_exec = _DML_M_regs__ulcon__read(_dev, &v89_fieldval);
					if(v88_exec) {
						return 1;
					} 

				} 
				*value = v89_fieldval >> lsb & MASK1((msb1 - 1) - lsb);
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__ulcon__write_access_main(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value)
{
	{
		{
			bool v90_exec = 0;
			UNUSED(v90_exec);
			{
				uint32 v91_fieldval = 0;
				{
					if (((lsb > 0) || ((msb1 - lsb) < 0x20))){
						v90_exec = _DML_M_regs__ulcon__get(_dev, &v91_fieldval);
						if(v90_exec) {
							return 1;
						} 

						v91_fieldval = MIX(v91_fieldval, (uint64 )value << lsb, (uint64 )MASK1((msb1 - 1) - lsb) << lsb);
						v90_exec = _DML_M_regs__ulcon__write(_dev, v91_fieldval);
						if(v90_exec) {
							return 1;
						} 

					} else {
						v90_exec = _DML_M_regs__ulcon__write(_dev, value);
						if(v90_exec) {
							return 1;
						} 

					} 
				} 
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__ulcon__hard_reset(uart_device_t *_dev)
{
	{
		{
			bool v92_exec = 0;
			UNUSED(v92_exec);
			{
				_dev->regs.ulcon = 0x0;
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__ulcon__read(uart_device_t *_dev, uint32 *value)
{
	{
		{
			bool v93_exec = 0;
			UNUSED(v93_exec);
			{
				*value = _dev->regs.ulcon;
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__ulcon__get(uart_device_t *_dev, uint32 *value)
{
	{
		{
			bool v94_exec = 0;
			UNUSED(v94_exec);
			{
				{
					*value = _dev->regs.ulcon;
				} 
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__ulcon__write(uart_device_t *_dev, uint32 value)
{
	{
		{
			bool v95_exec = 0;
			UNUSED(v95_exec);
			{
				_dev->regs.ulcon = value;
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__ucon__read_access(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value)
{
	{
		{
			bool v83_exec = 0;
			UNUSED(v83_exec);
			{
				uint64 v84_readval;
				v83_exec = _DML_M_regs__ucon__read_access_main(_dev, memop, msb1, lsb, &v84_readval);
				if(v83_exec) {
					return 1;
				} 

				*value = v84_readval;
				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__ucon__write_access(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value)
{
	{
		{
			bool v85_exec = 0;
			UNUSED(v85_exec);
			{
				v85_exec = _DML_M_regs__ucon__write_access_main(_dev, memop, msb1, lsb, value);
				if(v85_exec) {
					return 1;
				} 

				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__ucon__hard_reset_register(uart_device_t *_dev)
{
	{
		{
			bool v86_exec = 0;
			UNUSED(v86_exec);
			{
				{
					v86_exec = _DML_M_regs__ucon__hard_reset(_dev);
					if(v86_exec) {
						return 1;
					} 

				} 
				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__ucon__soft_reset_register(uart_device_t *_dev)
{
	{
		{
			bool v87_exec = 0;
			UNUSED(v87_exec);
			{
				v87_exec = _DML_M_regs__ucon__hard_reset_register(_dev);
				if(v87_exec) {
					return 1;
				} 

				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__ucon__read_access_main(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value)
{
	{
		{
			bool v88_exec = 0;
			UNUSED(v88_exec);
			{
				uint32 v89_fieldval = 0;
				{
					v88_exec = _DML_M_regs__ucon__read(_dev, &v89_fieldval);
					if(v88_exec) {
						return 1;
					} 

				} 
				*value = v89_fieldval >> lsb & MASK1((msb1 - 1) - lsb);
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__ucon__write_access_main(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value)
{
	{
		{
			bool v90_exec = 0;
			UNUSED(v90_exec);
			{
				uint32 v91_fieldval = 0;
				{
					if (((lsb > 0) || ((msb1 - lsb) < 0x20))){
						v90_exec = _DML_M_regs__ucon__get(_dev, &v91_fieldval);
						if(v90_exec) {
							return 1;
						} 

						v91_fieldval = MIX(v91_fieldval, (uint64 )value << lsb, (uint64 )MASK1((msb1 - 1) - lsb) << lsb);
						v90_exec = _DML_M_regs__ucon__write(_dev, v91_fieldval);
						if(v90_exec) {
							return 1;
						} 

					} else {
						v90_exec = _DML_M_regs__ucon__write(_dev, value);
						if(v90_exec) {
							return 1;
						} 

					} 
				} 
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__ucon__hard_reset(uart_device_t *_dev)
{
	{
		{
			bool v92_exec = 0;
			UNUSED(v92_exec);
			{
				_dev->regs.ucon = 0x0;
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__ucon__read(uart_device_t *_dev, uint32 *value)
{
	{
		{
			bool v93_exec = 0;
			UNUSED(v93_exec);
			{
				*value = _dev->regs.ucon;
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__ucon__get(uart_device_t *_dev, uint32 *value)
{
	{
		{
			bool v94_exec = 0;
			UNUSED(v94_exec);
			{
				{
					*value = _dev->regs.ucon;
				} 
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__ucon__write(uart_device_t *_dev, uint32 value)
{
	{
		{
			bool v95_exec = 0;
			UNUSED(v95_exec);
			{
				_dev->regs.ucon = value;
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__ufcon__read_access(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value)
{
	{
		{
			bool v83_exec = 0;
			UNUSED(v83_exec);
			{
				uint64 v84_readval;
				v83_exec = _DML_M_regs__ufcon__read_access_main(_dev, memop, msb1, lsb, &v84_readval);
				if(v83_exec) {
					return 1;
				} 

				*value = v84_readval;
				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__ufcon__write_access(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value)
{
	{
		{
			bool v85_exec = 0;
			UNUSED(v85_exec);
			{
				v85_exec = _DML_M_regs__ufcon__write_access_main(_dev, memop, msb1, lsb, value);
				if(v85_exec) {
					return 1;
				} 

				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__ufcon__hard_reset_register(uart_device_t *_dev)
{
	{
		{
			bool v86_exec = 0;
			UNUSED(v86_exec);
			{
				{
					v86_exec = _DML_M_regs__ufcon__hard_reset(_dev);
					if(v86_exec) {
						return 1;
					} 

				} 
				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__ufcon__soft_reset_register(uart_device_t *_dev)
{
	{
		{
			bool v87_exec = 0;
			UNUSED(v87_exec);
			{
				v87_exec = _DML_M_regs__ufcon__hard_reset_register(_dev);
				if(v87_exec) {
					return 1;
				} 

				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__ufcon__read_access_main(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value)
{
	{
		{
			bool v88_exec = 0;
			UNUSED(v88_exec);
			{
				uint32 v89_fieldval = 0;
				{
					v88_exec = _DML_M_regs__ufcon__read(_dev, &v89_fieldval);
					if(v88_exec) {
						return 1;
					} 

				} 
				*value = v89_fieldval >> lsb & MASK1((msb1 - 1) - lsb);
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__ufcon__write_access_main(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value)
{
	{
		{
			bool v90_exec = 0;
			UNUSED(v90_exec);
			{
				uint32 v91_fieldval = 0;
				{
					if (((lsb > 0) || ((msb1 - lsb) < 0x20))){
						v90_exec = _DML_M_regs__ufcon__get(_dev, &v91_fieldval);
						if(v90_exec) {
							return 1;
						} 

						v91_fieldval = MIX(v91_fieldval, (uint64 )value << lsb, (uint64 )MASK1((msb1 - 1) - lsb) << lsb);
						v90_exec = _DML_M_regs__ufcon__write(_dev, v91_fieldval);
						if(v90_exec) {
							return 1;
						} 

					} else {
						v90_exec = _DML_M_regs__ufcon__write(_dev, value);
						if(v90_exec) {
							return 1;
						} 

					} 
				} 
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__ufcon__hard_reset(uart_device_t *_dev)
{
	{
		{
			bool v92_exec = 0;
			UNUSED(v92_exec);
			{
				_dev->regs.ufcon = 0x0;
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__ufcon__read(uart_device_t *_dev, uint32 *value)
{
	{
		{
			bool v93_exec = 0;
			UNUSED(v93_exec);
			{
				*value = _dev->regs.ufcon;
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__ufcon__get(uart_device_t *_dev, uint32 *value)
{
	{
		{
			bool v94_exec = 0;
			UNUSED(v94_exec);
			{
				{
					*value = _dev->regs.ufcon;
				} 
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__ufcon__write(uart_device_t *_dev, uint32 value)
{
	{
		{
			bool v95_exec = 0;
			UNUSED(v95_exec);
			{
				_dev->regs.ufcon = value;
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__umcon__read_access(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value)
{
	{
		{
			bool v83_exec = 0;
			UNUSED(v83_exec);
			{
				uint64 v84_readval;
				v83_exec = _DML_M_regs__umcon__read_access_main(_dev, memop, msb1, lsb, &v84_readval);
				if(v83_exec) {
					return 1;
				} 

				*value = v84_readval;
				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__umcon__write_access(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value)
{
	{
		{
			bool v85_exec = 0;
			UNUSED(v85_exec);
			{
				v85_exec = _DML_M_regs__umcon__write_access_main(_dev, memop, msb1, lsb, value);
				if(v85_exec) {
					return 1;
				} 

				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__umcon__hard_reset_register(uart_device_t *_dev)
{
	{
		{
			bool v86_exec = 0;
			UNUSED(v86_exec);
			{
				{
					v86_exec = _DML_M_regs__umcon__hard_reset(_dev);
					if(v86_exec) {
						return 1;
					} 

				} 
				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__umcon__soft_reset_register(uart_device_t *_dev)
{
	{
		{
			bool v87_exec = 0;
			UNUSED(v87_exec);
			{
				v87_exec = _DML_M_regs__umcon__hard_reset_register(_dev);
				if(v87_exec) {
					return 1;
				} 

				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__umcon__read_access_main(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value)
{
	{
		{
			bool v88_exec = 0;
			UNUSED(v88_exec);
			{
				uint32 v89_fieldval = 0;
				{
					v88_exec = _DML_M_regs__umcon__read(_dev, &v89_fieldval);
					if(v88_exec) {
						return 1;
					} 

				} 
				*value = v89_fieldval >> lsb & MASK1((msb1 - 1) - lsb);
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__umcon__write_access_main(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value)
{
	{
		{
			bool v90_exec = 0;
			UNUSED(v90_exec);
			{
				uint32 v91_fieldval = 0;
				{
					if (((lsb > 0) || ((msb1 - lsb) < 0x20))){
						v90_exec = _DML_M_regs__umcon__get(_dev, &v91_fieldval);
						if(v90_exec) {
							return 1;
						} 

						v91_fieldval = MIX(v91_fieldval, (uint64 )value << lsb, (uint64 )MASK1((msb1 - 1) - lsb) << lsb);
						v90_exec = _DML_M_regs__umcon__write(_dev, v91_fieldval);
						if(v90_exec) {
							return 1;
						} 

					} else {
						v90_exec = _DML_M_regs__umcon__write(_dev, value);
						if(v90_exec) {
							return 1;
						} 

					} 
				} 
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__umcon__hard_reset(uart_device_t *_dev)
{
	{
		{
			bool v92_exec = 0;
			UNUSED(v92_exec);
			{
				_dev->regs.umcon = 0x0;
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__umcon__read(uart_device_t *_dev, uint32 *value)
{
	{
		{
			bool v93_exec = 0;
			UNUSED(v93_exec);
			{
				*value = _dev->regs.umcon;
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__umcon__get(uart_device_t *_dev, uint32 *value)
{
	{
		{
			bool v94_exec = 0;
			UNUSED(v94_exec);
			{
				{
					*value = _dev->regs.umcon;
				} 
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__umcon__write(uart_device_t *_dev, uint32 value)
{
	{
		{
			bool v95_exec = 0;
			UNUSED(v95_exec);
			{
				_dev->regs.umcon = value;
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__utrstat__read_access(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value)
{
	{
		{
			bool v83_exec = 0;
			UNUSED(v83_exec);
			{
				uint64 v84_readval;
				v83_exec = _DML_M_regs__utrstat__read_access_main(_dev, memop, msb1, lsb, &v84_readval);
				if(v83_exec) {
					return 1;
				} 

				*value = v84_readval;
				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__utrstat__write_access(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value)
{
	{
		{
			bool v85_exec = 0;
			UNUSED(v85_exec);
			{
				v85_exec = _DML_M_regs__utrstat__write_access_main(_dev, memop, msb1, lsb, value);
				if(v85_exec) {
					return 1;
				} 

				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__utrstat__hard_reset_register(uart_device_t *_dev)
{
	{
		{
			bool v86_exec = 0;
			UNUSED(v86_exec);
			{
				{
					v86_exec = _DML_M_regs__utrstat__hard_reset(_dev);
					if(v86_exec) {
						return 1;
					} 

				} 
				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__utrstat__soft_reset_register(uart_device_t *_dev)
{
	{
		{
			bool v87_exec = 0;
			UNUSED(v87_exec);
			{
				v87_exec = _DML_M_regs__utrstat__hard_reset_register(_dev);
				if(v87_exec) {
					return 1;
				} 

				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__utrstat__read_access_main(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value)
{
	{
		{
			bool v88_exec = 0;
			UNUSED(v88_exec);
			{
				uint32 v89_fieldval = 0;
				{
					v88_exec = _DML_M_regs__utrstat__read(_dev, &v89_fieldval);
					if(v88_exec) {
						return 1;
					} 

				} 
				*value = v89_fieldval >> lsb & MASK1((msb1 - 1) - lsb);
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__utrstat__write_access_main(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value)
{
	{
		{
			bool v90_exec = 0;
			UNUSED(v90_exec);
			{
				uint32 v91_fieldval = 0;
				{
					if (((lsb > 0) || ((msb1 - lsb) < 0x20))){
						v90_exec = _DML_M_regs__utrstat__get(_dev, &v91_fieldval);
						if(v90_exec) {
							return 1;
						} 

						v91_fieldval = MIX(v91_fieldval, (uint64 )value << lsb, (uint64 )MASK1((msb1 - 1) - lsb) << lsb);
						v90_exec = _DML_M_regs__utrstat__write(_dev, v91_fieldval);
						if(v90_exec) {
							return 1;
						} 

					} else {
						v90_exec = _DML_M_regs__utrstat__write(_dev, value);
						if(v90_exec) {
							return 1;
						} 

					} 
				} 
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__utrstat__hard_reset(uart_device_t *_dev)
{
	{
		{
			bool v92_exec = 0;
			UNUSED(v92_exec);
			{
				_dev->regs.utrstat = 0x0;
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__utrstat__read(uart_device_t *_dev, uint32 *value)
{
	{
		{
			bool v93_exec = 0;
			UNUSED(v93_exec);
			{
				*value = _dev->regs.utrstat;
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__utrstat__get(uart_device_t *_dev, uint32 *value)
{
	{
		{
			bool v94_exec = 0;
			UNUSED(v94_exec);
			{
				{
					*value = _dev->regs.utrstat;
				} 
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__utrstat__write(uart_device_t *_dev, uint32 value)
{
	{
		{
			bool v95_exec = 0;
			UNUSED(v95_exec);
			{
				_dev->regs.utrstat = value;
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__uerstat__read_access(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value)
{
	{
		{
			bool v83_exec = 0;
			UNUSED(v83_exec);
			{
				uint64 v84_readval;
				v83_exec = _DML_M_regs__uerstat__read_access_main(_dev, memop, msb1, lsb, &v84_readval);
				if(v83_exec) {
					return 1;
				} 

				*value = v84_readval;
				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__uerstat__write_access(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value)
{
	{
		{
			bool v85_exec = 0;
			UNUSED(v85_exec);
			{
				v85_exec = _DML_M_regs__uerstat__write_access_main(_dev, memop, msb1, lsb, value);
				if(v85_exec) {
					return 1;
				} 

				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__uerstat__hard_reset_register(uart_device_t *_dev)
{
	{
		{
			bool v86_exec = 0;
			UNUSED(v86_exec);
			{
				{
					v86_exec = _DML_M_regs__uerstat__hard_reset(_dev);
					if(v86_exec) {
						return 1;
					} 

				} 
				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__uerstat__soft_reset_register(uart_device_t *_dev)
{
	{
		{
			bool v87_exec = 0;
			UNUSED(v87_exec);
			{
				v87_exec = _DML_M_regs__uerstat__hard_reset_register(_dev);
				if(v87_exec) {
					return 1;
				} 

				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__uerstat__read_access_main(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value)
{
	{
		{
			bool v88_exec = 0;
			UNUSED(v88_exec);
			{
				uint32 v89_fieldval = 0;
				{
					v88_exec = _DML_M_regs__uerstat__read(_dev, &v89_fieldval);
					if(v88_exec) {
						return 1;
					} 

				} 
				*value = v89_fieldval >> lsb & MASK1((msb1 - 1) - lsb);
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__uerstat__write_access_main(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value)
{
	{
		{
			bool v90_exec = 0;
			UNUSED(v90_exec);
			{
				uint32 v91_fieldval = 0;
				{
					if (((lsb > 0) || ((msb1 - lsb) < 0x20))){
						v90_exec = _DML_M_regs__uerstat__get(_dev, &v91_fieldval);
						if(v90_exec) {
							return 1;
						} 

						v91_fieldval = MIX(v91_fieldval, (uint64 )value << lsb, (uint64 )MASK1((msb1 - 1) - lsb) << lsb);
						v90_exec = _DML_M_regs__uerstat__write(_dev, v91_fieldval);
						if(v90_exec) {
							return 1;
						} 

					} else {
						v90_exec = _DML_M_regs__uerstat__write(_dev, value);
						if(v90_exec) {
							return 1;
						} 

					} 
				} 
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__uerstat__hard_reset(uart_device_t *_dev)
{
	{
		{
			bool v92_exec = 0;
			UNUSED(v92_exec);
			{
				_dev->regs.uerstat = 0x0;
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__uerstat__read(uart_device_t *_dev, uint32 *value)
{
	{
		{
			bool v93_exec = 0;
			UNUSED(v93_exec);
			{
				*value = _dev->regs.uerstat;
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__uerstat__get(uart_device_t *_dev, uint32 *value)
{
	{
		{
			bool v94_exec = 0;
			UNUSED(v94_exec);
			{
				{
					*value = _dev->regs.uerstat;
				} 
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__uerstat__write(uart_device_t *_dev, uint32 value)
{
	{
		{
			bool v95_exec = 0;
			UNUSED(v95_exec);
			{
				_dev->regs.uerstat = value;
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__ufstat__read_access(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value)
{
	{
		{
			bool v83_exec = 0;
			UNUSED(v83_exec);
			{
				uint64 v84_readval;
				v83_exec = _DML_M_regs__ufstat__read_access_main(_dev, memop, msb1, lsb, &v84_readval);
				if(v83_exec) {
					return 1;
				} 

				*value = v84_readval;
				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__ufstat__write_access(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value)
{
	{
		{
			bool v85_exec = 0;
			UNUSED(v85_exec);
			{
				v85_exec = _DML_M_regs__ufstat__write_access_main(_dev, memop, msb1, lsb, value);
				if(v85_exec) {
					return 1;
				} 

				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__ufstat__hard_reset_register(uart_device_t *_dev)
{
	{
		{
			bool v86_exec = 0;
			UNUSED(v86_exec);
			{
				{
					v86_exec = _DML_M_regs__ufstat__hard_reset(_dev);
					if(v86_exec) {
						return 1;
					} 

				} 
				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__ufstat__soft_reset_register(uart_device_t *_dev)
{
	{
		{
			bool v87_exec = 0;
			UNUSED(v87_exec);
			{
				v87_exec = _DML_M_regs__ufstat__hard_reset_register(_dev);
				if(v87_exec) {
					return 1;
				} 

				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__ufstat__read_access_main(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value)
{
	{
		{
			bool v88_exec = 0;
			UNUSED(v88_exec);
			{
				uint32 v89_fieldval = 0;
				{
					v88_exec = _DML_M_regs__ufstat__read(_dev, &v89_fieldval);
					if(v88_exec) {
						return 1;
					} 

				} 
				*value = v89_fieldval >> lsb & MASK1((msb1 - 1) - lsb);
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__ufstat__write_access_main(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value)
{
	{
		{
			bool v90_exec = 0;
			UNUSED(v90_exec);
			{
				uint32 v91_fieldval = 0;
				{
					if (((lsb > 0) || ((msb1 - lsb) < 0x20))){
						v90_exec = _DML_M_regs__ufstat__get(_dev, &v91_fieldval);
						if(v90_exec) {
							return 1;
						} 

						v91_fieldval = MIX(v91_fieldval, (uint64 )value << lsb, (uint64 )MASK1((msb1 - 1) - lsb) << lsb);
						v90_exec = _DML_M_regs__ufstat__write(_dev, v91_fieldval);
						if(v90_exec) {
							return 1;
						} 

					} else {
						v90_exec = _DML_M_regs__ufstat__write(_dev, value);
						if(v90_exec) {
							return 1;
						} 

					} 
				} 
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__ufstat__hard_reset(uart_device_t *_dev)
{
	{
		{
			bool v92_exec = 0;
			UNUSED(v92_exec);
			{
				_dev->regs.ufstat = 0x0;
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__ufstat__read(uart_device_t *_dev, uint32 *value)
{
	{
		{
			bool v93_exec = 0;
			UNUSED(v93_exec);
			{
				*value = _dev->regs.ufstat;
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__ufstat__get(uart_device_t *_dev, uint32 *value)
{
	{
		{
			bool v94_exec = 0;
			UNUSED(v94_exec);
			{
				{
					*value = _dev->regs.ufstat;
				} 
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__ufstat__write(uart_device_t *_dev, uint32 value)
{
	{
		{
			bool v95_exec = 0;
			UNUSED(v95_exec);
			{
				_dev->regs.ufstat = value;
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__umstat__read_access(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value)
{
	{
		{
			bool v83_exec = 0;
			UNUSED(v83_exec);
			{
				uint64 v84_readval;
				v83_exec = _DML_M_regs__umstat__read_access_main(_dev, memop, msb1, lsb, &v84_readval);
				if(v83_exec) {
					return 1;
				} 

				*value = v84_readval;
				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__umstat__write_access(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value)
{
	{
		{
			bool v85_exec = 0;
			UNUSED(v85_exec);
			{
				v85_exec = _DML_M_regs__umstat__write_access_main(_dev, memop, msb1, lsb, value);
				if(v85_exec) {
					return 1;
				} 

				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__umstat__hard_reset_register(uart_device_t *_dev)
{
	{
		{
			bool v86_exec = 0;
			UNUSED(v86_exec);
			{
				{
					v86_exec = _DML_M_regs__umstat__hard_reset(_dev);
					if(v86_exec) {
						return 1;
					} 

				} 
				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__umstat__soft_reset_register(uart_device_t *_dev)
{
	{
		{
			bool v87_exec = 0;
			UNUSED(v87_exec);
			{
				v87_exec = _DML_M_regs__umstat__hard_reset_register(_dev);
				if(v87_exec) {
					return 1;
				} 

				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__umstat__read_access_main(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value)
{
	{
		{
			bool v88_exec = 0;
			UNUSED(v88_exec);
			{
				uint32 v89_fieldval = 0;
				{
					v88_exec = _DML_M_regs__umstat__read(_dev, &v89_fieldval);
					if(v88_exec) {
						return 1;
					} 

				} 
				*value = v89_fieldval >> lsb & MASK1((msb1 - 1) - lsb);
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__umstat__write_access_main(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value)
{
	{
		{
			bool v90_exec = 0;
			UNUSED(v90_exec);
			{
				uint32 v91_fieldval = 0;
				{
					if (((lsb > 0) || ((msb1 - lsb) < 0x20))){
						v90_exec = _DML_M_regs__umstat__get(_dev, &v91_fieldval);
						if(v90_exec) {
							return 1;
						} 

						v91_fieldval = MIX(v91_fieldval, (uint64 )value << lsb, (uint64 )MASK1((msb1 - 1) - lsb) << lsb);
						v90_exec = _DML_M_regs__umstat__write(_dev, v91_fieldval);
						if(v90_exec) {
							return 1;
						} 

					} else {
						v90_exec = _DML_M_regs__umstat__write(_dev, value);
						if(v90_exec) {
							return 1;
						} 

					} 
				} 
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__umstat__hard_reset(uart_device_t *_dev)
{
	{
		{
			bool v92_exec = 0;
			UNUSED(v92_exec);
			{
				_dev->regs.umstat = 0x0;
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__umstat__read(uart_device_t *_dev, uint32 *value)
{
	{
		{
			bool v93_exec = 0;
			UNUSED(v93_exec);
			{
				*value = _dev->regs.umstat;
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__umstat__get(uart_device_t *_dev, uint32 *value)
{
	{
		{
			bool v94_exec = 0;
			UNUSED(v94_exec);
			{
				{
					*value = _dev->regs.umstat;
				} 
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__umstat__write(uart_device_t *_dev, uint32 value)
{
	{
		{
			bool v95_exec = 0;
			UNUSED(v95_exec);
			{
				_dev->regs.umstat = value;
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__utxh__read_access(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value)
{
	{
		{
			bool v83_exec = 0;
			UNUSED(v83_exec);
			{
				uint64 v84_readval;
				v83_exec = _DML_M_regs__utxh__read_access_main(_dev, memop, msb1, lsb, &v84_readval);
				if(v83_exec) {
					return 1;
				} 

				*value = v84_readval;
				v83_exec = _DML_M_regs__utxh__after_read(_dev, memop);
				if(v83_exec) {
					return 1;
				} 

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__utxh__write_access(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value)
{
	{
		{
			bool v85_exec = 0;
			UNUSED(v85_exec);
			{
				v85_exec = _DML_M_regs__utxh__write_access_main(_dev, memop, msb1, lsb, value);
				if(v85_exec) {
					return 1;
				} 

				v85_exec = _DML_M_regs__utxh__after_write(_dev, memop);
				if(v85_exec) {
					return 1;
				} 

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__utxh__hard_reset_register(uart_device_t *_dev)
{
	{
		{
			bool v86_exec = 0;
			UNUSED(v86_exec);
			{
				{
					v86_exec = _DML_M_regs__utxh__hard_reset(_dev);
					if(v86_exec) {
						return 1;
					} 

				} 
				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__utxh__soft_reset_register(uart_device_t *_dev)
{
	{
		{
			bool v87_exec = 0;
			UNUSED(v87_exec);
			{
				v87_exec = _DML_M_regs__utxh__hard_reset_register(_dev);
				if(v87_exec) {
					return 1;
				} 

				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__utxh__read_access_main(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value)
{
	{
		{
			bool v88_exec = 0;
			UNUSED(v88_exec);
			{
				uint32 v89_fieldval = 0;
				{
					v88_exec = _DML_M_regs__utxh__read(_dev, &v89_fieldval);
					if(v88_exec) {
						return 1;
					} 

				} 
				*value = v89_fieldval >> lsb & MASK1((msb1 - 1) - lsb);
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__utxh__after_read(uart_device_t *_dev, generic_transaction_t *memop)
{
	{
		{
			bool v96_exec = 0;
			UNUSED(v96_exec);
			{
				_dev->regs.utrstat &= -2;
				_dev->regs.ufstat &= -2;
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__utxh__write_access_main(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value)
{
	{
		{
			bool v90_exec = 0;
			UNUSED(v90_exec);
			{
				uint32 v91_fieldval = 0;
				{
					if (((lsb > 0) || ((msb1 - lsb) < 0x20))){
						v90_exec = _DML_M_regs__utxh__get(_dev, &v91_fieldval);
						if(v90_exec) {
							return 1;
						} 

						v91_fieldval = MIX(v91_fieldval, (uint64 )value << lsb, (uint64 )MASK1((msb1 - 1) - lsb) << lsb);
						v90_exec = _DML_M_regs__utxh__write(_dev, v91_fieldval);
						if(v90_exec) {
							return 1;
						} 

					} else {
						v90_exec = _DML_M_regs__utxh__write(_dev, value);
						if(v90_exec) {
							return 1;
						} 

					} 
				} 
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__utxh__after_write(uart_device_t *_dev, generic_transaction_t *memop)
{
	{
		{
			bool v97_exec = 0;
			UNUSED(v97_exec);
			{
				_dev->regs.utrstat |= 0x6;
				_dev->regs.ufstat &= 0xff;
				_dev->regs.uintp |= ((0x4 & ~_dev->regs.uintm));
				_dev->regs.uintsp |= 0x4;
				_dev->irq.signal->signal_raise(_dev->irq.obj);
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__utxh__hard_reset(uart_device_t *_dev)
{
	{
		{
			bool v92_exec = 0;
			UNUSED(v92_exec);
			{
				_dev->regs.utxh = 0x0;
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__utxh__read(uart_device_t *_dev, uint32 *value)
{
	{
		{
			bool v93_exec = 0;
			UNUSED(v93_exec);
			{
				*value = _dev->regs.utxh;
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__utxh__get(uart_device_t *_dev, uint32 *value)
{
	{
		{
			bool v94_exec = 0;
			UNUSED(v94_exec);
			{
				{
					*value = _dev->regs.utxh;
				} 
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__utxh__write(uart_device_t *_dev, uint32 value)
{
	{
		{
			bool v98_exec = 0;
			UNUSED(v98_exec);
			{
				_dev->regs.utxh = value;
				int v99_c = value;
				_dev->uart_proxy.serial_device->write(_dev->uart_proxy.obj, v99_c);
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__urxh__read_access(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value)
{
	{
		{
			bool v83_exec = 0;
			UNUSED(v83_exec);
			{
				uint64 v84_readval;
				v83_exec = _DML_M_regs__urxh__read_access_main(_dev, memop, msb1, lsb, &v84_readval);
				if(v83_exec) {
					return 1;
				} 

				*value = v84_readval;
				v83_exec = _DML_M_regs__urxh__after_read(_dev, memop);
				if(v83_exec) {
					return 1;
				} 

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__urxh__write_access(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value)
{
	{
		{
			bool v85_exec = 0;
			UNUSED(v85_exec);
			{
				v85_exec = _DML_M_regs__urxh__write_access_main(_dev, memop, msb1, lsb, value);
				if(v85_exec) {
					return 1;
				} 

				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__urxh__hard_reset_register(uart_device_t *_dev)
{
	{
		{
			bool v86_exec = 0;
			UNUSED(v86_exec);
			{
				{
					v86_exec = _DML_M_regs__urxh__hard_reset(_dev);
					if(v86_exec) {
						return 1;
					} 

				} 
				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__urxh__soft_reset_register(uart_device_t *_dev)
{
	{
		{
			bool v87_exec = 0;
			UNUSED(v87_exec);
			{
				v87_exec = _DML_M_regs__urxh__hard_reset_register(_dev);
				if(v87_exec) {
					return 1;
				} 

				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__urxh__read_access_main(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value)
{
	{
		{
			bool v88_exec = 0;
			UNUSED(v88_exec);
			{
				uint32 v89_fieldval = 0;
				{
					v88_exec = _DML_M_regs__urxh__read(_dev, &v89_fieldval);
					if(v88_exec) {
						return 1;
					} 

				} 
				*value = v89_fieldval >> lsb & MASK1((msb1 - 1) - lsb);
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__urxh__after_read(uart_device_t *_dev, generic_transaction_t *memop)
{
	{
		{
			bool v100_exec = 0;
			UNUSED(v100_exec);
			{
				_dev->regs.utrstat &= (-2);
				_dev->regs.ufstat &= (-2);
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__urxh__write_access_main(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value)
{
	{
		{
			bool v90_exec = 0;
			UNUSED(v90_exec);
			{
				uint32 v91_fieldval = 0;
				{
					if (((lsb > 0) || ((msb1 - lsb) < 0x20))){
						v90_exec = _DML_M_regs__urxh__get(_dev, &v91_fieldval);
						if(v90_exec) {
							return 1;
						} 

						v91_fieldval = MIX(v91_fieldval, (uint64 )value << lsb, (uint64 )MASK1((msb1 - 1) - lsb) << lsb);
						v90_exec = _DML_M_regs__urxh__write(_dev, v91_fieldval);
						if(v90_exec) {
							return 1;
						} 

					} else {
						v90_exec = _DML_M_regs__urxh__write(_dev, value);
						if(v90_exec) {
							return 1;
						} 

					} 
				} 
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__urxh__hard_reset(uart_device_t *_dev)
{
	{
		{
			bool v92_exec = 0;
			UNUSED(v92_exec);
			{
				_dev->regs.urxh = 0x0;
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__urxh__read(uart_device_t *_dev, uint32 *value)
{
	{
		{
			bool v93_exec = 0;
			UNUSED(v93_exec);
			{
				*value = _dev->regs.urxh;
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__urxh__get(uart_device_t *_dev, uint32 *value)
{
	{
		{
			bool v94_exec = 0;
			UNUSED(v94_exec);
			{
				{
					*value = _dev->regs.urxh;
				} 
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__urxh__write(uart_device_t *_dev, uint32 value)
{
	{
		{
			bool v95_exec = 0;
			UNUSED(v95_exec);
			{
				_dev->regs.urxh = value;
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__ubrdiv__read_access(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value)
{
	{
		{
			bool v83_exec = 0;
			UNUSED(v83_exec);
			{
				uint64 v84_readval;
				v83_exec = _DML_M_regs__ubrdiv__read_access_main(_dev, memop, msb1, lsb, &v84_readval);
				if(v83_exec) {
					return 1;
				} 

				*value = v84_readval;
				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__ubrdiv__write_access(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value)
{
	{
		{
			bool v85_exec = 0;
			UNUSED(v85_exec);
			{
				v85_exec = _DML_M_regs__ubrdiv__write_access_main(_dev, memop, msb1, lsb, value);
				if(v85_exec) {
					return 1;
				} 

				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__ubrdiv__hard_reset_register(uart_device_t *_dev)
{
	{
		{
			bool v86_exec = 0;
			UNUSED(v86_exec);
			{
				{
					v86_exec = _DML_M_regs__ubrdiv__hard_reset(_dev);
					if(v86_exec) {
						return 1;
					} 

				} 
				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__ubrdiv__soft_reset_register(uart_device_t *_dev)
{
	{
		{
			bool v87_exec = 0;
			UNUSED(v87_exec);
			{
				v87_exec = _DML_M_regs__ubrdiv__hard_reset_register(_dev);
				if(v87_exec) {
					return 1;
				} 

				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__ubrdiv__read_access_main(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value)
{
	{
		{
			bool v88_exec = 0;
			UNUSED(v88_exec);
			{
				uint32 v89_fieldval = 0;
				{
					v88_exec = _DML_M_regs__ubrdiv__read(_dev, &v89_fieldval);
					if(v88_exec) {
						return 1;
					} 

				} 
				*value = v89_fieldval >> lsb & MASK1((msb1 - 1) - lsb);
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__ubrdiv__write_access_main(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value)
{
	{
		{
			bool v90_exec = 0;
			UNUSED(v90_exec);
			{
				uint32 v91_fieldval = 0;
				{
					if (((lsb > 0) || ((msb1 - lsb) < 0x20))){
						v90_exec = _DML_M_regs__ubrdiv__get(_dev, &v91_fieldval);
						if(v90_exec) {
							return 1;
						} 

						v91_fieldval = MIX(v91_fieldval, (uint64 )value << lsb, (uint64 )MASK1((msb1 - 1) - lsb) << lsb);
						v90_exec = _DML_M_regs__ubrdiv__write(_dev, v91_fieldval);
						if(v90_exec) {
							return 1;
						} 

					} else {
						v90_exec = _DML_M_regs__ubrdiv__write(_dev, value);
						if(v90_exec) {
							return 1;
						} 

					} 
				} 
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__ubrdiv__hard_reset(uart_device_t *_dev)
{
	{
		{
			bool v92_exec = 0;
			UNUSED(v92_exec);
			{
				_dev->regs.ubrdiv = 0x0;
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__ubrdiv__read(uart_device_t *_dev, uint32 *value)
{
	{
		{
			bool v93_exec = 0;
			UNUSED(v93_exec);
			{
				*value = _dev->regs.ubrdiv;
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__ubrdiv__get(uart_device_t *_dev, uint32 *value)
{
	{
		{
			bool v94_exec = 0;
			UNUSED(v94_exec);
			{
				{
					*value = _dev->regs.ubrdiv;
				} 
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__ubrdiv__write(uart_device_t *_dev, uint32 value)
{
	{
		{
			bool v95_exec = 0;
			UNUSED(v95_exec);
			{
				_dev->regs.ubrdiv = value;
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__ubrdivslot__read_access(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value)
{
	{
		{
			bool v83_exec = 0;
			UNUSED(v83_exec);
			{
				uint64 v84_readval;
				v83_exec = _DML_M_regs__ubrdivslot__read_access_main(_dev, memop, msb1, lsb, &v84_readval);
				if(v83_exec) {
					return 1;
				} 

				*value = v84_readval;
				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__ubrdivslot__write_access(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value)
{
	{
		{
			bool v85_exec = 0;
			UNUSED(v85_exec);
			{
				v85_exec = _DML_M_regs__ubrdivslot__write_access_main(_dev, memop, msb1, lsb, value);
				if(v85_exec) {
					return 1;
				} 

				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__ubrdivslot__hard_reset_register(uart_device_t *_dev)
{
	{
		{
			bool v86_exec = 0;
			UNUSED(v86_exec);
			{
				{
					v86_exec = _DML_M_regs__ubrdivslot__hard_reset(_dev);
					if(v86_exec) {
						return 1;
					} 

				} 
				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__ubrdivslot__soft_reset_register(uart_device_t *_dev)
{
	{
		{
			bool v87_exec = 0;
			UNUSED(v87_exec);
			{
				v87_exec = _DML_M_regs__ubrdivslot__hard_reset_register(_dev);
				if(v87_exec) {
					return 1;
				} 

				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__ubrdivslot__read_access_main(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value)
{
	{
		{
			bool v88_exec = 0;
			UNUSED(v88_exec);
			{
				uint32 v89_fieldval = 0;
				{
					v88_exec = _DML_M_regs__ubrdivslot__read(_dev, &v89_fieldval);
					if(v88_exec) {
						return 1;
					} 

				} 
				*value = v89_fieldval >> lsb & MASK1((msb1 - 1) - lsb);
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__ubrdivslot__write_access_main(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value)
{
	{
		{
			bool v90_exec = 0;
			UNUSED(v90_exec);
			{
				uint32 v91_fieldval = 0;
				{
					if (((lsb > 0) || ((msb1 - lsb) < 0x20))){
						v90_exec = _DML_M_regs__ubrdivslot__get(_dev, &v91_fieldval);
						if(v90_exec) {
							return 1;
						} 

						v91_fieldval = MIX(v91_fieldval, (uint64 )value << lsb, (uint64 )MASK1((msb1 - 1) - lsb) << lsb);
						v90_exec = _DML_M_regs__ubrdivslot__write(_dev, v91_fieldval);
						if(v90_exec) {
							return 1;
						} 

					} else {
						v90_exec = _DML_M_regs__ubrdivslot__write(_dev, value);
						if(v90_exec) {
							return 1;
						} 

					} 
				} 
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__ubrdivslot__hard_reset(uart_device_t *_dev)
{
	{
		{
			bool v92_exec = 0;
			UNUSED(v92_exec);
			{
				_dev->regs.ubrdivslot = 0x0;
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__ubrdivslot__read(uart_device_t *_dev, uint32 *value)
{
	{
		{
			bool v93_exec = 0;
			UNUSED(v93_exec);
			{
				*value = _dev->regs.ubrdivslot;
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__ubrdivslot__get(uart_device_t *_dev, uint32 *value)
{
	{
		{
			bool v94_exec = 0;
			UNUSED(v94_exec);
			{
				{
					*value = _dev->regs.ubrdivslot;
				} 
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__ubrdivslot__write(uart_device_t *_dev, uint32 value)
{
	{
		{
			bool v95_exec = 0;
			UNUSED(v95_exec);
			{
				_dev->regs.ubrdivslot = value;
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__uintp__read_access(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value)
{
	{
		{
			bool v83_exec = 0;
			UNUSED(v83_exec);
			{
				uint64 v84_readval;
				v83_exec = _DML_M_regs__uintp__read_access_main(_dev, memop, msb1, lsb, &v84_readval);
				if(v83_exec) {
					return 1;
				} 

				*value = v84_readval;
				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__uintp__write_access(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value)
{
	{
		{
			bool v85_exec = 0;
			UNUSED(v85_exec);
			{
				v85_exec = _DML_M_regs__uintp__write_access_main(_dev, memop, msb1, lsb, value);
				if(v85_exec) {
					return 1;
				} 

				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__uintp__hard_reset_register(uart_device_t *_dev)
{
	{
		{
			bool v86_exec = 0;
			UNUSED(v86_exec);
			{
				{
					v86_exec = _DML_M_regs__uintp__hard_reset(_dev);
					if(v86_exec) {
						return 1;
					} 

				} 
				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__uintp__soft_reset_register(uart_device_t *_dev)
{
	{
		{
			bool v87_exec = 0;
			UNUSED(v87_exec);
			{
				v87_exec = _DML_M_regs__uintp__hard_reset_register(_dev);
				if(v87_exec) {
					return 1;
				} 

				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__uintp__read_access_main(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value)
{
	{
		{
			bool v88_exec = 0;
			UNUSED(v88_exec);
			{
				uint32 v89_fieldval = 0;
				{
					v88_exec = _DML_M_regs__uintp__read(_dev, &v89_fieldval);
					if(v88_exec) {
						return 1;
					} 

				} 
				*value = v89_fieldval >> lsb & MASK1((msb1 - 1) - lsb);
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__uintp__write_access_main(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value)
{
	{
		{
			bool v90_exec = 0;
			UNUSED(v90_exec);
			{
				uint32 v91_fieldval = 0;
				{
					if (((lsb > 0) || ((msb1 - lsb) < 0x20))){
						v90_exec = _DML_M_regs__uintp__get(_dev, &v91_fieldval);
						if(v90_exec) {
							return 1;
						} 

						v91_fieldval = MIX(v91_fieldval, (uint64 )value << lsb, (uint64 )MASK1((msb1 - 1) - lsb) << lsb);
						v90_exec = _DML_M_regs__uintp__write(_dev, v91_fieldval);
						if(v90_exec) {
							return 1;
						} 

					} else {
						v90_exec = _DML_M_regs__uintp__write(_dev, value);
						if(v90_exec) {
							return 1;
						} 

					} 
				} 
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__uintp__hard_reset(uart_device_t *_dev)
{
	{
		{
			bool v92_exec = 0;
			UNUSED(v92_exec);
			{
				_dev->regs.uintp = 0x0;
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__uintp__read(uart_device_t *_dev, uint32 *value)
{
	{
		{
			bool v93_exec = 0;
			UNUSED(v93_exec);
			{
				*value = _dev->regs.uintp;
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__uintp__get(uart_device_t *_dev, uint32 *value)
{
	{
		{
			bool v94_exec = 0;
			UNUSED(v94_exec);
			{
				{
					*value = _dev->regs.uintp;
				} 
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__uintp__write(uart_device_t *_dev, uint32 value)
{
	{
		{
			bool v101_exec = 0;
			UNUSED(v101_exec);
			{
				_dev->regs.uintp &= ~value;
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__uintsp__read_access(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value)
{
	{
		{
			bool v83_exec = 0;
			UNUSED(v83_exec);
			{
				uint64 v84_readval;
				v83_exec = _DML_M_regs__uintsp__read_access_main(_dev, memop, msb1, lsb, &v84_readval);
				if(v83_exec) {
					return 1;
				} 

				*value = v84_readval;
				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__uintsp__write_access(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value)
{
	{
		{
			bool v85_exec = 0;
			UNUSED(v85_exec);
			{
				v85_exec = _DML_M_regs__uintsp__write_access_main(_dev, memop, msb1, lsb, value);
				if(v85_exec) {
					return 1;
				} 

				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__uintsp__hard_reset_register(uart_device_t *_dev)
{
	{
		{
			bool v86_exec = 0;
			UNUSED(v86_exec);
			{
				{
					v86_exec = _DML_M_regs__uintsp__hard_reset(_dev);
					if(v86_exec) {
						return 1;
					} 

				} 
				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__uintsp__soft_reset_register(uart_device_t *_dev)
{
	{
		{
			bool v87_exec = 0;
			UNUSED(v87_exec);
			{
				v87_exec = _DML_M_regs__uintsp__hard_reset_register(_dev);
				if(v87_exec) {
					return 1;
				} 

				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__uintsp__read_access_main(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value)
{
	{
		{
			bool v88_exec = 0;
			UNUSED(v88_exec);
			{
				uint32 v89_fieldval = 0;
				{
					v88_exec = _DML_M_regs__uintsp__read(_dev, &v89_fieldval);
					if(v88_exec) {
						return 1;
					} 

				} 
				*value = v89_fieldval >> lsb & MASK1((msb1 - 1) - lsb);
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__uintsp__write_access_main(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value)
{
	{
		{
			bool v90_exec = 0;
			UNUSED(v90_exec);
			{
				uint32 v91_fieldval = 0;
				{
					if (((lsb > 0) || ((msb1 - lsb) < 0x20))){
						v90_exec = _DML_M_regs__uintsp__get(_dev, &v91_fieldval);
						if(v90_exec) {
							return 1;
						} 

						v91_fieldval = MIX(v91_fieldval, (uint64 )value << lsb, (uint64 )MASK1((msb1 - 1) - lsb) << lsb);
						v90_exec = _DML_M_regs__uintsp__write(_dev, v91_fieldval);
						if(v90_exec) {
							return 1;
						} 

					} else {
						v90_exec = _DML_M_regs__uintsp__write(_dev, value);
						if(v90_exec) {
							return 1;
						} 

					} 
				} 
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__uintsp__hard_reset(uart_device_t *_dev)
{
	{
		{
			bool v92_exec = 0;
			UNUSED(v92_exec);
			{
				_dev->regs.uintsp = 0x0;
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__uintsp__read(uart_device_t *_dev, uint32 *value)
{
	{
		{
			bool v93_exec = 0;
			UNUSED(v93_exec);
			{
				*value = _dev->regs.uintsp;
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__uintsp__get(uart_device_t *_dev, uint32 *value)
{
	{
		{
			bool v94_exec = 0;
			UNUSED(v94_exec);
			{
				{
					*value = _dev->regs.uintsp;
				} 
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__uintsp__write(uart_device_t *_dev, uint32 value)
{
	{
		{
			bool v102_exec = 0;
			UNUSED(v102_exec);
			{
				_dev->regs.uintsp &= ~value;
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__uintm__read_access(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value)
{
	{
		{
			bool v83_exec = 0;
			UNUSED(v83_exec);
			{
				uint64 v84_readval;
				v83_exec = _DML_M_regs__uintm__read_access_main(_dev, memop, msb1, lsb, &v84_readval);
				if(v83_exec) {
					return 1;
				} 

				*value = v84_readval;
				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__uintm__write_access(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value)
{
	{
		{
			bool v85_exec = 0;
			UNUSED(v85_exec);
			{
				v85_exec = _DML_M_regs__uintm__write_access_main(_dev, memop, msb1, lsb, value);
				if(v85_exec) {
					return 1;
				} 

				v85_exec = _DML_M_regs__uintm__after_write(_dev, memop);
				if(v85_exec) {
					return 1;
				} 

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__uintm__hard_reset_register(uart_device_t *_dev)
{
	{
		{
			bool v86_exec = 0;
			UNUSED(v86_exec);
			{
				{
					v86_exec = _DML_M_regs__uintm__hard_reset(_dev);
					if(v86_exec) {
						return 1;
					} 

				} 
				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__uintm__soft_reset_register(uart_device_t *_dev)
{
	{
		{
			bool v87_exec = 0;
			UNUSED(v87_exec);
			{
				v87_exec = _DML_M_regs__uintm__hard_reset_register(_dev);
				if(v87_exec) {
					return 1;
				} 

				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__uintm__read_access_main(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value)
{
	{
		{
			bool v88_exec = 0;
			UNUSED(v88_exec);
			{
				uint32 v89_fieldval = 0;
				{
					v88_exec = _DML_M_regs__uintm__read(_dev, &v89_fieldval);
					if(v88_exec) {
						return 1;
					} 

				} 
				*value = v89_fieldval >> lsb & MASK1((msb1 - 1) - lsb);
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__uintm__write_access_main(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value)
{
	{
		{
			bool v90_exec = 0;
			UNUSED(v90_exec);
			{
				uint32 v91_fieldval = 0;
				{
					if (((lsb > 0) || ((msb1 - lsb) < 0x20))){
						v90_exec = _DML_M_regs__uintm__get(_dev, &v91_fieldval);
						if(v90_exec) {
							return 1;
						} 

						v91_fieldval = MIX(v91_fieldval, (uint64 )value << lsb, (uint64 )MASK1((msb1 - 1) - lsb) << lsb);
						v90_exec = _DML_M_regs__uintm__write(_dev, v91_fieldval);
						if(v90_exec) {
							return 1;
						} 

					} else {
						v90_exec = _DML_M_regs__uintm__write(_dev, value);
						if(v90_exec) {
							return 1;
						} 

					} 
				} 
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__uintm__after_write(uart_device_t *_dev, generic_transaction_t *memop)
{
	{
		{
			bool v103_exec = 0;
			UNUSED(v103_exec);
			{
				_dev->regs.uintp |= ((0x4 & ~_dev->regs.uintm));
				_dev->regs.uintsp |= 0x4;
				_dev->irq.signal->signal_raise(_dev->irq.obj);
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__uintm__hard_reset(uart_device_t *_dev)
{
	{
		{
			bool v92_exec = 0;
			UNUSED(v92_exec);
			{
				_dev->regs.uintm = 0x0;
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__uintm__read(uart_device_t *_dev, uint32 *value)
{
	{
		{
			bool v93_exec = 0;
			UNUSED(v93_exec);
			{
				*value = _dev->regs.uintm;
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__uintm__get(uart_device_t *_dev, uint32 *value)
{
	{
		{
			bool v94_exec = 0;
			UNUSED(v94_exec);
			{
				{
					*value = _dev->regs.uintm;
				} 
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__uintm__write(uart_device_t *_dev, uint32 value)
{
	{
		{
			bool v95_exec = 0;
			UNUSED(v95_exec);
			{
				_dev->regs.uintm = value;
			} 
		}
		return 0;
	}
}

static int uart_proxy_set(void *_, conf_object_t *obj, attr_value_t *val,  attr_value_t *_index) {
	uart_device_t *_dev = (uart_device_t *)obj;
	int ret = 0;
	void const *iface = NULL;
	conf_object_t *peer = NULL;
	const char *port = NULL;
	
	if(SIM_attr_is_object(*val)){
		peer = SIM_attr_object(*val);
	} else if(SIM_attr_is_list(*val)) {
		peer = SIM_attr_object(SIM_attr_list_item(*val, 0));
		port = SIM_attr_string(SIM_attr_list_item(*val, 1));
	}
	if(_dev->uart_proxy.obj == peer && _dev->uart_proxy.port == port) {
		return 0;
	}
	_dev->uart_proxy.obj = peer;
	if(_dev->uart_proxy.port)
		MM_FREE((void *)_dev->uart_proxy.port);
	if(port) {
		_dev->uart_proxy.port = MM_STRDUP(port);
	} else { 
		_dev->uart_proxy.port = NULL;
	}
	if(port) {
		iface = SIM_c_get_port_interface(peer, "serial_device", port);
	} else {
		iface = SIM_c_get_interface(peer, "serial_device");
	}
	_dev->uart_proxy.serial_device = iface;
	return ret;
}

static attr_value_t uart_proxy_get(void *_, conf_object_t *obj, attr_value_t *_index) {
	uart_device_t *_dev = (uart_device_t *)obj;
	int ret = 0;
	UNUSED(ret);
	attr_value_t attr;
	if(_dev->uart_proxy.port) {
		attr = SIM_alloc_attr_list(2);
		SIM_attr_list_set_item(&attr, 0, SIM_make_attr_string(_dev->uart_proxy.port));
		SIM_attr_list_set_item(&attr, 1, SIM_make_attr_obj(_dev->uart_proxy.obj));
	}
	return attr;
}

static int irq_set(void *_, conf_object_t *obj, attr_value_t *val,  attr_value_t *_index) {
	uart_device_t *_dev = (uart_device_t *)obj;
	int ret = 0;
	void const *iface = NULL;
	conf_object_t *peer = NULL;
	const char *port = NULL;
	
	if(SIM_attr_is_object(*val)){
		peer = SIM_attr_object(*val);
	} else if(SIM_attr_is_list(*val)) {
		peer = SIM_attr_object(SIM_attr_list_item(*val, 0));
		port = SIM_attr_string(SIM_attr_list_item(*val, 1));
	}
	if(_dev->irq.obj == peer && _dev->irq.port == port) {
		return 0;
	}
	_dev->irq.obj = peer;
	if(_dev->irq.port)
		MM_FREE((void *)_dev->irq.port);
	if(port) {
		_dev->irq.port = MM_STRDUP(port);
	} else { 
		_dev->irq.port = NULL;
	}
	if(port) {
		iface = SIM_c_get_port_interface(peer, "signal", port);
	} else {
		iface = SIM_c_get_interface(peer, "signal");
	}
	_dev->irq.signal = iface;
	return ret;
}

static attr_value_t irq_get(void *_, conf_object_t *obj, attr_value_t *_index) {
	uart_device_t *_dev = (uart_device_t *)obj;
	int ret = 0;
	UNUSED(ret);
	attr_value_t attr;
	if(_dev->irq.port) {
		attr = SIM_alloc_attr_list(2);
		SIM_attr_list_set_item(&attr, 0, SIM_make_attr_string(_dev->uart_proxy.port));
		SIM_attr_list_set_item(&attr, 1, SIM_make_attr_obj(_dev->uart_proxy.obj));
	}
	return attr;
}

const struct ConnectDescription uart_device_connects[] = {
	[0] = (struct ConnectDescription) {
		.name = "uart_proxy",
		.set = uart_proxy_set,
		.get = uart_proxy_get,
	},
	[1] = (struct ConnectDescription) {
		.name = "irq",
		.set = irq_set,
		.get = irq_get,
	},
	[2] = (struct ConnectDescription) {
		.name = NULL,
		.set = NULL,
		.get = NULL,
	}
};

static const struct InterfaceDescription uart_device_ifaces[] = {
	[0] = {}
};

static const class_resource_t uart_device_resources = {
	.ifaces = uart_device_ifaces,
	.connects = uart_device_connects,
	.ports = NULL,
};

static const bank_access_t regs_access = {
	.read = &regs_read,
	.write = &regs_write,
};

static const struct bank_access_description uart_device_bank_access[] = {
	[0] = (struct bank_access_description) {
		.name = "regs",
		.access = &regs_access,
	},
	[1] = {}
};

static const class_data_t uart_device_data = {
	.new_instance = uart_device_create,
	.finalize_instance = NULL,
	.pre_delete_instance = NULL,
	.delete_instance = NULL,
	.resources = &uart_device_resources,
	.bank_access = uart_device_bank_access,
};

void init_uart_device(void) {
	static conf_class_t class_class = {
		.cls_name = "uart_device",
		.cls_data = &uart_device_data,
	};
	SIM_register_conf_class(class_class.cls_name, &class_class);
}

void init_local(void) {
	init_uart_device();
}
