/* Generated by dmlc, not to edit it */
/* Sat Oct 12 17:30:23 2013
 */
#ifndef UART_DEVICE_STRUCT_H
#define UART_DEVICE_STRUCT_H

typedef struct uart_device uart_device_t;

#define REGS_MR_SIZE 0x3c

struct uart_device {
	conf_object_t obj;
	struct {
		uint32 ulcon;
		uint32 ucon;
		uint32 ufcon;
		uint32 umcon;
		uint32 utrstat;
		uint32 uerstat;
		uint32 ufstat;
		uint32 umstat;
		uint32 utxh;
		uint32 urxh;
		uint32 ubrdiv;
		uint32 ubrdivslot;
		uint32 uintp;
		uint32 uintsp;
		uint32 uintm;
	} regs;
	//MemoryRegion mr_regs;
	struct {
		const char *port;
		conf_object_t *obj;
		const serial_device_interface_t *serial_device;
	} uart_proxy;
	struct {
		const char *port;
		conf_object_t *obj;
		const signal_interface_t *signal;
	} irq;
};

#endif
