/* Generated by dmlc, don't edit it
 * dml object method prototypes
 * Sat Oct 12 17:30:23 2013
 */

static bool				
_DML_M_init(uart_device_t *_dev);

static bool				
_DML_M_hard_reset(uart_device_t *_dev);

static bool				
_DML_M_soft_reset(uart_device_t *_dev);

static bool				
_DML_M_regs__access(uart_device_t *_dev, generic_transaction_t *memop, uint32 offset, uint32 size);

static bool				
_DML_M_regs__hard_reset(uart_device_t *_dev);

static bool				
_DML_M_regs__soft_reset(uart_device_t *_dev);

static bool				
_DML_M_regs__read_access_memop(uart_device_t *_dev, generic_transaction_t *memop, uint32 offset, uint32 size);

static bool				
_DML_M_regs__get_write_value(uart_device_t *_dev, generic_transaction_t *memop, uint64 *writeval);

static bool				
_DML_M_regs__write_access_memop(uart_device_t *_dev, generic_transaction_t *memop, uint32 offset, uint32 size, uint64 value);

static bool				
_DML_M_regs__finalize_read_access(uart_device_t *_dev, generic_transaction_t *memop, uint64 val);

static bool				
_DML_M_regs__set_read_value(uart_device_t *_dev, generic_transaction_t *memop, uint64 value);

static bool				
_DML_M_regs__ulcon__read_access(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value);

static bool				
_DML_M_regs__ulcon__write_access(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value);

static bool				
_DML_M_regs__ulcon__hard_reset_register(uart_device_t *_dev);

static bool				
_DML_M_regs__ulcon__soft_reset_register(uart_device_t *_dev);

static bool				
_DML_M_regs__ulcon__read_access_main(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value);

static bool				
_DML_M_regs__ulcon__write_access_main(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value);

static bool				
_DML_M_regs__ulcon__hard_reset(uart_device_t *_dev);

static bool				
_DML_M_regs__ulcon__read(uart_device_t *_dev, uint32 *value);

static bool				
_DML_M_regs__ulcon__get(uart_device_t *_dev, uint32 *value);

static bool				
_DML_M_regs__ulcon__write(uart_device_t *_dev, uint32 value);

static bool				
_DML_M_regs__ucon__read_access(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value);

static bool				
_DML_M_regs__ucon__write_access(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value);

static bool				
_DML_M_regs__ucon__hard_reset_register(uart_device_t *_dev);

static bool				
_DML_M_regs__ucon__soft_reset_register(uart_device_t *_dev);

static bool				
_DML_M_regs__ucon__read_access_main(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value);

static bool				
_DML_M_regs__ucon__write_access_main(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value);

static bool				
_DML_M_regs__ucon__hard_reset(uart_device_t *_dev);

static bool				
_DML_M_regs__ucon__read(uart_device_t *_dev, uint32 *value);

static bool				
_DML_M_regs__ucon__get(uart_device_t *_dev, uint32 *value);

static bool				
_DML_M_regs__ucon__write(uart_device_t *_dev, uint32 value);

static bool				
_DML_M_regs__ufcon__read_access(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value);

static bool				
_DML_M_regs__ufcon__write_access(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value);

static bool				
_DML_M_regs__ufcon__hard_reset_register(uart_device_t *_dev);

static bool				
_DML_M_regs__ufcon__soft_reset_register(uart_device_t *_dev);

static bool				
_DML_M_regs__ufcon__read_access_main(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value);

static bool				
_DML_M_regs__ufcon__write_access_main(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value);

static bool				
_DML_M_regs__ufcon__hard_reset(uart_device_t *_dev);

static bool				
_DML_M_regs__ufcon__read(uart_device_t *_dev, uint32 *value);

static bool				
_DML_M_regs__ufcon__get(uart_device_t *_dev, uint32 *value);

static bool				
_DML_M_regs__ufcon__write(uart_device_t *_dev, uint32 value);

static bool				
_DML_M_regs__umcon__read_access(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value);

static bool				
_DML_M_regs__umcon__write_access(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value);

static bool				
_DML_M_regs__umcon__hard_reset_register(uart_device_t *_dev);

static bool				
_DML_M_regs__umcon__soft_reset_register(uart_device_t *_dev);

static bool				
_DML_M_regs__umcon__read_access_main(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value);

static bool				
_DML_M_regs__umcon__write_access_main(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value);

static bool				
_DML_M_regs__umcon__hard_reset(uart_device_t *_dev);

static bool				
_DML_M_regs__umcon__read(uart_device_t *_dev, uint32 *value);

static bool				
_DML_M_regs__umcon__get(uart_device_t *_dev, uint32 *value);

static bool				
_DML_M_regs__umcon__write(uart_device_t *_dev, uint32 value);

static bool				
_DML_M_regs__utrstat__read_access(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value);

static bool				
_DML_M_regs__utrstat__write_access(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value);

static bool				
_DML_M_regs__utrstat__hard_reset_register(uart_device_t *_dev);

static bool				
_DML_M_regs__utrstat__soft_reset_register(uart_device_t *_dev);

static bool				
_DML_M_regs__utrstat__read_access_main(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value);

static bool				
_DML_M_regs__utrstat__write_access_main(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value);

static bool				
_DML_M_regs__utrstat__hard_reset(uart_device_t *_dev);

static bool				
_DML_M_regs__utrstat__read(uart_device_t *_dev, uint32 *value);

static bool				
_DML_M_regs__utrstat__get(uart_device_t *_dev, uint32 *value);

static bool				
_DML_M_regs__utrstat__write(uart_device_t *_dev, uint32 value);

static bool				
_DML_M_regs__uerstat__read_access(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value);

static bool				
_DML_M_regs__uerstat__write_access(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value);

static bool				
_DML_M_regs__uerstat__hard_reset_register(uart_device_t *_dev);

static bool				
_DML_M_regs__uerstat__soft_reset_register(uart_device_t *_dev);

static bool				
_DML_M_regs__uerstat__read_access_main(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value);

static bool				
_DML_M_regs__uerstat__write_access_main(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value);

static bool				
_DML_M_regs__uerstat__hard_reset(uart_device_t *_dev);

static bool				
_DML_M_regs__uerstat__read(uart_device_t *_dev, uint32 *value);

static bool				
_DML_M_regs__uerstat__get(uart_device_t *_dev, uint32 *value);

static bool				
_DML_M_regs__uerstat__write(uart_device_t *_dev, uint32 value);

static bool				
_DML_M_regs__ufstat__read_access(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value);

static bool				
_DML_M_regs__ufstat__write_access(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value);

static bool				
_DML_M_regs__ufstat__hard_reset_register(uart_device_t *_dev);

static bool				
_DML_M_regs__ufstat__soft_reset_register(uart_device_t *_dev);

static bool				
_DML_M_regs__ufstat__read_access_main(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value);

static bool				
_DML_M_regs__ufstat__write_access_main(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value);

static bool				
_DML_M_regs__ufstat__hard_reset(uart_device_t *_dev);

static bool				
_DML_M_regs__ufstat__read(uart_device_t *_dev, uint32 *value);

static bool				
_DML_M_regs__ufstat__get(uart_device_t *_dev, uint32 *value);

static bool				
_DML_M_regs__ufstat__write(uart_device_t *_dev, uint32 value);

static bool				
_DML_M_regs__umstat__read_access(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value);

static bool				
_DML_M_regs__umstat__write_access(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value);

static bool				
_DML_M_regs__umstat__hard_reset_register(uart_device_t *_dev);

static bool				
_DML_M_regs__umstat__soft_reset_register(uart_device_t *_dev);

static bool				
_DML_M_regs__umstat__read_access_main(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value);

static bool				
_DML_M_regs__umstat__write_access_main(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value);

static bool				
_DML_M_regs__umstat__hard_reset(uart_device_t *_dev);

static bool				
_DML_M_regs__umstat__read(uart_device_t *_dev, uint32 *value);

static bool				
_DML_M_regs__umstat__get(uart_device_t *_dev, uint32 *value);

static bool				
_DML_M_regs__umstat__write(uart_device_t *_dev, uint32 value);

static bool				
_DML_M_regs__utxh__read_access(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value);

static bool				
_DML_M_regs__utxh__write_access(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value);

static bool				
_DML_M_regs__utxh__hard_reset_register(uart_device_t *_dev);

static bool				
_DML_M_regs__utxh__soft_reset_register(uart_device_t *_dev);

static bool				
_DML_M_regs__utxh__read_access_main(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value);

static bool				
_DML_M_regs__utxh__after_read(uart_device_t *_dev, generic_transaction_t *memop);

static bool				
_DML_M_regs__utxh__write_access_main(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value);

static bool				
_DML_M_regs__utxh__after_write(uart_device_t *_dev, generic_transaction_t *memop);

static bool				
_DML_M_regs__utxh__hard_reset(uart_device_t *_dev);

static bool				
_DML_M_regs__utxh__read(uart_device_t *_dev, uint32 *value);

static bool				
_DML_M_regs__utxh__get(uart_device_t *_dev, uint32 *value);

static bool				
_DML_M_regs__utxh__write(uart_device_t *_dev, uint32 value);

static bool				
_DML_M_regs__urxh__read_access(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value);

static bool				
_DML_M_regs__urxh__write_access(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value);

static bool				
_DML_M_regs__urxh__hard_reset_register(uart_device_t *_dev);

static bool				
_DML_M_regs__urxh__soft_reset_register(uart_device_t *_dev);

static bool				
_DML_M_regs__urxh__read_access_main(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value);

static bool				
_DML_M_regs__urxh__after_read(uart_device_t *_dev, generic_transaction_t *memop);

static bool				
_DML_M_regs__urxh__write_access_main(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value);

static bool				
_DML_M_regs__urxh__hard_reset(uart_device_t *_dev);

static bool				
_DML_M_regs__urxh__read(uart_device_t *_dev, uint32 *value);

static bool				
_DML_M_regs__urxh__get(uart_device_t *_dev, uint32 *value);

static bool				
_DML_M_regs__urxh__write(uart_device_t *_dev, uint32 value);

static bool				
_DML_M_regs__ubrdiv__read_access(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value);

static bool				
_DML_M_regs__ubrdiv__write_access(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value);

static bool				
_DML_M_regs__ubrdiv__hard_reset_register(uart_device_t *_dev);

static bool				
_DML_M_regs__ubrdiv__soft_reset_register(uart_device_t *_dev);

static bool				
_DML_M_regs__ubrdiv__read_access_main(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value);

static bool				
_DML_M_regs__ubrdiv__write_access_main(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value);

static bool				
_DML_M_regs__ubrdiv__hard_reset(uart_device_t *_dev);

static bool				
_DML_M_regs__ubrdiv__read(uart_device_t *_dev, uint32 *value);

static bool				
_DML_M_regs__ubrdiv__get(uart_device_t *_dev, uint32 *value);

static bool				
_DML_M_regs__ubrdiv__write(uart_device_t *_dev, uint32 value);

static bool				
_DML_M_regs__ubrdivslot__read_access(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value);

static bool				
_DML_M_regs__ubrdivslot__write_access(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value);

static bool				
_DML_M_regs__ubrdivslot__hard_reset_register(uart_device_t *_dev);

static bool				
_DML_M_regs__ubrdivslot__soft_reset_register(uart_device_t *_dev);

static bool				
_DML_M_regs__ubrdivslot__read_access_main(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value);

static bool				
_DML_M_regs__ubrdivslot__write_access_main(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value);

static bool				
_DML_M_regs__ubrdivslot__hard_reset(uart_device_t *_dev);

static bool				
_DML_M_regs__ubrdivslot__read(uart_device_t *_dev, uint32 *value);

static bool				
_DML_M_regs__ubrdivslot__get(uart_device_t *_dev, uint32 *value);

static bool				
_DML_M_regs__ubrdivslot__write(uart_device_t *_dev, uint32 value);

static bool				
_DML_M_regs__uintp__read_access(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value);

static bool				
_DML_M_regs__uintp__write_access(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value);

static bool				
_DML_M_regs__uintp__hard_reset_register(uart_device_t *_dev);

static bool				
_DML_M_regs__uintp__soft_reset_register(uart_device_t *_dev);

static bool				
_DML_M_regs__uintp__read_access_main(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value);

static bool				
_DML_M_regs__uintp__write_access_main(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value);

static bool				
_DML_M_regs__uintp__hard_reset(uart_device_t *_dev);

static bool				
_DML_M_regs__uintp__read(uart_device_t *_dev, uint32 *value);

static bool				
_DML_M_regs__uintp__get(uart_device_t *_dev, uint32 *value);

static bool				
_DML_M_regs__uintp__write(uart_device_t *_dev, uint32 value);

static bool				
_DML_M_regs__uintsp__read_access(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value);

static bool				
_DML_M_regs__uintsp__write_access(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value);

static bool				
_DML_M_regs__uintsp__hard_reset_register(uart_device_t *_dev);

static bool				
_DML_M_regs__uintsp__soft_reset_register(uart_device_t *_dev);

static bool				
_DML_M_regs__uintsp__read_access_main(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value);

static bool				
_DML_M_regs__uintsp__write_access_main(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value);

static bool				
_DML_M_regs__uintsp__hard_reset(uart_device_t *_dev);

static bool				
_DML_M_regs__uintsp__read(uart_device_t *_dev, uint32 *value);

static bool				
_DML_M_regs__uintsp__get(uart_device_t *_dev, uint32 *value);

static bool				
_DML_M_regs__uintsp__write(uart_device_t *_dev, uint32 value);

static bool				
_DML_M_regs__uintm__read_access(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value);

static bool				
_DML_M_regs__uintm__write_access(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value);

static bool				
_DML_M_regs__uintm__hard_reset_register(uart_device_t *_dev);

static bool				
_DML_M_regs__uintm__soft_reset_register(uart_device_t *_dev);

static bool				
_DML_M_regs__uintm__read_access_main(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value);

static bool				
_DML_M_regs__uintm__write_access_main(uart_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value);

static bool				
_DML_M_regs__uintm__after_write(uart_device_t *_dev, generic_transaction_t *memop);

static bool				
_DML_M_regs__uintm__hard_reset(uart_device_t *_dev);

static bool				
_DML_M_regs__uintm__read(uart_device_t *_dev, uint32 *value);

static bool				
_DML_M_regs__uintm__get(uart_device_t *_dev, uint32 *value);

static bool				
_DML_M_regs__uintm__write(uart_device_t *_dev, uint32 value);
