/*
 * skyeye_object_headfile.c: 
 *
 * Copyright (C) 2013 alloc <alloc.young@gmail.com>
 * Skyeye Develop Group, for help please send mail to
 * <skyeye-developer@lists.gro.clinux.org>
 *
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 */
#include <time.h>
#include "gen_utility.h"
#include "platform.h"

void gen_systemc_struct(device_t *dev, FILE *f) {
    const char *dev_name = dev->obj.name;
    time_t timep;
    char *cap_name = to_upper(dev_name);
	int i;
	object_t *obj;

    time(&timep);
    fprintf(f, "/* Generated by dmlc, not to edit it */\n");
    fprintf(f, "/* %s */\n", asctime(localtime(&timep)));

    fprintf(f, "#ifndef LT_%s_TARGET_H\n", cap_name);
    fprintf(f, "#define LT_%s_TARGET_H\n", cap_name);
	fprintf(f, "\n");
	fprintf(f, "extern \"C\" {\n");
	fprintf(f, "#include <simics/bank_access.h>\n");
	fprintf(f, "}\n");
	fprintf(f, "#include \"tlm.h\"\n");
	fprintf(f, "#include \"systemc.h\"\n");
	fprintf(f, "#include \"tlm_utils/simple_target_soket.h\"\n");
	
	fprintf(f, "\nclass Lt_%s_target:public sc_core::sc_module{\n", dev_name);
	fprintf(f, "public:\n");
	fprintf(f, "\tLt_%s_target(sc_core::sc_module_name module_name, const char *obj_name);\n", dev_name);
	fprintf(f, "\t~Lt_%s_target();\n", dev_name);
	
	for(i = 0; i < dev->bank_count; i++) {
		obj = dev->banks[i];
		fprintf(f, "\tlm_utils::simple_target_socket<Lt_%s_target> target_%s_socket;\n", dev_name, obj->name);
	}
	fprintf(f, "\tconf_object_t *get_obj(void) {return obj;}\n");
	
	fprintf(f, "private:\n");
	fprintf(f, "\tconf_object_t *obj;\n");
	for(i = 0; i < dev->bank_count; i++) {
		obj = dev->banks[i];
		fprintf(f, "\tvoid custom_b_transport_%s(tlm::tlm_generic_payload &payload, sc_core::sc_time &delay_time);\n", obj->name);
		fprintf(f, "\tbank_access_t *m_iface_%s;\n", obj->name);
	}
    /*more here */
    fprintf(f,"};\n");
    fprintf(f, "\n#endif\n");
    free(cap_name);
}
