/*
 * skyeye_platform.c: 
 *
 * Copyright (C) 2013 alloc <alloc.young@gmail.com>
 * Skyeye Develop Group, for help please send mail to
 * <skyeye-developer@lists.gro.clinux.org>
 *
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 */
#include "platform.h"
#include "gen_utility.h"
#include <time.h>
#include "gen_method_protos.h"

extern object_t *DEV;

static void gen_my_headerfile(device_t *dev, FILE *f) {
    const char *name = dev->obj.name;
    time_t timep;

    time(&timep);
    fprintf(f, "/* \n");
    fprintf(f, " * Lt_%s_target.cpp\n", name);
    fprintf(f, " * Generated by dmlc, not to edit it\n");
    fprintf(f, " * %s",asctime(localtime(&timep)));
    fprintf(f, " */\n");
	fprintf(f, "\n");
    fprintf(f, "#include \"Lt_%s_target.h\"\n", name);
}

static void gen_constructor(device_t *dev, FILE *f) {
	const char *name = dev->obj.name;
	int i;
	object_t *obj;

	fprintf(f, "\nLt_%s_target::Lt_%s_target(sc_core::sc_module_name module_name, const char *obj_name)\n", name, name);
	fprintf(f, ":sc_module(module_name)\n");
	fprintf(f, "{\n");
	fprintf(f, "\tm_obj = pre_conf_obj(obj_name, \"%s\");\n", name);
	for(i = 0; i < dev->bank_count; i++) {
		obj = dev->banks[i];
		fprintf(f, "\ttarget_%s_socket.register_b_transport(this, &Lt_%s_target::custom_b_transport_%s);\n", name, name,obj->name);
		fprintf(f, "\tm_iface_%s = SIM_get_bank_access(m_obj, \"%s\");\n", obj->name, obj->name);
	}
	fprintf(f, "}\n");
}

static void gen_destructor(device_t *dev, FILE *f) {
	const char *name = dev->obj.name;

	fprintf(f, "\nLt_%s_target::~Lt_%s_target(){\n", name, name);
	fprintf(f, "}\n");
}

static void gen_systemc_bank_access(object_t *obj, FILE *f) {
	const char *name = obj->name;

	fprintf(f, "\nvoid Lt_%s_target::custom_b_transport_%s(tlm::tlm_generic_payload &payload, sc_core::sc_time &delay_time)\n", DEV->name, obj->name);
	fprintf(f, "{\n");
	fprintf(f, "\tphysical_address_t address = payload.get_address();\n");
	fprintf(f, "\ttlm::tlm_command comand = palyload.get_command();\n");
	fprintf(f, "\tunsigned char *data = payload.get_data_ptr();\n");
	fprintf(f, "\tshort size  = payload.get_data_lenth();\n");
	fprintf(f, "\n");
	fprintf(f, "\tsize = size/8;\n");
	fprintf(f, "\tif((tlm::TLM_READ_COMMAND) == command) {\n");
	fprintf(f, "\t\tm_iface_%s->read(m_obj, address, (void *)data, size);\n", obj->name);
	fprintf(f, "\t}\n");
	fprintf(f, "\telse if((tlm::TLM_WRITE_COMMAND == command)) {\n");
	fprintf(f, "\t\tuint64_t tmp;\n");
	fprintf(f, "\t\ttmp = (uin64_t)data;\n");
	fprintf(f, "\t\tm_iface_%s->write(m_obj, address, (void *)&tmp, size);\n", obj->name);
	fprintf(f, "\t} else {\n");
	fprintf(f, "\t}\n");
	fprintf(f, "\tpayload.set_response_status(tlm::TLM_OK_RESPONSE);\n");
	fprintf(f, "}\n");
}

static void gen_bank_access(object_t *obj, FILE *f) {
	gen_systemc_bank_access(obj, f);
}

static void gen_banks_mr(device_t *dev, FILE *f) {
    int i = 0;
    object_t *obj;
    for(i = 0; i < dev->bank_count; i++) {
        obj = dev->banks[i];
        gen_bank_access(obj, f);
    }
}

static void gen_my_device_init(device_t *dev, FILE *f) {

	gen_my_headerfile(dev, f);
	gen_constructor(dev, f);		
	gen_destructor(dev, f);
	gen_banks_mr(dev, f);
}
extern void gen_systemc_struct(device_t *dev, FILE *f);
void gen_platform_device_info(device_t *dev, const char *out) {
	char tmp[1024];
	const char *name; 
	FILE *f;

	name = dev->obj.name;
	snprintf(tmp, sizeof(tmp), "%s/Lt_%s_target.h", out, name);
	f = fopen(tmp, "w");
	if(f) {
		gen_systemc_struct(dev, f);
		fclose(f);
	}
	snprintf(tmp, sizeof(tmp), "%s/Lt_%s_target.cpp", out, name);
	f = fopen(tmp, "w");
	if(f) {
		gen_my_device_init(dev, f);
		fclose(f);
	}
}

void gen_platform_device_module(device_t *dev, const  char *out) {
}
