/*
 * skyeye_platform.c: 
 *
 * Copyright (C) 2013 alloc <alloc.young@gmail.com>
 * Skyeye Develop Group, for help please send mail to
 * <skyeye-developer@lists.gro.clinux.org>
 *
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 */
#include "platform.h"
#include "gen_utility.h"
#include <time.h>
#include "gen_method_protos.h"

extern object_t *DEV;

void gen_headerfile(device_t *dev, FILE *f) {
    const char *name = dev->obj.name;
    time_t timep;

    time(&timep);
    fprintf(f, "/* \n");
    fprintf(f, " * %s.c\n", name);
    fprintf(f, " * Generated by dmlc, not to edit it\n");
    fprintf(f, " * %s",asctime(localtime(&timep)));
    fprintf(f, " */\n");

    fprintf(f, "\n#include \"%s.h\"\n", name);
    fprintf(f, "\n#include \"%s_protos.c\"\n", name);
    fprintf(f, "\n#include \"skyeye_mm.h\"\n");
    fprintf(f, "\n#include \"skyeye_class.h\"\n", name);
    fprintf(f, "\n#include  <string.h>\n", name);
}

static void gen_bank_read_access(object_t *obj, FILE *f) {
	const char *name = obj->name;
	const char *dev_name = DEV->name;

	fprintf(f, "\nstatic exception_t\n");
	fprintf(f, "%s_read(conf_object_t *obj, generic_address_t addr, void *buf, size_t count) {\n", name);
	fprintf(f, "\t%s_t *_dev = (%s_t *)obj;\n", dev_name, dev_name);
	fprintf(f, "\tgeneric_transaction_t memop;\n");
	fprintf(f, "\tbool ret = 0;\n");
	fprintf(f, "\tUNUSED(ret);\n");
	fprintf(f, "\tuint64_t val;\n");
	fprintf(f, "\n");
	fprintf(f, "\tmemset(&memop, 0, sizeof(memop));\n");
	fprintf(f, "\tSIM_set_mem_op(&memop, !SIM_Trn_Write);\n");
	fprintf(f, "\tret = _DML_M_%s__access(_dev, &memop, (physical_address_t)addr, (physical_address_t)count);\n",  name);
	fprintf(f, "\tval = SIM_mem_op_get_value(&memop);\n");
	fprintf(f, "\tmemcpy(buf, &val, count);\n");
	fprintf(f, "\treturn No_exp;\n");
	fprintf(f, "}\n");
}

static void gen_bank_write_access(object_t *obj, FILE *f) {
	const char *name = obj->name;
	const char *dev_name = DEV->name;

	fprintf(f, "\nstatic exception_t\n");
	fprintf(f, "%s_read(conf_object_t *obj, generic_address_t addr, void *buf, size_t count) {\n", name);
	fprintf(f, "\t%s_t *_dev = (%s_t *)obj;\n", dev_name, dev_name);
	fprintf(f, "\tgeneric_transaction_t memop;\n");
	fprintf(f, "\tbool ret = 0;\n");
	fprintf(f, "\tUNUSED(ret);\n");
	fprintf(f, "\tuint64_t val = *(uint64 *)buf;\n");
	fprintf(f, "\n");
	fprintf(f, "\tmemset(&memop, 0, sizeof(memop));\n");
	fprintf(f, "\tSIM_set_mem_op(&memop, SIM_Trn_Write);\n");
	fprintf(f, "\tSIM_mem_op_set_value(&memop, val);\n");
	fprintf(f, "\tret = _DML_M_%s__access(_dev, &memop, (physical_address_t)addr, (physical_address_t)count);\n",  name);
	fprintf(f, "\treturn No_exp;\n");
	fprintf(f, "}\n");
}

static void gen_bank_access(object_t *obj, FILE *f) {
    gen_bank_read_access(obj, f);
    gen_bank_write_access(obj, f);
    add_object_method(obj, "access");
}

static void gen_banks_mr(device_t *dev, FILE *f) {
    int i = 0;
    object_t *obj;
    for(i = 0; i < dev->bank_count; i++) {
        obj = dev->banks[i];
        gen_bank_access(obj, f);
    }
}

static void gen_mmio_setup(device_t *dev, FILE *f) {
    const char *dev_name = dev->obj.name;
    int i = 0;
    object_t *obj;

    gen_banks_mr(dev, f);
    fprintf(f, "\nstatic void\n");
    fprintf(f, "%s_mmio_setup(%s_t *_dev) {\n", dev_name, dev_name);
    for(i = 0; i < dev->bank_count; i++) {
        obj = dev->banks[i];
		fprintf(f, "\t{\n");
		fprintf(f, "\t\t_dev->mr_%s.conf_obj = &_dev->obj;\n", obj->name);	
		fprintf(f, "\t\t_dev->mr_%s.read = %s_read;\n", obj->name, obj->name);
		fprintf(f, "\t\t_dev->mr_%s.write = %s_write;\n", obj->name, obj->name);
		fprintf(f, "\t\tSKY_register_interface(&_dev->mr_%s, _dev->obj.objname, MEMORY_SPACE_INTF_NAME);\n", obj->name);
		fprintf(f, "\t}\n");
    }
    fprintf(f, "}\n");
}


void gen_device_init(device_t *dev, FILE *f) {
    const char *dev_name = dev->obj.name;
    int index = get_local_index();

    add_object_method(&dev->obj, "init");
    gen_mmio_setup(dev, f);
    fprintf(f, "\nstatic conf_object_t  *%s_create(const char *name) {\n", dev_name);
    fprintf(f, "\t%s_t *_dev = skyeye_mm_zero(sizeof(*_dev));\n", dev_name);
	fprintf(f, "\tconf_object_register(&_dev->obj, name);\n");
    fprintf(f, "\tbool v%d_exec = 0;\n", index);
    fprintf(f, "\tUNUSED(v%d_exec);\n", index);
    fprintf(f, "\n\t%s_hard_reset(_dev);\n", dev_name);
    fprintf(f, "\tv%d_exec = _DML_M_init(_dev);\n", index);
    fprintf(f, "\t%s_mmio_setup(_dev);\n", dev_name);
    fprintf(f, "\treturn 0;\n");
    fprintf(f, "}\n");
}

void gen_device_type_info(device_t *dev, FILE *f) {
	const char *name = dev->obj.name;
	
	fprintf(f, "\nvoid init_%s(void) {\n", name);
	fprintf(f, "\tstatic skyeye_class_t class_data = {\n");
	fprintf(f, "\t\t.class_name = \"%s\",\n", name);	
	fprintf(f, "\t\t.class_desc = \"%s\",\n", name);	
	fprintf(f, "\t\t.new_instance = %s_create,\n", name);
	fprintf(f, "\t\t.free_instance = NULL,\n");
	fprintf(f, "\t\t.set_attr = NULL,\n");
	fprintf(f, "\t\t.get_attr = NULL,\n");
	fprintf(f, "\t};\n");
	fprintf(f, "\tSKY_register_class(&class_data.class_name, &class_data);\n");
	fprintf(f, "}\n");
}

