#!/bin/bash

./bin/workspace remove ADM706
./bin/workspace remove aintc
./bin/workspace remove arm_i2c
./bin/workspace remove arm-mac
./bin/workspace remove bcm5241
./bin/workspace remove bcm5389
./bin/workspace remove bcm5461
./bin/workspace remove bcm56334
./bin/workspace remove BCM5646
./bin/workspace remove BCM56820
./bin/workspace remove CDCM7005
./bin/workspace remove cfcard
./bin/workspace remove cy22393
./bin/workspace remove DEC21140A-dml
./bin/workspace remove eeprom
./bin/workspace remove flash-hook
./bin/workspace remove gptimer
./bin/workspace remove hac_sem
./bin/workspace remove hbbu-sfp
./bin/workspace remove hidsp-icu
./bin/workspace remove hidsp-timer
./bin/workspace remove HiSEMV230
./bin/workspace remove ISP1160
./bin/workspace remove lm75
./bin/workspace remove lm80
./bin/workspace remove mpc8260_adm706
./bin/workspace remove mpc8323-qe-cpri-mac
./bin/workspace remove mpc8323-qe-hdlc
./bin/workspace remove mpc8323-qe-mux-hook
./bin/workspace remove mpc8323-qe-tdm
./bin/workspace remove MPC8323-QE-TIMER
./bin/workspace remove mpc8323-qe-ucc-hook
./bin/workspace remove mpc8541-cpm-cp
./bin/workspace remove mpc8541-cpm-fcc
./bin/workspace remove mpc8541-cpm-mux
./bin/workspace remove mpc8541-cpm-pic
./bin/workspace remove my_dma
./bin/workspace remove pef22554
./bin/workspace remove pi7c9x110
./bin/workspace remove pm7340
./bin/workspace remove PM8363
./bin/workspace remove sd6181-soc-vic
./bin/workspace remove sd6182-gic
./bin/workspace remove sd6182-gmac
./bin/workspace remove sd6182-gmsgm
./bin/workspace remove sd6182-gpio
./bin/workspace remove sd6182-mss
./bin/workspace remove sd6182-sem
./bin/workspace remove sd6182-timer
./bin/workspace remove sd6182-uart
./bin/workspace remove sdram_spd
./bin/workspace remove SRRU-DSP-CACHE
./bin/workspace remove SRRU_DSP_IDMA
./bin/workspace remove SRRU_DSP_INTC
./bin/workspace remove SRRU-DSP-TIMER
./bin/workspace remove SRRU-EMIF
./bin/workspace remove SRRU_GPIO
./bin/workspace remove SRRU-SPI-CONTROLLER
./bin/workspace remove SRRU_SYS_CTL
./bin/workspace remove st16c2552
./bin/workspace remove sta101
./bin/workspace remove STW81102
./bin/workspace remove tci6482-edma3
./bin/workspace remove tci6482-emac
./bin/workspace remove tci6482-i2c
./bin/workspace remove tci6482-intc
./bin/workspace remove tci6482-loader
./bin/workspace remove tci6482-megamodule
./bin/workspace remove tci6482-pllctl
./bin/workspace remove tci6482-tcp2
./bin/workspace remove tci6482-timer
./bin/workspace remove tci6482-vcp2
./bin/workspace remove ti-semaphore
./bin/workspace remove TLV5638
./bin/workspace remove wbbi_arm1136_dummy
./bin/workspace remove wbbi_arm1136_emif
./bin/workspace remove wbbi_arm1136_gpio
./bin/workspace remove wbbi_arm1136_intc
./bin/workspace remove wbbi-arm1136-reset
./bin/workspace remove wbbi_arm1136_sysctl
./bin/workspace remove wbbi_arm1136_timer
./bin/workspace remove wbbi_c64xplus_dummy
./bin/workspace remove wbbi_c64xplus_emac
./bin/workspace remove wbbi_c64xplus_megamodule
./bin/workspace remove wbbi_c64xplus_pllctl
./bin/workspace remove wbbi_dsp_intc
./bin/workspace remove wbbi-dsp-tcp2
./bin/workspace remove wbbi-dsp-timer
./bin/workspace remove wbbi-dsp-vcp2
./bin/workspace remove wbbi-gpio-timer
./bin/workspace remove wbbi_ucc_hook
./bin/workspace remove xsi-csr
./bin/workspace remove xsi-emac
./bin/workspace remove xsi-gmac
./bin/workspace remove xsi-gpio
./bin/workspace remove xsi-intr
./bin/workspace remove xsi-npe
./bin/workspace remove xsi-pci
./bin/workspace remove xsi-timer
./bin/workspace remove ADM706
./bin/workspace remove aintc
./bin/workspace remove arm_i2c
./bin/workspace remove arm-mac
./bin/workspace remove bcm5241
./bin/workspace remove bcm5389
./bin/workspace remove bcm5461
#./bin/workspace remove bcm56334
./bin/workspace remove BCM5646
#./bin/workspace remove BCM56820
./bin/workspace remove CDCM7005
./bin/workspace remove cfcard
./bin/workspace remove cy22393
./bin/workspace remove DEC21140A-dml
./bin/workspace remove eeprom
./bin/workspace remove flash-hook
./bin/workspace remove gptimer
./bin/workspace remove hac_sem
./bin/workspace remove hbbu-sfp
./bin/workspace remove hidsp-icu
./bin/workspace remove hidsp-timer
./bin/workspace remove HiSEMV230
./bin/workspace remove ISP1160
./bin/workspace remove lm75
./bin/workspace remove lm80
./bin/workspace remove mpc8260_adm706
./bin/workspace remove mpc8323-qe-cpri-mac
./bin/workspace remove mpc8323-qe-hdlc
./bin/workspace remove mpc8323-qe-mux-hook
./bin/workspace remove mpc8323-qe-tdm
./bin/workspace remove MPC8323-QE-TIMER
./bin/workspace remove mpc8323-qe-ucc-hook
./bin/workspace remove mpc8541-cpm-cp
./bin/workspace remove mpc8541-cpm-fcc
./bin/workspace remove mpc8541-cpm-mux
./bin/workspace remove mpc8541-cpm-pic
./bin/workspace remove my_dma
./bin/workspace remove pef22554
./bin/workspace remove pi7c9x110
./bin/workspace remove pm7340
./bin/workspace remove PM8363
./bin/workspace remove sd6181-soc-vic
./bin/workspace remove sd6182-gic
./bin/workspace remove sd6182-gmac
./bin/workspace remove sd6182-gmsgm
./bin/workspace remove sd6182-gpio
./bin/workspace remove sd6182-mss
./bin/workspace remove sd6182-sem
./bin/workspace remove sd6182-timer
./bin/workspace remove sd6182-uart
./bin/workspace remove sdram_spd
./bin/workspace remove SRRU-DSP-CACHE
./bin/workspace remove SRRU_DSP_IDMA
./bin/workspace remove SRRU_DSP_INTC
./bin/workspace remove SRRU-DSP-TIMER
./bin/workspace remove SRRU-EMIF
./bin/workspace remove SRRU_GPIO
./bin/workspace remove SRRU-SPI-CONTROLLER
./bin/workspace remove SRRU_SYS_CTL
./bin/workspace remove st16c2552
./bin/workspace remove sta101
./bin/workspace remove STW81102
./bin/workspace remove tci6482-edma3
./bin/workspace remove tci6482-emac
./bin/workspace remove tci6482-i2c
./bin/workspace remove tci6482-intc
./bin/workspace remove tci6482-loader
./bin/workspace remove tci6482-megamodule
./bin/workspace remove tci6482-pllctl
./bin/workspace remove tci6482-tcp2
./bin/workspace remove tci6482-timer
./bin/workspace remove tci6482-vcp2
./bin/workspace remove ti-semaphore
./bin/workspace remove TLV5638
./bin/workspace remove wbbi_arm1136_dummy
./bin/workspace remove wbbi_arm1136_emif
./bin/workspace remove wbbi_arm1136_gpio
./bin/workspace remove wbbi_arm1136_intc
./bin/workspace remove wbbi-arm1136-reset
./bin/workspace remove wbbi_arm1136_sysctl
./bin/workspace remove wbbi_arm1136_timer
./bin/workspace remove wbbi_c64xplus_dummy
./bin/workspace remove wbbi_c64xplus_emac
./bin/workspace remove wbbi_c64xplus_megamodule
./bin/workspace remove wbbi_c64xplus_pllctl
./bin/workspace remove wbbi_dsp_intc
./bin/workspace remove wbbi-dsp-tcp2
./bin/workspace remove wbbi-dsp-timer
./bin/workspace remove wbbi-dsp-vcp2
./bin/workspace remove wbbi-gpio-timer
./bin/workspace remove wbbi_ucc_hook
./bin/workspace remove xsi-csr
./bin/workspace remove xsi-emac
./bin/workspace remove xsi-gmac
./bin/workspace remove xsi-gpio
./bin/workspace remove xsi-intr
./bin/workspace remove xsi-npe
./bin/workspace remove xsi-pci
./bin/workspace remove xsi-timer

