/* Generated by dmlc, don't edit it
 * dml object method prototypes
 * Fri Oct 18 17:48:45 2013
 */

static bool				
_DML_M_vic_update_irq(vic_device_t *_dev);

static bool				
_DML_M_init(vic_device_t *_dev);

static bool				
_DML_M_hard_reset(vic_device_t *_dev);

static bool				
_DML_M_soft_reset(vic_device_t *_dev);

static bool				
_DML_M_regs__access(vic_device_t *_dev, generic_transaction_t *memop, uint32 offset, uint32 size);

static bool				
_DML_M_regs__hard_reset(vic_device_t *_dev);

static bool				
_DML_M_regs__soft_reset(vic_device_t *_dev);

static bool				
_DML_M_regs__read_access_memop(vic_device_t *_dev, generic_transaction_t *memop, uint32 offset, uint32 size);

static bool				
_DML_M_regs__get_write_value(vic_device_t *_dev, generic_transaction_t *memop, uint64 *writeval);

static bool				
_DML_M_regs__write_access_memop(vic_device_t *_dev, generic_transaction_t *memop, uint32 offset, uint32 size, uint64 value);

static bool				
_DML_M_regs__finalize_read_access(vic_device_t *_dev, generic_transaction_t *memop, uint64 val);

static bool				
_DML_M_regs__set_read_value(vic_device_t *_dev, generic_transaction_t *memop, uint64 value);

static bool				
_DML_M_regs__irqstatus__read_access(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value);

static bool				
_DML_M_regs__irqstatus__write_access(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value);

static bool				
_DML_M_regs__irqstatus__hard_reset_register(vic_device_t *_dev);

static bool				
_DML_M_regs__irqstatus__soft_reset_register(vic_device_t *_dev);

static bool				
_DML_M_regs__irqstatus__read_access_main(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value);

static bool				
_DML_M_regs__irqstatus__after_read(vic_device_t *_dev, generic_transaction_t *mop);

static bool				
_DML_M_regs__irqstatus__write_access_main(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value);

static bool				
_DML_M_regs__irqstatus__hard_reset(vic_device_t *_dev);

static bool				
_DML_M_regs__irqstatus__read(vic_device_t *_dev, uint32 *value);

static bool				
_DML_M_regs__irqstatus__get(vic_device_t *_dev, uint32 *value);

static bool				
_DML_M_regs__fiqstatus__read_access(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value);

static bool				
_DML_M_regs__fiqstatus__write_access(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value);

static bool				
_DML_M_regs__fiqstatus__hard_reset_register(vic_device_t *_dev);

static bool				
_DML_M_regs__fiqstatus__soft_reset_register(vic_device_t *_dev);

static bool				
_DML_M_regs__fiqstatus__read_access_main(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value);

static bool				
_DML_M_regs__fiqstatus__after_read(vic_device_t *_dev, generic_transaction_t *mop);

static bool				
_DML_M_regs__fiqstatus__write_access_main(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value);

static bool				
_DML_M_regs__fiqstatus__hard_reset(vic_device_t *_dev);

static bool				
_DML_M_regs__fiqstatus__read(vic_device_t *_dev, uint32 *value);

static bool				
_DML_M_regs__fiqstatus__get(vic_device_t *_dev, uint32 *value);

static bool				
_DML_M_regs__rawintr__read_access(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value);

static bool				
_DML_M_regs__rawintr__write_access(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value);

static bool				
_DML_M_regs__rawintr__hard_reset_register(vic_device_t *_dev);

static bool				
_DML_M_regs__rawintr__soft_reset_register(vic_device_t *_dev);

static bool				
_DML_M_regs__rawintr__read_access_main(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value);

static bool				
_DML_M_regs__rawintr__after_read(vic_device_t *_dev, generic_transaction_t *mop);

static bool				
_DML_M_regs__rawintr__write_access_main(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value);

static bool				
_DML_M_regs__rawintr__hard_reset(vic_device_t *_dev);

static bool				
_DML_M_regs__rawintr__read(vic_device_t *_dev, uint32 *value);

static bool				
_DML_M_regs__rawintr__get(vic_device_t *_dev, uint32 *value);

static bool				
_DML_M_regs__intselect__read_access(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value);

static bool				
_DML_M_regs__intselect__write_access(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value);

static bool				
_DML_M_regs__intselect__hard_reset_register(vic_device_t *_dev);

static bool				
_DML_M_regs__intselect__soft_reset_register(vic_device_t *_dev);

static bool				
_DML_M_regs__intselect__read_access_main(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value);

static bool				
_DML_M_regs__intselect__write_access_main(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value);

static bool				
_DML_M_regs__intselect__hard_reset(vic_device_t *_dev);

static bool				
_DML_M_regs__intselect__read(vic_device_t *_dev, uint32 *value);

static bool				
_DML_M_regs__intselect__get(vic_device_t *_dev, uint32 *value);

static bool				
_DML_M_regs__intselect__write(vic_device_t *_dev, uint32 value);

static bool				
_DML_M_regs__intenable__read_access(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value);

static bool				
_DML_M_regs__intenable__write_access(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value);

static bool				
_DML_M_regs__intenable__hard_reset_register(vic_device_t *_dev);

static bool				
_DML_M_regs__intenable__soft_reset_register(vic_device_t *_dev);

static bool				
_DML_M_regs__intenable__read_access_main(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value);

static bool				
_DML_M_regs__intenable__write_access_main(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value);

static bool				
_DML_M_regs__intenable__hard_reset(vic_device_t *_dev);

static bool				
_DML_M_regs__intenable__read(vic_device_t *_dev, uint32 *value);

static bool				
_DML_M_regs__intenable__get(vic_device_t *_dev, uint32 *value);

static bool				
_DML_M_regs__intenable__write(vic_device_t *_dev, uint32 value);

static bool				
_DML_M_regs__intenclear__read_access(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value);

static bool				
_DML_M_regs__intenclear__write_access(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value);

static bool				
_DML_M_regs__intenclear__hard_reset_register(vic_device_t *_dev);

static bool				
_DML_M_regs__intenclear__soft_reset_register(vic_device_t *_dev);

static bool				
_DML_M_regs__intenclear__read_access_main(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value);

static bool				
_DML_M_regs__intenclear__write_access_main(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value);

static bool				
_DML_M_regs__intenclear__hard_reset(vic_device_t *_dev);

static bool				
_DML_M_regs__intenclear__read(vic_device_t *_dev, uint32 *value);

static bool				
_DML_M_regs__intenclear__get(vic_device_t *_dev, uint32 *value);

static bool				
_DML_M_regs__intenclear__write(vic_device_t *_dev, uint32 value);

static bool				
_DML_M_regs__softint__read_access(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value);

static bool				
_DML_M_regs__softint__write_access(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value);

static bool				
_DML_M_regs__softint__hard_reset_register(vic_device_t *_dev);

static bool				
_DML_M_regs__softint__soft_reset_register(vic_device_t *_dev);

static bool				
_DML_M_regs__softint__read_access_main(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value);

static bool				
_DML_M_regs__softint__write_access_main(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value);

static bool				
_DML_M_regs__softint__hard_reset(vic_device_t *_dev);

static bool				
_DML_M_regs__softint__read(vic_device_t *_dev, uint32 *value);

static bool				
_DML_M_regs__softint__get(vic_device_t *_dev, uint32 *value);

static bool				
_DML_M_regs__softint__write(vic_device_t *_dev, uint32 value);

static bool				
_DML_M_regs__softintclear__read_access(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value);

static bool				
_DML_M_regs__softintclear__write_access(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value);

static bool				
_DML_M_regs__softintclear__hard_reset_register(vic_device_t *_dev);

static bool				
_DML_M_regs__softintclear__soft_reset_register(vic_device_t *_dev);

static bool				
_DML_M_regs__softintclear__read_access_main(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value);

static bool				
_DML_M_regs__softintclear__write_access_main(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value);

static bool				
_DML_M_regs__softintclear__hard_reset(vic_device_t *_dev);

static bool				
_DML_M_regs__softintclear__read(vic_device_t *_dev, uint32 *value);

static bool				
_DML_M_regs__softintclear__get(vic_device_t *_dev, uint32 *value);

static bool				
_DML_M_regs__softintclear__write(vic_device_t *_dev, uint32 value);

static bool				
_DML_M_regs__protection__read_access(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value);

static bool				
_DML_M_regs__protection__write_access(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value);

static bool				
_DML_M_regs__protection__hard_reset_register(vic_device_t *_dev);

static bool				
_DML_M_regs__protection__soft_reset_register(vic_device_t *_dev);

static bool				
_DML_M_regs__protection__read_access_main(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value);

static bool				
_DML_M_regs__protection__write_access_main(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value);

static bool				
_DML_M_regs__protection__hard_reset(vic_device_t *_dev);

static bool				
_DML_M_regs__protection__read(vic_device_t *_dev, uint32 *value);

static bool				
_DML_M_regs__protection__get(vic_device_t *_dev, uint32 *value);

static bool				
_DML_M_regs__protection__write(vic_device_t *_dev, uint32 value);

static bool				
_DML_M_regs__swproritymask__read_access(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value);

static bool				
_DML_M_regs__swproritymask__write_access(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value);

static bool				
_DML_M_regs__swproritymask__hard_reset_register(vic_device_t *_dev);

static bool				
_DML_M_regs__swproritymask__soft_reset_register(vic_device_t *_dev);

static bool				
_DML_M_regs__swproritymask__read_access_main(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value);

static bool				
_DML_M_regs__swproritymask__write_access_main(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value);

static bool				
_DML_M_regs__swproritymask__hard_reset(vic_device_t *_dev);

static bool				
_DML_M_regs__swproritymask__read(vic_device_t *_dev, uint32 *value);

static bool				
_DML_M_regs__swproritymask__get(vic_device_t *_dev, uint32 *value);

static bool				
_DML_M_regs__swproritymask__write(vic_device_t *_dev, uint32 value);

static bool				
_DML_M_regs__proritydaisy__read_access(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value);

static bool				
_DML_M_regs__proritydaisy__write_access(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value);

static bool				
_DML_M_regs__proritydaisy__hard_reset_register(vic_device_t *_dev);

static bool				
_DML_M_regs__proritydaisy__soft_reset_register(vic_device_t *_dev);

static bool				
_DML_M_regs__proritydaisy__read_access_main(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value);

static bool				
_DML_M_regs__proritydaisy__write_access_main(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value);

static bool				
_DML_M_regs__proritydaisy__hard_reset(vic_device_t *_dev);

static bool				
_DML_M_regs__proritydaisy__read(vic_device_t *_dev, uint32 *value);

static bool				
_DML_M_regs__proritydaisy__get(vic_device_t *_dev, uint32 *value);

static bool				
_DML_M_regs__proritydaisy__write(vic_device_t *_dev, uint32 value);

static bool				
_DML_M_regs__vectaddr__read_access(vic_device_t *_dev, int _idx0, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value);

static bool				
_DML_M_regs__vectaddr__write_access(vic_device_t *_dev, int _idx0, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value);

static bool				
_DML_M_regs__vectaddr__hard_reset_register(vic_device_t *_dev, int _idx0);

static bool				
_DML_M_regs__vectaddr__soft_reset_register(vic_device_t *_dev, int _idx0);

static bool				
_DML_M_regs__vectaddr__read_access_main(vic_device_t *_dev, int _idx0, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value);

static bool				
_DML_M_regs__vectaddr__write_access_main(vic_device_t *_dev, int _idx0, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value);

static bool				
_DML_M_regs__vectaddr__hard_reset(vic_device_t *_dev, int _idx0);

static bool				
_DML_M_regs__vectaddr__read(vic_device_t *_dev, int _idx0, uint32 *value);

static bool				
_DML_M_regs__vectaddr__get(vic_device_t *_dev, int _idx0, uint32 *value);

static bool				
_DML_M_regs__vectaddr__write(vic_device_t *_dev, int _idx0, uint32 value);

static bool				
_DML_M_regs__vectprority__read_access(vic_device_t *_dev, int _idx0, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value);

static bool				
_DML_M_regs__vectprority__write_access(vic_device_t *_dev, int _idx0, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value);

static bool				
_DML_M_regs__vectprority__hard_reset_register(vic_device_t *_dev, int _idx0);

static bool				
_DML_M_regs__vectprority__soft_reset_register(vic_device_t *_dev, int _idx0);

static bool				
_DML_M_regs__vectprority__read_access_main(vic_device_t *_dev, int _idx0, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value);

static bool				
_DML_M_regs__vectprority__write_access_main(vic_device_t *_dev, int _idx0, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value);

static bool				
_DML_M_regs__vectprority__hard_reset(vic_device_t *_dev, int _idx0);

static bool				
_DML_M_regs__vectprority__read(vic_device_t *_dev, int _idx0, uint32 *value);

static bool				
_DML_M_regs__vectprority__get(vic_device_t *_dev, int _idx0, uint32 *value);

static bool				
_DML_M_regs__vectprority__write(vic_device_t *_dev, int _idx0, uint32 value);

static bool				
_DML_M_regs__periphid0__read_access(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value);

static bool				
_DML_M_regs__periphid0__write_access(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value);

static bool				
_DML_M_regs__periphid0__hard_reset_register(vic_device_t *_dev);

static bool				
_DML_M_regs__periphid0__soft_reset_register(vic_device_t *_dev);

static bool				
_DML_M_regs__periphid0__read_access_main(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value);

static bool				
_DML_M_regs__periphid0__write_access_main(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value);

static bool				
_DML_M_regs__periphid0__hard_reset(vic_device_t *_dev);

static bool				
_DML_M_regs__periphid0__read(vic_device_t *_dev, uint32 *value);

static bool				
_DML_M_regs__periphid0__get(vic_device_t *_dev, uint32 *value);

static bool				
_DML_M_regs__periphid1__read_access(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value);

static bool				
_DML_M_regs__periphid1__write_access(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value);

static bool				
_DML_M_regs__periphid1__hard_reset_register(vic_device_t *_dev);

static bool				
_DML_M_regs__periphid1__soft_reset_register(vic_device_t *_dev);

static bool				
_DML_M_regs__periphid1__read_access_main(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value);

static bool				
_DML_M_regs__periphid1__write_access_main(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value);

static bool				
_DML_M_regs__periphid1__hard_reset(vic_device_t *_dev);

static bool				
_DML_M_regs__periphid1__read(vic_device_t *_dev, uint32 *value);

static bool				
_DML_M_regs__periphid1__get(vic_device_t *_dev, uint32 *value);

static bool				
_DML_M_regs__periphid2__read_access(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value);

static bool				
_DML_M_regs__periphid2__write_access(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value);

static bool				
_DML_M_regs__periphid2__hard_reset_register(vic_device_t *_dev);

static bool				
_DML_M_regs__periphid2__soft_reset_register(vic_device_t *_dev);

static bool				
_DML_M_regs__periphid2__read_access_main(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value);

static bool				
_DML_M_regs__periphid2__write_access_main(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value);

static bool				
_DML_M_regs__periphid2__hard_reset(vic_device_t *_dev);

static bool				
_DML_M_regs__periphid2__read(vic_device_t *_dev, uint32 *value);

static bool				
_DML_M_regs__periphid2__get(vic_device_t *_dev, uint32 *value);

static bool				
_DML_M_regs__periphid3__read_access(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value);

static bool				
_DML_M_regs__periphid3__write_access(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value);

static bool				
_DML_M_regs__periphid3__hard_reset_register(vic_device_t *_dev);

static bool				
_DML_M_regs__periphid3__soft_reset_register(vic_device_t *_dev);

static bool				
_DML_M_regs__periphid3__read_access_main(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value);

static bool				
_DML_M_regs__periphid3__write_access_main(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value);

static bool				
_DML_M_regs__periphid3__hard_reset(vic_device_t *_dev);

static bool				
_DML_M_regs__periphid3__read(vic_device_t *_dev, uint32 *value);

static bool				
_DML_M_regs__periphid3__get(vic_device_t *_dev, uint32 *value);

static bool				
_DML_M_regs__periphid3__write(vic_device_t *_dev, uint32 value);

static bool				
_DML_M_int_update__int_update(vic_device_t *_dev);

static bool				
_DML_M_simple_interrupt__interrupt(vic_device_t *_dev, int num);

static bool				
_DML_M_simple_interrupt__interrupt_clear(vic_device_t *_dev, int num);

static void
_DML_IFACE_int_update__int_update(conf_object_t *obj);

static void
_DML_IFACE_simple_interrupt__interrupt(conf_object_t *obj, int num);

static void
_DML_IFACE_simple_interrupt__interrupt_clear(conf_object_t *obj, int num);
