/* Generated by dmlc, not to edit it */
/* Fri Oct 18 17:48:44 2013
 */
#ifndef VIC_DEVICE_STRUCT_H
#define VIC_DEVICE_STRUCT_H

typedef struct vic_device vic_device_t;

#define REGS_MR_SIZE 0xff0

struct vic_device {
	conf_object_t obj;
	struct {
		uint32 irqstatus;
		uint32 fiqstatus;
		uint32 rawintr;
		uint32 intselect;
		uint32 intenable;
		uint32 intenclear;
		uint32 softint;
		uint32 softintclear;
		uint32 protection;
		uint32 swproritymask;
		uint32 proritydaisy;
		uint32 vectaddr[32];
		uint32 vectprority[32];
		uint32 periphid0;
		uint32 periphid1;
		uint32 periphid2;
		uint32 periphid3;
	} regs;
	struct {
		const char *port;
		conf_object_t *obj;
		const simple_interrupt_interface_t *simple_interrupt;
	} irq;
};

#endif
