/* 
 * vic_device.c
 * Generated by dmlc, not to edit it
 * Fri Oct 18 17:48:44 2013
 */

#include  <string.h>
#include "vic_device.h"
#include "vic_device_protos.c"

static exception_type_t
regs_read(conf_object_t *obj, physical_address_t addr, void *buf, size_t count) {
	vic_device_t *_dev = (vic_device_t *)obj;
	generic_transaction_t memop;
	bool ret = 0;
	UNUSED(ret);
	uint64_t val;

	memset(&memop, 0, sizeof(memop));
	SIM_set_mem_op(&memop, !SIM_Trn_Write);
	ret = _DML_M_regs__access(_dev, &memop, (physical_address_t)addr, (physical_address_t)count);
	val = SIM_mem_op_get_value(&memop);
	memcpy(buf, &val, count);
	return No_exp;
}

static exception_type_t
regs_write(conf_object_t *obj, physical_address_t addr, const void *buf, size_t count) {
	vic_device_t *_dev = (vic_device_t *)obj;
	generic_transaction_t memop;
	bool ret = 0;
	UNUSED(ret);
	uint64_t val = *(uint64 *)buf;

	memset(&memop, 0, sizeof(memop));
	SIM_set_mem_op(&memop, SIM_Trn_Write);
	SIM_mem_op_set_value(&memop, val);
	ret = _DML_M_regs__access(_dev, &memop, (physical_address_t)addr, (physical_address_t)count);
	return No_exp;
}

/*
static void
vic_device_mmio_setup(vic_device_t *_dev, const char *objname) {
	{
		_dev->mr_regs.conf_obj = &_dev->obj;
		_dev->mr_regs.read = regs_read;
		_dev->mr_regs.write = regs_write;
		SKY_register_interface(&_dev->mr_regs, objname, MEMORY_SPACE_INTF_NAME);
	}
}
*/

static conf_object_t  *vic_device_create(const char *name) {
	vic_device_t *_dev = MM_ZALLOC(sizeof(*_dev));
	conf_object_register(&_dev->obj, name);
	bool v1_exec = 0;
	UNUSED(v1_exec);

	vic_device_hard_reset(_dev);
	v1_exec = _DML_M_init(_dev);
	return &_dev->obj;
}

void vic_device_hard_reset(vic_device_t *obj) {
	bool v2_exec;
	UNUSED(v2_exec);

	v2_exec = _DML_M_hard_reset(obj);
}

void vic_device_soft_reset(vic_device_t *obj) {
	bool v3_exec;
	UNUSED(v3_exec);

	v3_exec = _DML_M_soft_reset(obj);
}

static void
_DML_IFACE_int_update__int_update(conf_object_t *obj)
{
	vic_device_t *_dev = (vic_device_t *)obj;
	{
		bool exec;
		exec = _DML_M_int_update__int_update(_dev);
		if(exec) {
			goto throw;
		}
	}
throw: ;
}

static void
_DML_IFACE_simple_interrupt__interrupt(conf_object_t *obj, int num)
{
	vic_device_t *_dev = (vic_device_t *)obj;
	{
		bool exec;
		exec = _DML_M_simple_interrupt__interrupt(_dev, num);
		if(exec) {
			goto throw;
		}
	}
throw: ;
}

static void
_DML_IFACE_simple_interrupt__interrupt_clear(conf_object_t *obj, int num)
{
	vic_device_t *_dev = (vic_device_t *)obj;
	{
		bool exec;
		exec = _DML_M_simple_interrupt__interrupt_clear(_dev, num);
		if(exec) {
			goto throw;
		}
	}
throw: ;
}

static bool
_DML_M_regs__read_access(vic_device_t *_dev, generic_transaction_t *memop, physical_address_t offset, physical_address_t size, bool *success, uint64 *readvalue)
{
	{
		{
			bool v4_exec = 0;
			{
				{
					uint64 v5_offset = offset;
					int64 v5_size = size;
					int64 v5_size2;
					*readvalue = 0;
					switch(v5_offset / 128 )
					{
						case 2:
							{
								int _idx0;
								_idx0 = (v5_offset - 0x100) / 4;
								if(((_idx0 >= 0) && (_idx0 < 32)) && ((v5_offset - _idx0 * 4 - 0x100) == 0))
								{
									uint64 v6_ret_value;
									v5_size2 = 4;
									v4_exec = _DML_M_regs__vectaddr__read_access(_dev, _idx0, memop, 31, 0, &v6_ret_value);
									if(v4_exec){
										return 1;
									}
									*readvalue = v6_ret_value;
									goto found;
								}
								break;
							}
						case 4:
							{
								int _idx0;
								_idx0 = (v5_offset - 0x200) / 4;
								if(((_idx0 >= 0) && (_idx0 < 32)) && ((v5_offset - _idx0 * 4 - 0x200) == 0))
								{
									uint64 v7_ret_value;
									v5_size2 = 4;
									v4_exec = _DML_M_regs__vectprority__read_access(_dev, _idx0, memop, 31, 0, &v7_ret_value);
									if(v4_exec){
										return 1;
									}
									*readvalue = v7_ret_value;
									goto found;
								}
								break;
							}
					}
					switch(v5_offset / 4)
					{
						case 0:
							{
								uint8 v8_lsb;
								uint8 v8_msb;
								v5_size2 = v5_size < 4 - v5_offset ? v5_size : 4 - v5_offset;
								v8_lsb = (v5_offset - 0) * 8;
								v8_msb = v8_lsb + v5_size2 * 8;
								{
									uint64 v9_ret_value  = 0;
									{
										v4_exec = _DML_M_regs__irqstatus__read_access(_dev, memop, v8_msb, v8_lsb, &v9_ret_value);
										if(v4_exec)
											return 1;
									}
									*readvalue = v9_ret_value;
								}
								goto found;
							}
						case 1:
							{
								uint8 v10_lsb;
								uint8 v10_msb;
								v5_size2 = v5_size < 8 - v5_offset ? v5_size : 8 - v5_offset;
								v10_lsb = (v5_offset - 4) * 8;
								v10_msb = v10_lsb + v5_size2 * 8;
								{
									uint64 v11_ret_value  = 0;
									{
										v4_exec = _DML_M_regs__fiqstatus__read_access(_dev, memop, v10_msb, v10_lsb, &v11_ret_value);
										if(v4_exec)
											return 1;
									}
									*readvalue = v11_ret_value;
								}
								goto found;
							}
						case 2:
							{
								uint8 v12_lsb;
								uint8 v12_msb;
								v5_size2 = v5_size < 12 - v5_offset ? v5_size : 12 - v5_offset;
								v12_lsb = (v5_offset - 8) * 8;
								v12_msb = v12_lsb + v5_size2 * 8;
								{
									uint64 v13_ret_value  = 0;
									{
										v4_exec = _DML_M_regs__rawintr__read_access(_dev, memop, v12_msb, v12_lsb, &v13_ret_value);
										if(v4_exec)
											return 1;
									}
									*readvalue = v13_ret_value;
								}
								goto found;
							}
						case 3:
							{
								uint8 v14_lsb;
								uint8 v14_msb;
								v5_size2 = v5_size < 16 - v5_offset ? v5_size : 16 - v5_offset;
								v14_lsb = (v5_offset - 12) * 8;
								v14_msb = v14_lsb + v5_size2 * 8;
								{
									uint64 v15_ret_value  = 0;
									{
										v4_exec = _DML_M_regs__intselect__read_access(_dev, memop, v14_msb, v14_lsb, &v15_ret_value);
										if(v4_exec)
											return 1;
									}
									*readvalue = v15_ret_value;
								}
								goto found;
							}
						case 4:
							{
								uint8 v16_lsb;
								uint8 v16_msb;
								v5_size2 = v5_size < 20 - v5_offset ? v5_size : 20 - v5_offset;
								v16_lsb = (v5_offset - 16) * 8;
								v16_msb = v16_lsb + v5_size2 * 8;
								{
									uint64 v17_ret_value  = 0;
									{
										v4_exec = _DML_M_regs__intenable__read_access(_dev, memop, v16_msb, v16_lsb, &v17_ret_value);
										if(v4_exec)
											return 1;
									}
									*readvalue = v17_ret_value;
								}
								goto found;
							}
						case 5:
							{
								uint8 v18_lsb;
								uint8 v18_msb;
								v5_size2 = v5_size < 24 - v5_offset ? v5_size : 24 - v5_offset;
								v18_lsb = (v5_offset - 20) * 8;
								v18_msb = v18_lsb + v5_size2 * 8;
								{
									uint64 v19_ret_value  = 0;
									{
										v4_exec = _DML_M_regs__intenclear__read_access(_dev, memop, v18_msb, v18_lsb, &v19_ret_value);
										if(v4_exec)
											return 1;
									}
									*readvalue = v19_ret_value;
								}
								goto found;
							}
						case 6:
							{
								uint8 v20_lsb;
								uint8 v20_msb;
								v5_size2 = v5_size < 28 - v5_offset ? v5_size : 28 - v5_offset;
								v20_lsb = (v5_offset - 24) * 8;
								v20_msb = v20_lsb + v5_size2 * 8;
								{
									uint64 v21_ret_value  = 0;
									{
										v4_exec = _DML_M_regs__softint__read_access(_dev, memop, v20_msb, v20_lsb, &v21_ret_value);
										if(v4_exec)
											return 1;
									}
									*readvalue = v21_ret_value;
								}
								goto found;
							}
						case 7:
							{
								uint8 v22_lsb;
								uint8 v22_msb;
								v5_size2 = v5_size < 32 - v5_offset ? v5_size : 32 - v5_offset;
								v22_lsb = (v5_offset - 28) * 8;
								v22_msb = v22_lsb + v5_size2 * 8;
								{
									uint64 v23_ret_value  = 0;
									{
										v4_exec = _DML_M_regs__softintclear__read_access(_dev, memop, v22_msb, v22_lsb, &v23_ret_value);
										if(v4_exec)
											return 1;
									}
									*readvalue = v23_ret_value;
								}
								goto found;
							}
						case 8:
							{
								uint8 v24_lsb;
								uint8 v24_msb;
								v5_size2 = v5_size < 36 - v5_offset ? v5_size : 36 - v5_offset;
								v24_lsb = (v5_offset - 32) * 8;
								v24_msb = v24_lsb + v5_size2 * 8;
								{
									uint64 v25_ret_value  = 0;
									{
										v4_exec = _DML_M_regs__protection__read_access(_dev, memop, v24_msb, v24_lsb, &v25_ret_value);
										if(v4_exec)
											return 1;
									}
									*readvalue = v25_ret_value;
								}
								goto found;
							}
						case 9:
							{
								uint8 v26_lsb;
								uint8 v26_msb;
								v5_size2 = v5_size < 40 - v5_offset ? v5_size : 40 - v5_offset;
								v26_lsb = (v5_offset - 36) * 8;
								v26_msb = v26_lsb + v5_size2 * 8;
								{
									uint64 v27_ret_value  = 0;
									{
										v4_exec = _DML_M_regs__swproritymask__read_access(_dev, memop, v26_msb, v26_lsb, &v27_ret_value);
										if(v4_exec)
											return 1;
									}
									*readvalue = v27_ret_value;
								}
								goto found;
							}
						case 10:
							{
								uint8 v28_lsb;
								uint8 v28_msb;
								v5_size2 = v5_size < 44 - v5_offset ? v5_size : 44 - v5_offset;
								v28_lsb = (v5_offset - 40) * 8;
								v28_msb = v28_lsb + v5_size2 * 8;
								{
									uint64 v29_ret_value  = 0;
									{
										v4_exec = _DML_M_regs__proritydaisy__read_access(_dev, memop, v28_msb, v28_lsb, &v29_ret_value);
										if(v4_exec)
											return 1;
									}
									*readvalue = v29_ret_value;
								}
								goto found;
							}
						case 0x3f8:
							{
								uint8 v30_lsb;
								uint8 v30_msb;
								v5_size2 = v5_size < 4068 - v5_offset ? v5_size : 4068 - v5_offset;
								v30_lsb = (v5_offset - 4064) * 8;
								v30_msb = v30_lsb + v5_size2 * 8;
								{
									uint64 v31_ret_value  = 0;
									{
										v4_exec = _DML_M_regs__periphid0__read_access(_dev, memop, v30_msb, v30_lsb, &v31_ret_value);
										if(v4_exec)
											return 1;
									}
									*readvalue = v31_ret_value;
								}
								goto found;
							}
						case 0x3f9:
							{
								uint8 v32_lsb;
								uint8 v32_msb;
								v5_size2 = v5_size < 4072 - v5_offset ? v5_size : 4072 - v5_offset;
								v32_lsb = (v5_offset - 4068) * 8;
								v32_msb = v32_lsb + v5_size2 * 8;
								{
									uint64 v33_ret_value  = 0;
									{
										v4_exec = _DML_M_regs__periphid1__read_access(_dev, memop, v32_msb, v32_lsb, &v33_ret_value);
										if(v4_exec)
											return 1;
									}
									*readvalue = v33_ret_value;
								}
								goto found;
							}
						case 0x3fa:
							{
								uint8 v34_lsb;
								uint8 v34_msb;
								v5_size2 = v5_size < 4076 - v5_offset ? v5_size : 4076 - v5_offset;
								v34_lsb = (v5_offset - 4072) * 8;
								v34_msb = v34_lsb + v5_size2 * 8;
								{
									uint64 v35_ret_value  = 0;
									{
										v4_exec = _DML_M_regs__periphid2__read_access(_dev, memop, v34_msb, v34_lsb, &v35_ret_value);
										if(v4_exec)
											return 1;
									}
									*readvalue = v35_ret_value;
								}
								goto found;
							}
						case 0x3fb:
							{
								uint8 v36_lsb;
								uint8 v36_msb;
								v5_size2 = v5_size < 4080 - v5_offset ? v5_size : 4080 - v5_offset;
								v36_lsb = (v5_offset - 4076) * 8;
								v36_msb = v36_lsb + v5_size2 * 8;
								{
									uint64 v37_ret_value  = 0;
									{
										v4_exec = _DML_M_regs__periphid3__read_access(_dev, memop, v36_msb, v36_lsb, &v37_ret_value);
										if(v4_exec)
											return 1;
									}
									*readvalue = v37_ret_value;
								}
								goto found;
							}
					}
					*success = 0;
					goto exit1;
				found:
					*success = v5_size == v5_size2;
				}
			exit1:;
			}
		}
		return 0;
	}
}

static bool 
_DML_M_regs__write_access(vic_device_t *_dev, generic_transaction_t *memop, physical_address_t offset, physical_address_t size, uint64 writevalue, bool *success)
{
	{
		{
			bool v38_exec = 0;
			{
				{
					uint64 v39_offset = offset;
					int64 v39_size = size;
					int64 v39_size2;
					switch(v39_offset / 128 )
					{
						case 2:
							{
								int _idx0;
								_idx0 = (v39_offset - 0x100) / 4;
								if(((_idx0 >= 0) && (_idx0 < 32)) && ((v39_offset - _idx0 * 4 - 0x100) == 0))
								{
								v39_size2 = 4;
									v38_exec = _DML_M_regs__vectaddr__write_access(_dev, _idx0, memop, 31, 0, writevalue);
									if(v38_exec){
										return 1;
									}
									goto found;
								}
								break;
							}
						case 4:
							{
								int _idx0;
								_idx0 = (v39_offset - 0x200) / 4;
								if(((_idx0 >= 0) && (_idx0 < 32)) && ((v39_offset - _idx0 * 4 - 0x200) == 0))
								{
								v39_size2 = 4;
									v38_exec = _DML_M_regs__vectprority__write_access(_dev, _idx0, memop, 31, 0, writevalue);
									if(v38_exec){
										return 1;
									}
									goto found;
								}
								break;
							}
					}
					switch(v39_offset / 4 )
					{
						case 0:
							{
								uint8 v42_lsb;
								uint8 v42_msb;
								v39_size2 = v39_size < 4 - v39_offset ? v39_size : 4 - v39_offset;
								v42_lsb = (v39_offset - 0) * 8;
								v42_msb = v42_lsb + v39_size2 * 8;
								{
									v38_exec = _DML_M_regs__irqstatus__write_access(_dev, memop, v42_msb, v42_lsb, writevalue);
									if(v38_exec)
										return 1;
								}
								goto found;
							}
						case 1:
							{
								uint8 v44_lsb;
								uint8 v44_msb;
								v39_size2 = v39_size < 8 - v39_offset ? v39_size : 8 - v39_offset;
								v44_lsb = (v39_offset - 4) * 8;
								v44_msb = v44_lsb + v39_size2 * 8;
								{
									v38_exec = _DML_M_regs__fiqstatus__write_access(_dev, memop, v44_msb, v44_lsb, writevalue);
									if(v38_exec)
										return 1;
								}
								goto found;
							}
						case 2:
							{
								uint8 v46_lsb;
								uint8 v46_msb;
								v39_size2 = v39_size < 12 - v39_offset ? v39_size : 12 - v39_offset;
								v46_lsb = (v39_offset - 8) * 8;
								v46_msb = v46_lsb + v39_size2 * 8;
								{
									v38_exec = _DML_M_regs__rawintr__write_access(_dev, memop, v46_msb, v46_lsb, writevalue);
									if(v38_exec)
										return 1;
								}
								goto found;
							}
						case 3:
							{
								uint8 v48_lsb;
								uint8 v48_msb;
								v39_size2 = v39_size < 16 - v39_offset ? v39_size : 16 - v39_offset;
								v48_lsb = (v39_offset - 12) * 8;
								v48_msb = v48_lsb + v39_size2 * 8;
								{
									v38_exec = _DML_M_regs__intselect__write_access(_dev, memop, v48_msb, v48_lsb, writevalue);
									if(v38_exec)
										return 1;
								}
								goto found;
							}
						case 4:
							{
								uint8 v50_lsb;
								uint8 v50_msb;
								v39_size2 = v39_size < 20 - v39_offset ? v39_size : 20 - v39_offset;
								v50_lsb = (v39_offset - 16) * 8;
								v50_msb = v50_lsb + v39_size2 * 8;
								{
									v38_exec = _DML_M_regs__intenable__write_access(_dev, memop, v50_msb, v50_lsb, writevalue);
									if(v38_exec)
										return 1;
								}
								goto found;
							}
						case 5:
							{
								uint8 v52_lsb;
								uint8 v52_msb;
								v39_size2 = v39_size < 24 - v39_offset ? v39_size : 24 - v39_offset;
								v52_lsb = (v39_offset - 20) * 8;
								v52_msb = v52_lsb + v39_size2 * 8;
								{
									v38_exec = _DML_M_regs__intenclear__write_access(_dev, memop, v52_msb, v52_lsb, writevalue);
									if(v38_exec)
										return 1;
								}
								goto found;
							}
						case 6:
							{
								uint8 v54_lsb;
								uint8 v54_msb;
								v39_size2 = v39_size < 28 - v39_offset ? v39_size : 28 - v39_offset;
								v54_lsb = (v39_offset - 24) * 8;
								v54_msb = v54_lsb + v39_size2 * 8;
								{
									v38_exec = _DML_M_regs__softint__write_access(_dev, memop, v54_msb, v54_lsb, writevalue);
									if(v38_exec)
										return 1;
								}
								goto found;
							}
						case 7:
							{
								uint8 v56_lsb;
								uint8 v56_msb;
								v39_size2 = v39_size < 32 - v39_offset ? v39_size : 32 - v39_offset;
								v56_lsb = (v39_offset - 28) * 8;
								v56_msb = v56_lsb + v39_size2 * 8;
								{
									v38_exec = _DML_M_regs__softintclear__write_access(_dev, memop, v56_msb, v56_lsb, writevalue);
									if(v38_exec)
										return 1;
								}
								goto found;
							}
						case 8:
							{
								uint8 v58_lsb;
								uint8 v58_msb;
								v39_size2 = v39_size < 36 - v39_offset ? v39_size : 36 - v39_offset;
								v58_lsb = (v39_offset - 32) * 8;
								v58_msb = v58_lsb + v39_size2 * 8;
								{
									v38_exec = _DML_M_regs__protection__write_access(_dev, memop, v58_msb, v58_lsb, writevalue);
									if(v38_exec)
										return 1;
								}
								goto found;
							}
						case 9:
							{
								uint8 v60_lsb;
								uint8 v60_msb;
								v39_size2 = v39_size < 40 - v39_offset ? v39_size : 40 - v39_offset;
								v60_lsb = (v39_offset - 36) * 8;
								v60_msb = v60_lsb + v39_size2 * 8;
								{
									v38_exec = _DML_M_regs__swproritymask__write_access(_dev, memop, v60_msb, v60_lsb, writevalue);
									if(v38_exec)
										return 1;
								}
								goto found;
							}
						case 10:
							{
								uint8 v62_lsb;
								uint8 v62_msb;
								v39_size2 = v39_size < 44 - v39_offset ? v39_size : 44 - v39_offset;
								v62_lsb = (v39_offset - 40) * 8;
								v62_msb = v62_lsb + v39_size2 * 8;
								{
									v38_exec = _DML_M_regs__proritydaisy__write_access(_dev, memop, v62_msb, v62_lsb, writevalue);
									if(v38_exec)
										return 1;
								}
								goto found;
							}
						case 0x3f8:
							{
								uint8 v64_lsb;
								uint8 v64_msb;
								v39_size2 = v39_size < 4068 - v39_offset ? v39_size : 4068 - v39_offset;
								v64_lsb = (v39_offset - 4064) * 8;
								v64_msb = v64_lsb + v39_size2 * 8;
								{
									v38_exec = _DML_M_regs__periphid0__write_access(_dev, memop, v64_msb, v64_lsb, writevalue);
									if(v38_exec)
										return 1;
								}
								goto found;
							}
						case 0x3f9:
							{
								uint8 v66_lsb;
								uint8 v66_msb;
								v39_size2 = v39_size < 4072 - v39_offset ? v39_size : 4072 - v39_offset;
								v66_lsb = (v39_offset - 4068) * 8;
								v66_msb = v66_lsb + v39_size2 * 8;
								{
									v38_exec = _DML_M_regs__periphid1__write_access(_dev, memop, v66_msb, v66_lsb, writevalue);
									if(v38_exec)
										return 1;
								}
								goto found;
							}
						case 0x3fa:
							{
								uint8 v68_lsb;
								uint8 v68_msb;
								v39_size2 = v39_size < 4076 - v39_offset ? v39_size : 4076 - v39_offset;
								v68_lsb = (v39_offset - 4072) * 8;
								v68_msb = v68_lsb + v39_size2 * 8;
								{
									v38_exec = _DML_M_regs__periphid2__write_access(_dev, memop, v68_msb, v68_lsb, writevalue);
									if(v38_exec)
										return 1;
								}
								goto found;
							}
						case 0x3fb:
							{
								uint8 v70_lsb;
								uint8 v70_msb;
								v39_size2 = v39_size < 4080 - v39_offset ? v39_size : 4080 - v39_offset;
								v70_lsb = (v39_offset - 4076) * 8;
								v70_msb = v70_lsb + v39_size2 * 8;
								{
									v38_exec = _DML_M_regs__periphid3__write_access(_dev, memop, v70_msb, v70_lsb, writevalue);
									if(v38_exec)
										return 1;
								}
								goto found;
							}
					}
					*success = 0;
					goto exit2;
				found:
					*success = v39_size == v39_size2;
				}
			exit2:;
			}
		}
		return 0;
	}
}

static bool				
_DML_M_init(vic_device_t *_dev)
{
	{
		{
			bool v72_exec = 0;
			UNUSED(v72_exec);
			{
				{
					{
						
					} 
				} 

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_hard_reset(vic_device_t *_dev)
{
	{
		{
			bool v73_exec = 0;
			UNUSED(v73_exec);
			{
				{
					{
						v73_exec = _DML_M_regs__hard_reset(_dev);
						if(v73_exec) {
							return 1;
						} 
					} 
				} 

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_soft_reset(vic_device_t *_dev)
{
	{
		{
			bool v74_exec = 0;
			UNUSED(v74_exec);
			{
				{
					{
						v74_exec = _DML_M_regs__soft_reset(_dev);
						if(v74_exec) {
							return 1;
						} 
					} 
				} 

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__access(vic_device_t *_dev, generic_transaction_t *memop, uint32 offset, uint32 size)
{
	{
		{
			bool v75_exec = 0;
			UNUSED(v75_exec);
			{
				if ((size > 8)){
					
					
				} 
				if (SIM_mem_op_is_read(memop)){
					v75_exec = _DML_M_regs__read_access_memop(_dev, memop, offset, size);
					if(v75_exec) {
						return 1;
					} 

				} else {
					uint64 v76_writeval;
					v75_exec = _DML_M_regs__get_write_value(_dev, memop, &v76_writeval);
					if(v75_exec) {
						return 1;
					} 

					v75_exec = _DML_M_regs__write_access_memop(_dev, memop, offset, size, v76_writeval);
					if(v75_exec) {
						return 1;
					} 

				} 
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__hard_reset(vic_device_t *_dev)
{
	{
		{
			bool v77_exec = 0;
			UNUSED(v77_exec);
			{
				{
					{
						v77_exec = _DML_M_regs__irqstatus__hard_reset_register(_dev);
						if(v77_exec) {
							return 1;
						} 
					} 
{
						v77_exec = _DML_M_regs__fiqstatus__hard_reset_register(_dev);
						if(v77_exec) {
							return 1;
						} 
					} 
{
						v77_exec = _DML_M_regs__rawintr__hard_reset_register(_dev);
						if(v77_exec) {
							return 1;
						} 
					} 
{
						v77_exec = _DML_M_regs__intselect__hard_reset_register(_dev);
						if(v77_exec) {
							return 1;
						} 
					} 
{
						v77_exec = _DML_M_regs__intenable__hard_reset_register(_dev);
						if(v77_exec) {
							return 1;
						} 
					} 
{
						v77_exec = _DML_M_regs__intenclear__hard_reset_register(_dev);
						if(v77_exec) {
							return 1;
						} 
					} 
{
						v77_exec = _DML_M_regs__softint__hard_reset_register(_dev);
						if(v77_exec) {
							return 1;
						} 
					} 
{
						v77_exec = _DML_M_regs__softintclear__hard_reset_register(_dev);
						if(v77_exec) {
							return 1;
						} 
					} 
{
						v77_exec = _DML_M_regs__protection__hard_reset_register(_dev);
						if(v77_exec) {
							return 1;
						} 
					} 
{
						v77_exec = _DML_M_regs__swproritymask__hard_reset_register(_dev);
						if(v77_exec) {
							return 1;
						} 
					} 
{
						v77_exec = _DML_M_regs__proritydaisy__hard_reset_register(_dev);
						if(v77_exec) {
							return 1;
						} 
					} 
{
						int _idx0;
						for(_idx0 = 0; _idx0 < 32; _idx0++){
							v77_exec = _DML_M_regs__vectaddr__hard_reset_register(_dev, _idx0);
							if(v77_exec) {
								return 1;
							} 
						} 					} 
{
						int _idx0;
						for(_idx0 = 0; _idx0 < 32; _idx0++){
							v77_exec = _DML_M_regs__vectprority__hard_reset_register(_dev, _idx0);
							if(v77_exec) {
								return 1;
							} 
						} 					} 
{
						v77_exec = _DML_M_regs__periphid0__hard_reset_register(_dev);
						if(v77_exec) {
							return 1;
						} 
					} 
{
						v77_exec = _DML_M_regs__periphid1__hard_reset_register(_dev);
						if(v77_exec) {
							return 1;
						} 
					} 
{
						v77_exec = _DML_M_regs__periphid2__hard_reset_register(_dev);
						if(v77_exec) {
							return 1;
						} 
					} 
{
						v77_exec = _DML_M_regs__periphid3__hard_reset_register(_dev);
						if(v77_exec) {
							return 1;
						} 
					} 
				} 

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__soft_reset(vic_device_t *_dev)
{
	{
		{
			bool v78_exec = 0;
			UNUSED(v78_exec);
			{
				{
					{
						v78_exec = _DML_M_regs__irqstatus__soft_reset_register(_dev);
						if(v78_exec) {
							return 1;
						} 
					} 
{
						v78_exec = _DML_M_regs__fiqstatus__soft_reset_register(_dev);
						if(v78_exec) {
							return 1;
						} 
					} 
{
						v78_exec = _DML_M_regs__rawintr__soft_reset_register(_dev);
						if(v78_exec) {
							return 1;
						} 
					} 
{
						v78_exec = _DML_M_regs__intselect__soft_reset_register(_dev);
						if(v78_exec) {
							return 1;
						} 
					} 
{
						v78_exec = _DML_M_regs__intenable__soft_reset_register(_dev);
						if(v78_exec) {
							return 1;
						} 
					} 
{
						v78_exec = _DML_M_regs__intenclear__soft_reset_register(_dev);
						if(v78_exec) {
							return 1;
						} 
					} 
{
						v78_exec = _DML_M_regs__softint__soft_reset_register(_dev);
						if(v78_exec) {
							return 1;
						} 
					} 
{
						v78_exec = _DML_M_regs__softintclear__soft_reset_register(_dev);
						if(v78_exec) {
							return 1;
						} 
					} 
{
						v78_exec = _DML_M_regs__protection__soft_reset_register(_dev);
						if(v78_exec) {
							return 1;
						} 
					} 
{
						v78_exec = _DML_M_regs__swproritymask__soft_reset_register(_dev);
						if(v78_exec) {
							return 1;
						} 
					} 
{
						v78_exec = _DML_M_regs__proritydaisy__soft_reset_register(_dev);
						if(v78_exec) {
							return 1;
						} 
					} 
{
						int _idx0;
						for(_idx0 = 0; _idx0 < 32; _idx0++){
							v78_exec = _DML_M_regs__vectaddr__soft_reset_register(_dev, _idx0);
							if(v78_exec) {
								return 1;
							} 
						} 					} 
{
						int _idx0;
						for(_idx0 = 0; _idx0 < 32; _idx0++){
							v78_exec = _DML_M_regs__vectprority__soft_reset_register(_dev, _idx0);
							if(v78_exec) {
								return 1;
							} 
						} 					} 
{
						v78_exec = _DML_M_regs__periphid0__soft_reset_register(_dev);
						if(v78_exec) {
							return 1;
						} 
					} 
{
						v78_exec = _DML_M_regs__periphid1__soft_reset_register(_dev);
						if(v78_exec) {
							return 1;
						} 
					} 
{
						v78_exec = _DML_M_regs__periphid2__soft_reset_register(_dev);
						if(v78_exec) {
							return 1;
						} 
					} 
{
						v78_exec = _DML_M_regs__periphid3__soft_reset_register(_dev);
						if(v78_exec) {
							return 1;
						} 
					} 
				} 

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__read_access_memop(vic_device_t *_dev, generic_transaction_t *memop, uint32 offset, uint32 size)
{
	{
		{
			bool v79_exec = 0;
			UNUSED(v79_exec);
			{
				bool v80_success = 0;
				uint64 v81_val = 0;
				v79_exec = _DML_M_regs__read_access(_dev, memop, offset, size, &v80_success, &v81_val);
				if(v79_exec) {
					return 1;
				} 

				if (v80_success){
					v79_exec = _DML_M_regs__finalize_read_access(_dev, memop, v81_val);
					if(v79_exec) {
						return 1;
					} 

				} 
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__get_write_value(vic_device_t *_dev, generic_transaction_t *memop, uint64 *writeval)
{
	{
		{
			bool v82_exec = 0;
			UNUSED(v82_exec);
			{
				*writeval = SIM_mem_op_get_value(memop);
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__write_access_memop(vic_device_t *_dev, generic_transaction_t *memop, uint32 offset, uint32 size, uint64 value)
{
	{
		{
			bool v83_exec = 0;
			UNUSED(v83_exec);
			{
				bool v84_success = 0;
				v83_exec = _DML_M_regs__write_access(_dev, memop, offset, size, value, &v84_success);
				if(v83_exec) {
					return 1;
				} 

				if (v84_success){
					

				} 
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__finalize_read_access(vic_device_t *_dev, generic_transaction_t *memop, uint64 val)
{
	{
		{
			bool v85_exec = 0;
			UNUSED(v85_exec);
			{
				v85_exec = _DML_M_regs__set_read_value(_dev, memop, val);
				if(v85_exec) {
					return 1;
				} 

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__set_read_value(vic_device_t *_dev, generic_transaction_t *memop, uint64 value)
{
	{
		{
			bool v86_exec = 0;
			UNUSED(v86_exec);
			{
				SIM_mem_op_set_value(memop, value);
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__irqstatus__read_access(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value)
{
	{
		{
			bool v87_exec = 0;
			UNUSED(v87_exec);
			{
				uint64 v88_readval;
				v87_exec = _DML_M_regs__irqstatus__read_access_main(_dev, memop, msb1, lsb, &v88_readval);
				if(v87_exec) {
					return 1;
				} 

				*value = v88_readval;
				v87_exec = _DML_M_regs__irqstatus__after_read(_dev, memop);
				if(v87_exec) {
					return 1;
				} 

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__irqstatus__write_access(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value)
{
	{
		{
			bool v89_exec = 0;
			UNUSED(v89_exec);
			{
				v89_exec = _DML_M_regs__irqstatus__write_access_main(_dev, memop, msb1, lsb, value);
				if(v89_exec) {
					return 1;
				} 

				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__irqstatus__hard_reset_register(vic_device_t *_dev)
{
	{
		{
			bool v90_exec = 0;
			UNUSED(v90_exec);
			{
				{
					v90_exec = _DML_M_regs__irqstatus__hard_reset(_dev);
					if(v90_exec) {
						return 1;
					} 

				} 
				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__irqstatus__soft_reset_register(vic_device_t *_dev)
{
	{
		{
			bool v91_exec = 0;
			UNUSED(v91_exec);
			{
				v91_exec = _DML_M_regs__irqstatus__hard_reset_register(_dev);
				if(v91_exec) {
					return 1;
				} 

				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__irqstatus__read_access_main(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value)
{
	{
		{
			bool v92_exec = 0;
			UNUSED(v92_exec);
			{
				uint32 v93_fieldval = 0;
				{
					v92_exec = _DML_M_regs__irqstatus__read(_dev, &v93_fieldval);
					if(v92_exec) {
						return 1;
					} 

				} 
				*value = v93_fieldval >> lsb & MASK1((msb1 - 1) - lsb);
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__irqstatus__after_read(vic_device_t *_dev, generic_transaction_t *mop)
{
	{
		{
			bool v94_exec = 0;
			UNUSED(v94_exec);
			{
				_dev->regs.irqstatus = 0;
				v94_exec = _DML_M_vic_update_irq(_dev);
				if(v94_exec) {
					return 1;
				} 

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__irqstatus__write_access_main(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value)
{
	{
		{
			bool v95_exec = 0;
			UNUSED(v95_exec);
			{
				uint32 v96_fieldval = 0;
				{
					if (((lsb > 0) || ((msb1 - lsb) < 0x20))){
						v95_exec = _DML_M_regs__irqstatus__get(_dev, &v96_fieldval);
						if(v95_exec) {
							return 1;
						} 

						v96_fieldval = MIX(v96_fieldval, (uint64 )value << lsb, (uint64 )MASK1((msb1 - 1) - lsb) << lsb);
						

					} else {
						

					} 
				} 
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__irqstatus__hard_reset(vic_device_t *_dev)
{
	{
		{
			bool v97_exec = 0;
			UNUSED(v97_exec);
			{
				_dev->regs.irqstatus = 0x0;
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__irqstatus__read(vic_device_t *_dev, uint32 *value)
{
	{
		{
			bool v98_exec = 0;
			UNUSED(v98_exec);
			{
				*value = _dev->regs.irqstatus;
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__irqstatus__get(vic_device_t *_dev, uint32 *value)
{
	{
		{
			bool v99_exec = 0;
			UNUSED(v99_exec);
			{
				{
					*value = _dev->regs.irqstatus;
				} 
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__fiqstatus__read_access(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value)
{
	{
		{
			bool v87_exec = 0;
			UNUSED(v87_exec);
			{
				uint64 v88_readval;
				v87_exec = _DML_M_regs__fiqstatus__read_access_main(_dev, memop, msb1, lsb, &v88_readval);
				if(v87_exec) {
					return 1;
				} 

				*value = v88_readval;
				v87_exec = _DML_M_regs__fiqstatus__after_read(_dev, memop);
				if(v87_exec) {
					return 1;
				} 

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__fiqstatus__write_access(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value)
{
	{
		{
			bool v89_exec = 0;
			UNUSED(v89_exec);
			{
				v89_exec = _DML_M_regs__fiqstatus__write_access_main(_dev, memop, msb1, lsb, value);
				if(v89_exec) {
					return 1;
				} 

				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__fiqstatus__hard_reset_register(vic_device_t *_dev)
{
	{
		{
			bool v90_exec = 0;
			UNUSED(v90_exec);
			{
				{
					v90_exec = _DML_M_regs__fiqstatus__hard_reset(_dev);
					if(v90_exec) {
						return 1;
					} 

				} 
				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__fiqstatus__soft_reset_register(vic_device_t *_dev)
{
	{
		{
			bool v91_exec = 0;
			UNUSED(v91_exec);
			{
				v91_exec = _DML_M_regs__fiqstatus__hard_reset_register(_dev);
				if(v91_exec) {
					return 1;
				} 

				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__fiqstatus__read_access_main(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value)
{
	{
		{
			bool v92_exec = 0;
			UNUSED(v92_exec);
			{
				uint32 v93_fieldval = 0;
				{
					v92_exec = _DML_M_regs__fiqstatus__read(_dev, &v93_fieldval);
					if(v92_exec) {
						return 1;
					} 

				} 
				*value = v93_fieldval >> lsb & MASK1((msb1 - 1) - lsb);
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__fiqstatus__after_read(vic_device_t *_dev, generic_transaction_t *mop)
{
	{
		{
			bool v100_exec = 0;
			UNUSED(v100_exec);
			{
				_dev->regs.fiqstatus = 0;
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__fiqstatus__write_access_main(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value)
{
	{
		{
			bool v95_exec = 0;
			UNUSED(v95_exec);
			{
				uint32 v96_fieldval = 0;
				{
					if (((lsb > 0) || ((msb1 - lsb) < 0x20))){
						v95_exec = _DML_M_regs__fiqstatus__get(_dev, &v96_fieldval);
						if(v95_exec) {
							return 1;
						} 

						v96_fieldval = MIX(v96_fieldval, (uint64 )value << lsb, (uint64 )MASK1((msb1 - 1) - lsb) << lsb);
						

					} else {
						

					} 
				} 
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__fiqstatus__hard_reset(vic_device_t *_dev)
{
	{
		{
			bool v97_exec = 0;
			UNUSED(v97_exec);
			{
				_dev->regs.fiqstatus = 0x0;
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__fiqstatus__read(vic_device_t *_dev, uint32 *value)
{
	{
		{
			bool v98_exec = 0;
			UNUSED(v98_exec);
			{
				*value = _dev->regs.fiqstatus;
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__fiqstatus__get(vic_device_t *_dev, uint32 *value)
{
	{
		{
			bool v99_exec = 0;
			UNUSED(v99_exec);
			{
				{
					*value = _dev->regs.fiqstatus;
				} 
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__rawintr__read_access(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value)
{
	{
		{
			bool v87_exec = 0;
			UNUSED(v87_exec);
			{
				uint64 v88_readval;
				v87_exec = _DML_M_regs__rawintr__read_access_main(_dev, memop, msb1, lsb, &v88_readval);
				if(v87_exec) {
					return 1;
				} 

				*value = v88_readval;
				v87_exec = _DML_M_regs__rawintr__after_read(_dev, memop);
				if(v87_exec) {
					return 1;
				} 

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__rawintr__write_access(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value)
{
	{
		{
			bool v89_exec = 0;
			UNUSED(v89_exec);
			{
				v89_exec = _DML_M_regs__rawintr__write_access_main(_dev, memop, msb1, lsb, value);
				if(v89_exec) {
					return 1;
				} 

				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__rawintr__hard_reset_register(vic_device_t *_dev)
{
	{
		{
			bool v90_exec = 0;
			UNUSED(v90_exec);
			{
				{
					v90_exec = _DML_M_regs__rawintr__hard_reset(_dev);
					if(v90_exec) {
						return 1;
					} 

				} 
				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__rawintr__soft_reset_register(vic_device_t *_dev)
{
	{
		{
			bool v91_exec = 0;
			UNUSED(v91_exec);
			{
				v91_exec = _DML_M_regs__rawintr__hard_reset_register(_dev);
				if(v91_exec) {
					return 1;
				} 

				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__rawintr__read_access_main(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value)
{
	{
		{
			bool v92_exec = 0;
			UNUSED(v92_exec);
			{
				uint32 v93_fieldval = 0;
				{
					v92_exec = _DML_M_regs__rawintr__read(_dev, &v93_fieldval);
					if(v92_exec) {
						return 1;
					} 

				} 
				*value = v93_fieldval >> lsb & MASK1((msb1 - 1) - lsb);
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__rawintr__after_read(vic_device_t *_dev, generic_transaction_t *mop)
{
	{
		{
			bool v101_exec = 0;
			UNUSED(v101_exec);
			{
				_dev->regs.rawintr = 0;
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__rawintr__write_access_main(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value)
{
	{
		{
			bool v95_exec = 0;
			UNUSED(v95_exec);
			{
				uint32 v96_fieldval = 0;
				{
					if (((lsb > 0) || ((msb1 - lsb) < 0x20))){
						v95_exec = _DML_M_regs__rawintr__get(_dev, &v96_fieldval);
						if(v95_exec) {
							return 1;
						} 

						v96_fieldval = MIX(v96_fieldval, (uint64 )value << lsb, (uint64 )MASK1((msb1 - 1) - lsb) << lsb);
						

					} else {
						

					} 
				} 
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__rawintr__hard_reset(vic_device_t *_dev)
{
	{
		{
			bool v97_exec = 0;
			UNUSED(v97_exec);
			{
				_dev->regs.rawintr = 0x0;
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__rawintr__read(vic_device_t *_dev, uint32 *value)
{
	{
		{
			bool v98_exec = 0;
			UNUSED(v98_exec);
			{
				*value = _dev->regs.rawintr;
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__rawintr__get(vic_device_t *_dev, uint32 *value)
{
	{
		{
			bool v99_exec = 0;
			UNUSED(v99_exec);
			{
				{
					*value = _dev->regs.rawintr;
				} 
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__intselect__read_access(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value)
{
	{
		{
			bool v87_exec = 0;
			UNUSED(v87_exec);
			{
				uint64 v88_readval;
				v87_exec = _DML_M_regs__intselect__read_access_main(_dev, memop, msb1, lsb, &v88_readval);
				if(v87_exec) {
					return 1;
				} 

				*value = v88_readval;
				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__intselect__write_access(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value)
{
	{
		{
			bool v89_exec = 0;
			UNUSED(v89_exec);
			{
				v89_exec = _DML_M_regs__intselect__write_access_main(_dev, memop, msb1, lsb, value);
				if(v89_exec) {
					return 1;
				} 

				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__intselect__hard_reset_register(vic_device_t *_dev)
{
	{
		{
			bool v90_exec = 0;
			UNUSED(v90_exec);
			{
				{
					v90_exec = _DML_M_regs__intselect__hard_reset(_dev);
					if(v90_exec) {
						return 1;
					} 

				} 
				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__intselect__soft_reset_register(vic_device_t *_dev)
{
	{
		{
			bool v91_exec = 0;
			UNUSED(v91_exec);
			{
				v91_exec = _DML_M_regs__intselect__hard_reset_register(_dev);
				if(v91_exec) {
					return 1;
				} 

				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__intselect__read_access_main(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value)
{
	{
		{
			bool v92_exec = 0;
			UNUSED(v92_exec);
			{
				uint32 v93_fieldval = 0;
				{
					v92_exec = _DML_M_regs__intselect__read(_dev, &v93_fieldval);
					if(v92_exec) {
						return 1;
					} 

				} 
				*value = v93_fieldval >> lsb & MASK1((msb1 - 1) - lsb);
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__intselect__write_access_main(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value)
{
	{
		{
			bool v95_exec = 0;
			UNUSED(v95_exec);
			{
				uint32 v96_fieldval = 0;
				{
					if (((lsb > 0) || ((msb1 - lsb) < 0x20))){
						v95_exec = _DML_M_regs__intselect__get(_dev, &v96_fieldval);
						if(v95_exec) {
							return 1;
						} 

						v96_fieldval = MIX(v96_fieldval, (uint64 )value << lsb, (uint64 )MASK1((msb1 - 1) - lsb) << lsb);
						v95_exec = _DML_M_regs__intselect__write(_dev, v96_fieldval);
						if(v95_exec) {
							return 1;
						} 

					} else {
						v95_exec = _DML_M_regs__intselect__write(_dev, value);
						if(v95_exec) {
							return 1;
						} 

					} 
				} 
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__intselect__hard_reset(vic_device_t *_dev)
{
	{
		{
			bool v97_exec = 0;
			UNUSED(v97_exec);
			{
				_dev->regs.intselect = 0x0;
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__intselect__read(vic_device_t *_dev, uint32 *value)
{
	{
		{
			bool v98_exec = 0;
			UNUSED(v98_exec);
			{
				*value = _dev->regs.intselect;
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__intselect__get(vic_device_t *_dev, uint32 *value)
{
	{
		{
			bool v99_exec = 0;
			UNUSED(v99_exec);
			{
				{
					*value = _dev->regs.intselect;
				} 
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__intselect__write(vic_device_t *_dev, uint32 value)
{
	{
		{
			bool v102_exec = 0;
			UNUSED(v102_exec);
			{
				_dev->regs.intselect = value;
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__intenable__read_access(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value)
{
	{
		{
			bool v87_exec = 0;
			UNUSED(v87_exec);
			{
				uint64 v88_readval;
				v87_exec = _DML_M_regs__intenable__read_access_main(_dev, memop, msb1, lsb, &v88_readval);
				if(v87_exec) {
					return 1;
				} 

				*value = v88_readval;
				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__intenable__write_access(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value)
{
	{
		{
			bool v89_exec = 0;
			UNUSED(v89_exec);
			{
				v89_exec = _DML_M_regs__intenable__write_access_main(_dev, memop, msb1, lsb, value);
				if(v89_exec) {
					return 1;
				} 

				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__intenable__hard_reset_register(vic_device_t *_dev)
{
	{
		{
			bool v90_exec = 0;
			UNUSED(v90_exec);
			{
				{
					v90_exec = _DML_M_regs__intenable__hard_reset(_dev);
					if(v90_exec) {
						return 1;
					} 

				} 
				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__intenable__soft_reset_register(vic_device_t *_dev)
{
	{
		{
			bool v91_exec = 0;
			UNUSED(v91_exec);
			{
				v91_exec = _DML_M_regs__intenable__hard_reset_register(_dev);
				if(v91_exec) {
					return 1;
				} 

				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__intenable__read_access_main(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value)
{
	{
		{
			bool v92_exec = 0;
			UNUSED(v92_exec);
			{
				uint32 v93_fieldval = 0;
				{
					v92_exec = _DML_M_regs__intenable__read(_dev, &v93_fieldval);
					if(v92_exec) {
						return 1;
					} 

				} 
				*value = v93_fieldval >> lsb & MASK1((msb1 - 1) - lsb);
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__intenable__write_access_main(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value)
{
	{
		{
			bool v95_exec = 0;
			UNUSED(v95_exec);
			{
				uint32 v96_fieldval = 0;
				{
					if (((lsb > 0) || ((msb1 - lsb) < 0x20))){
						v95_exec = _DML_M_regs__intenable__get(_dev, &v96_fieldval);
						if(v95_exec) {
							return 1;
						} 

						v96_fieldval = MIX(v96_fieldval, (uint64 )value << lsb, (uint64 )MASK1((msb1 - 1) - lsb) << lsb);
						v95_exec = _DML_M_regs__intenable__write(_dev, v96_fieldval);
						if(v95_exec) {
							return 1;
						} 

					} else {
						v95_exec = _DML_M_regs__intenable__write(_dev, value);
						if(v95_exec) {
							return 1;
						} 

					} 
				} 
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__intenable__hard_reset(vic_device_t *_dev)
{
	{
		{
			bool v97_exec = 0;
			UNUSED(v97_exec);
			{
				_dev->regs.intenable = 0x0;
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__intenable__read(vic_device_t *_dev, uint32 *value)
{
	{
		{
			bool v98_exec = 0;
			UNUSED(v98_exec);
			{
				*value = _dev->regs.intenable;
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__intenable__get(vic_device_t *_dev, uint32 *value)
{
	{
		{
			bool v99_exec = 0;
			UNUSED(v99_exec);
			{
				{
					*value = _dev->regs.intenable;
				} 
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__intenable__write(vic_device_t *_dev, uint32 value)
{
	{
		{
			bool v103_exec = 0;
			UNUSED(v103_exec);
			{
				_dev->regs.intenable |= value;
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__intenclear__read_access(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value)
{
	{
		{
			bool v87_exec = 0;
			UNUSED(v87_exec);
			{
				uint64 v88_readval;
				v87_exec = _DML_M_regs__intenclear__read_access_main(_dev, memop, msb1, lsb, &v88_readval);
				if(v87_exec) {
					return 1;
				} 

				*value = v88_readval;
				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__intenclear__write_access(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value)
{
	{
		{
			bool v89_exec = 0;
			UNUSED(v89_exec);
			{
				v89_exec = _DML_M_regs__intenclear__write_access_main(_dev, memop, msb1, lsb, value);
				if(v89_exec) {
					return 1;
				} 

				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__intenclear__hard_reset_register(vic_device_t *_dev)
{
	{
		{
			bool v90_exec = 0;
			UNUSED(v90_exec);
			{
				{
					v90_exec = _DML_M_regs__intenclear__hard_reset(_dev);
					if(v90_exec) {
						return 1;
					} 

				} 
				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__intenclear__soft_reset_register(vic_device_t *_dev)
{
	{
		{
			bool v91_exec = 0;
			UNUSED(v91_exec);
			{
				v91_exec = _DML_M_regs__intenclear__hard_reset_register(_dev);
				if(v91_exec) {
					return 1;
				} 

				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__intenclear__read_access_main(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value)
{
	{
		{
			bool v92_exec = 0;
			UNUSED(v92_exec);
			{
				uint32 v93_fieldval = 0;
				{
					v92_exec = _DML_M_regs__intenclear__read(_dev, &v93_fieldval);
					if(v92_exec) {
						return 1;
					} 

				} 
				*value = v93_fieldval >> lsb & MASK1((msb1 - 1) - lsb);
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__intenclear__write_access_main(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value)
{
	{
		{
			bool v95_exec = 0;
			UNUSED(v95_exec);
			{
				uint32 v96_fieldval = 0;
				{
					if (((lsb > 0) || ((msb1 - lsb) < 0x20))){
						v95_exec = _DML_M_regs__intenclear__get(_dev, &v96_fieldval);
						if(v95_exec) {
							return 1;
						} 

						v96_fieldval = MIX(v96_fieldval, (uint64 )value << lsb, (uint64 )MASK1((msb1 - 1) - lsb) << lsb);
						v95_exec = _DML_M_regs__intenclear__write(_dev, v96_fieldval);
						if(v95_exec) {
							return 1;
						} 

					} else {
						v95_exec = _DML_M_regs__intenclear__write(_dev, value);
						if(v95_exec) {
							return 1;
						} 

					} 
				} 
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__intenclear__hard_reset(vic_device_t *_dev)
{
	{
		{
			bool v97_exec = 0;
			UNUSED(v97_exec);
			{
				_dev->regs.intenclear = 0x0;
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__intenclear__read(vic_device_t *_dev, uint32 *value)
{
	{
		{
			bool v98_exec = 0;
			UNUSED(v98_exec);
			{
				*value = _dev->regs.intenclear;
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__intenclear__get(vic_device_t *_dev, uint32 *value)
{
	{
		{
			bool v99_exec = 0;
			UNUSED(v99_exec);
			{
				{
					*value = _dev->regs.intenclear;
				} 
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__intenclear__write(vic_device_t *_dev, uint32 value)
{
	{
		{
			bool v104_exec = 0;
			UNUSED(v104_exec);
			{
				_dev->regs.intenclear &= ~value;
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__softint__read_access(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value)
{
	{
		{
			bool v87_exec = 0;
			UNUSED(v87_exec);
			{
				uint64 v88_readval;
				v87_exec = _DML_M_regs__softint__read_access_main(_dev, memop, msb1, lsb, &v88_readval);
				if(v87_exec) {
					return 1;
				} 

				*value = v88_readval;
				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__softint__write_access(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value)
{
	{
		{
			bool v89_exec = 0;
			UNUSED(v89_exec);
			{
				v89_exec = _DML_M_regs__softint__write_access_main(_dev, memop, msb1, lsb, value);
				if(v89_exec) {
					return 1;
				} 

				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__softint__hard_reset_register(vic_device_t *_dev)
{
	{
		{
			bool v90_exec = 0;
			UNUSED(v90_exec);
			{
				{
					v90_exec = _DML_M_regs__softint__hard_reset(_dev);
					if(v90_exec) {
						return 1;
					} 

				} 
				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__softint__soft_reset_register(vic_device_t *_dev)
{
	{
		{
			bool v91_exec = 0;
			UNUSED(v91_exec);
			{
				v91_exec = _DML_M_regs__softint__hard_reset_register(_dev);
				if(v91_exec) {
					return 1;
				} 

				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__softint__read_access_main(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value)
{
	{
		{
			bool v92_exec = 0;
			UNUSED(v92_exec);
			{
				uint32 v93_fieldval = 0;
				{
					v92_exec = _DML_M_regs__softint__read(_dev, &v93_fieldval);
					if(v92_exec) {
						return 1;
					} 

				} 
				*value = v93_fieldval >> lsb & MASK1((msb1 - 1) - lsb);
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__softint__write_access_main(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value)
{
	{
		{
			bool v95_exec = 0;
			UNUSED(v95_exec);
			{
				uint32 v96_fieldval = 0;
				{
					if (((lsb > 0) || ((msb1 - lsb) < 0x20))){
						v95_exec = _DML_M_regs__softint__get(_dev, &v96_fieldval);
						if(v95_exec) {
							return 1;
						} 

						v96_fieldval = MIX(v96_fieldval, (uint64 )value << lsb, (uint64 )MASK1((msb1 - 1) - lsb) << lsb);
						v95_exec = _DML_M_regs__softint__write(_dev, v96_fieldval);
						if(v95_exec) {
							return 1;
						} 

					} else {
						v95_exec = _DML_M_regs__softint__write(_dev, value);
						if(v95_exec) {
							return 1;
						} 

					} 
				} 
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__softint__hard_reset(vic_device_t *_dev)
{
	{
		{
			bool v97_exec = 0;
			UNUSED(v97_exec);
			{
				_dev->regs.softint = 0x0;
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__softint__read(vic_device_t *_dev, uint32 *value)
{
	{
		{
			bool v98_exec = 0;
			UNUSED(v98_exec);
			{
				*value = _dev->regs.softint;
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__softint__get(vic_device_t *_dev, uint32 *value)
{
	{
		{
			bool v99_exec = 0;
			UNUSED(v99_exec);
			{
				{
					*value = _dev->regs.softint;
				} 
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__softint__write(vic_device_t *_dev, uint32 value)
{
	{
		{
			bool v102_exec = 0;
			UNUSED(v102_exec);
			{
				_dev->regs.softint = value;
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__softintclear__read_access(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value)
{
	{
		{
			bool v87_exec = 0;
			UNUSED(v87_exec);
			{
				uint64 v88_readval;
				v87_exec = _DML_M_regs__softintclear__read_access_main(_dev, memop, msb1, lsb, &v88_readval);
				if(v87_exec) {
					return 1;
				} 

				*value = v88_readval;
				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__softintclear__write_access(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value)
{
	{
		{
			bool v89_exec = 0;
			UNUSED(v89_exec);
			{
				v89_exec = _DML_M_regs__softintclear__write_access_main(_dev, memop, msb1, lsb, value);
				if(v89_exec) {
					return 1;
				} 

				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__softintclear__hard_reset_register(vic_device_t *_dev)
{
	{
		{
			bool v90_exec = 0;
			UNUSED(v90_exec);
			{
				{
					v90_exec = _DML_M_regs__softintclear__hard_reset(_dev);
					if(v90_exec) {
						return 1;
					} 

				} 
				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__softintclear__soft_reset_register(vic_device_t *_dev)
{
	{
		{
			bool v91_exec = 0;
			UNUSED(v91_exec);
			{
				v91_exec = _DML_M_regs__softintclear__hard_reset_register(_dev);
				if(v91_exec) {
					return 1;
				} 

				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__softintclear__read_access_main(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value)
{
	{
		{
			bool v92_exec = 0;
			UNUSED(v92_exec);
			{
				uint32 v93_fieldval = 0;
				{
					v92_exec = _DML_M_regs__softintclear__read(_dev, &v93_fieldval);
					if(v92_exec) {
						return 1;
					} 

				} 
				*value = v93_fieldval >> lsb & MASK1((msb1 - 1) - lsb);
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__softintclear__write_access_main(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value)
{
	{
		{
			bool v95_exec = 0;
			UNUSED(v95_exec);
			{
				uint32 v96_fieldval = 0;
				{
					if (((lsb > 0) || ((msb1 - lsb) < 0x20))){
						v95_exec = _DML_M_regs__softintclear__get(_dev, &v96_fieldval);
						if(v95_exec) {
							return 1;
						} 

						v96_fieldval = MIX(v96_fieldval, (uint64 )value << lsb, (uint64 )MASK1((msb1 - 1) - lsb) << lsb);
						v95_exec = _DML_M_regs__softintclear__write(_dev, v96_fieldval);
						if(v95_exec) {
							return 1;
						} 

					} else {
						v95_exec = _DML_M_regs__softintclear__write(_dev, value);
						if(v95_exec) {
							return 1;
						} 

					} 
				} 
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__softintclear__hard_reset(vic_device_t *_dev)
{
	{
		{
			bool v97_exec = 0;
			UNUSED(v97_exec);
			{
				_dev->regs.softintclear = 0x0;
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__softintclear__read(vic_device_t *_dev, uint32 *value)
{
	{
		{
			bool v98_exec = 0;
			UNUSED(v98_exec);
			{
				*value = _dev->regs.softintclear;
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__softintclear__get(vic_device_t *_dev, uint32 *value)
{
	{
		{
			bool v99_exec = 0;
			UNUSED(v99_exec);
			{
				{
					*value = _dev->regs.softintclear;
				} 
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__softintclear__write(vic_device_t *_dev, uint32 value)
{
	{
		{
			bool v105_exec = 0;
			UNUSED(v105_exec);
			{
				_dev->regs.softintclear &= ~value;
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__protection__read_access(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value)
{
	{
		{
			bool v87_exec = 0;
			UNUSED(v87_exec);
			{
				uint64 v88_readval;
				v87_exec = _DML_M_regs__protection__read_access_main(_dev, memop, msb1, lsb, &v88_readval);
				if(v87_exec) {
					return 1;
				} 

				*value = v88_readval;
				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__protection__write_access(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value)
{
	{
		{
			bool v89_exec = 0;
			UNUSED(v89_exec);
			{
				v89_exec = _DML_M_regs__protection__write_access_main(_dev, memop, msb1, lsb, value);
				if(v89_exec) {
					return 1;
				} 

				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__protection__hard_reset_register(vic_device_t *_dev)
{
	{
		{
			bool v90_exec = 0;
			UNUSED(v90_exec);
			{
				{
					v90_exec = _DML_M_regs__protection__hard_reset(_dev);
					if(v90_exec) {
						return 1;
					} 

				} 
				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__protection__soft_reset_register(vic_device_t *_dev)
{
	{
		{
			bool v91_exec = 0;
			UNUSED(v91_exec);
			{
				v91_exec = _DML_M_regs__protection__hard_reset_register(_dev);
				if(v91_exec) {
					return 1;
				} 

				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__protection__read_access_main(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value)
{
	{
		{
			bool v92_exec = 0;
			UNUSED(v92_exec);
			{
				uint32 v93_fieldval = 0;
				{
					v92_exec = _DML_M_regs__protection__read(_dev, &v93_fieldval);
					if(v92_exec) {
						return 1;
					} 

				} 
				*value = v93_fieldval >> lsb & MASK1((msb1 - 1) - lsb);
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__protection__write_access_main(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value)
{
	{
		{
			bool v95_exec = 0;
			UNUSED(v95_exec);
			{
				uint32 v96_fieldval = 0;
				{
					if (((lsb > 0) || ((msb1 - lsb) < 0x20))){
						v95_exec = _DML_M_regs__protection__get(_dev, &v96_fieldval);
						if(v95_exec) {
							return 1;
						} 

						v96_fieldval = MIX(v96_fieldval, (uint64 )value << lsb, (uint64 )MASK1((msb1 - 1) - lsb) << lsb);
						v95_exec = _DML_M_regs__protection__write(_dev, v96_fieldval);
						if(v95_exec) {
							return 1;
						} 

					} else {
						v95_exec = _DML_M_regs__protection__write(_dev, value);
						if(v95_exec) {
							return 1;
						} 

					} 
				} 
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__protection__hard_reset(vic_device_t *_dev)
{
	{
		{
			bool v97_exec = 0;
			UNUSED(v97_exec);
			{
				_dev->regs.protection = 0x0;
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__protection__read(vic_device_t *_dev, uint32 *value)
{
	{
		{
			bool v98_exec = 0;
			UNUSED(v98_exec);
			{
				*value = _dev->regs.protection;
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__protection__get(vic_device_t *_dev, uint32 *value)
{
	{
		{
			bool v99_exec = 0;
			UNUSED(v99_exec);
			{
				{
					*value = _dev->regs.protection;
				} 
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__protection__write(vic_device_t *_dev, uint32 value)
{
	{
		{
			bool v102_exec = 0;
			UNUSED(v102_exec);
			{
				_dev->regs.protection = value;
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__swproritymask__read_access(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value)
{
	{
		{
			bool v87_exec = 0;
			UNUSED(v87_exec);
			{
				uint64 v88_readval;
				v87_exec = _DML_M_regs__swproritymask__read_access_main(_dev, memop, msb1, lsb, &v88_readval);
				if(v87_exec) {
					return 1;
				} 

				*value = v88_readval;
				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__swproritymask__write_access(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value)
{
	{
		{
			bool v89_exec = 0;
			UNUSED(v89_exec);
			{
				v89_exec = _DML_M_regs__swproritymask__write_access_main(_dev, memop, msb1, lsb, value);
				if(v89_exec) {
					return 1;
				} 

				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__swproritymask__hard_reset_register(vic_device_t *_dev)
{
	{
		{
			bool v90_exec = 0;
			UNUSED(v90_exec);
			{
				{
					v90_exec = _DML_M_regs__swproritymask__hard_reset(_dev);
					if(v90_exec) {
						return 1;
					} 

				} 
				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__swproritymask__soft_reset_register(vic_device_t *_dev)
{
	{
		{
			bool v91_exec = 0;
			UNUSED(v91_exec);
			{
				v91_exec = _DML_M_regs__swproritymask__hard_reset_register(_dev);
				if(v91_exec) {
					return 1;
				} 

				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__swproritymask__read_access_main(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value)
{
	{
		{
			bool v92_exec = 0;
			UNUSED(v92_exec);
			{
				uint32 v93_fieldval = 0;
				{
					v92_exec = _DML_M_regs__swproritymask__read(_dev, &v93_fieldval);
					if(v92_exec) {
						return 1;
					} 

				} 
				*value = v93_fieldval >> lsb & MASK1((msb1 - 1) - lsb);
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__swproritymask__write_access_main(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value)
{
	{
		{
			bool v95_exec = 0;
			UNUSED(v95_exec);
			{
				uint32 v96_fieldval = 0;
				{
					if (((lsb > 0) || ((msb1 - lsb) < 0x20))){
						v95_exec = _DML_M_regs__swproritymask__get(_dev, &v96_fieldval);
						if(v95_exec) {
							return 1;
						} 

						v96_fieldval = MIX(v96_fieldval, (uint64 )value << lsb, (uint64 )MASK1((msb1 - 1) - lsb) << lsb);
						v95_exec = _DML_M_regs__swproritymask__write(_dev, v96_fieldval);
						if(v95_exec) {
							return 1;
						} 

					} else {
						v95_exec = _DML_M_regs__swproritymask__write(_dev, value);
						if(v95_exec) {
							return 1;
						} 

					} 
				} 
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__swproritymask__hard_reset(vic_device_t *_dev)
{
	{
		{
			bool v97_exec = 0;
			UNUSED(v97_exec);
			{
				_dev->regs.swproritymask = 0x0;
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__swproritymask__read(vic_device_t *_dev, uint32 *value)
{
	{
		{
			bool v98_exec = 0;
			UNUSED(v98_exec);
			{
				*value = _dev->regs.swproritymask;
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__swproritymask__get(vic_device_t *_dev, uint32 *value)
{
	{
		{
			bool v99_exec = 0;
			UNUSED(v99_exec);
			{
				{
					*value = _dev->regs.swproritymask;
				} 
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__swproritymask__write(vic_device_t *_dev, uint32 value)
{
	{
		{
			bool v102_exec = 0;
			UNUSED(v102_exec);
			{
				_dev->regs.swproritymask = value;
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__proritydaisy__read_access(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value)
{
	{
		{
			bool v87_exec = 0;
			UNUSED(v87_exec);
			{
				uint64 v88_readval;
				v87_exec = _DML_M_regs__proritydaisy__read_access_main(_dev, memop, msb1, lsb, &v88_readval);
				if(v87_exec) {
					return 1;
				} 

				*value = v88_readval;
				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__proritydaisy__write_access(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value)
{
	{
		{
			bool v89_exec = 0;
			UNUSED(v89_exec);
			{
				v89_exec = _DML_M_regs__proritydaisy__write_access_main(_dev, memop, msb1, lsb, value);
				if(v89_exec) {
					return 1;
				} 

				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__proritydaisy__hard_reset_register(vic_device_t *_dev)
{
	{
		{
			bool v90_exec = 0;
			UNUSED(v90_exec);
			{
				{
					v90_exec = _DML_M_regs__proritydaisy__hard_reset(_dev);
					if(v90_exec) {
						return 1;
					} 

				} 
				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__proritydaisy__soft_reset_register(vic_device_t *_dev)
{
	{
		{
			bool v91_exec = 0;
			UNUSED(v91_exec);
			{
				v91_exec = _DML_M_regs__proritydaisy__hard_reset_register(_dev);
				if(v91_exec) {
					return 1;
				} 

				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__proritydaisy__read_access_main(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value)
{
	{
		{
			bool v92_exec = 0;
			UNUSED(v92_exec);
			{
				uint32 v93_fieldval = 0;
				{
					v92_exec = _DML_M_regs__proritydaisy__read(_dev, &v93_fieldval);
					if(v92_exec) {
						return 1;
					} 

				} 
				*value = v93_fieldval >> lsb & MASK1((msb1 - 1) - lsb);
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__proritydaisy__write_access_main(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value)
{
	{
		{
			bool v95_exec = 0;
			UNUSED(v95_exec);
			{
				uint32 v96_fieldval = 0;
				{
					if (((lsb > 0) || ((msb1 - lsb) < 0x20))){
						v95_exec = _DML_M_regs__proritydaisy__get(_dev, &v96_fieldval);
						if(v95_exec) {
							return 1;
						} 

						v96_fieldval = MIX(v96_fieldval, (uint64 )value << lsb, (uint64 )MASK1((msb1 - 1) - lsb) << lsb);
						v95_exec = _DML_M_regs__proritydaisy__write(_dev, v96_fieldval);
						if(v95_exec) {
							return 1;
						} 

					} else {
						v95_exec = _DML_M_regs__proritydaisy__write(_dev, value);
						if(v95_exec) {
							return 1;
						} 

					} 
				} 
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__proritydaisy__hard_reset(vic_device_t *_dev)
{
	{
		{
			bool v97_exec = 0;
			UNUSED(v97_exec);
			{
				_dev->regs.proritydaisy = 0x0;
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__proritydaisy__read(vic_device_t *_dev, uint32 *value)
{
	{
		{
			bool v98_exec = 0;
			UNUSED(v98_exec);
			{
				*value = _dev->regs.proritydaisy;
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__proritydaisy__get(vic_device_t *_dev, uint32 *value)
{
	{
		{
			bool v99_exec = 0;
			UNUSED(v99_exec);
			{
				{
					*value = _dev->regs.proritydaisy;
				} 
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__proritydaisy__write(vic_device_t *_dev, uint32 value)
{
	{
		{
			bool v102_exec = 0;
			UNUSED(v102_exec);
			{
				_dev->regs.proritydaisy = value;
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__vectaddr__read_access(vic_device_t *_dev, int _idx0, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value)
{
	{
		{
			bool v87_exec = 0;
			UNUSED(v87_exec);
			{
				uint64 v88_readval;
				v87_exec = _DML_M_regs__vectaddr__read_access_main(_dev, _idx0, memop, msb1, lsb, &v88_readval);
				if(v87_exec) {
					return 1;
				} 

				*value = v88_readval;
				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__vectaddr__write_access(vic_device_t *_dev, int _idx0, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value)
{
	{
		{
			bool v89_exec = 0;
			UNUSED(v89_exec);
			{
				v89_exec = _DML_M_regs__vectaddr__write_access_main(_dev, _idx0, memop, msb1, lsb, value);
				if(v89_exec) {
					return 1;
				} 

				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__vectaddr__hard_reset_register(vic_device_t *_dev, int _idx0)
{
	{
		{
			bool v90_exec = 0;
			UNUSED(v90_exec);
			{
				{
					v90_exec = _DML_M_regs__vectaddr__hard_reset(_dev, _idx0);
					if(v90_exec) {
						return 1;
					} 

				} 
				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__vectaddr__soft_reset_register(vic_device_t *_dev, int _idx0)
{
	{
		{
			bool v91_exec = 0;
			UNUSED(v91_exec);
			{
				v91_exec = _DML_M_regs__vectaddr__hard_reset_register(_dev, _idx0);
				if(v91_exec) {
					return 1;
				} 

				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__vectaddr__read_access_main(vic_device_t *_dev, int _idx0, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value)
{
	{
		{
			bool v92_exec = 0;
			UNUSED(v92_exec);
			{
				uint32 v93_fieldval = 0;
				{
					v92_exec = _DML_M_regs__vectaddr__read(_dev, _idx0, &v93_fieldval);
					if(v92_exec) {
						return 1;
					} 

				} 
				*value = v93_fieldval >> lsb & MASK1((msb1 - 1) - lsb);
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__vectaddr__write_access_main(vic_device_t *_dev, int _idx0, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value)
{
	{
		{
			bool v95_exec = 0;
			UNUSED(v95_exec);
			{
				uint32 v96_fieldval = 0;
				{
					if (((lsb > 0) || ((msb1 - lsb) < 0x20))){
						v95_exec = _DML_M_regs__vectaddr__get(_dev, _idx0, &v96_fieldval);
						if(v95_exec) {
							return 1;
						} 

						v96_fieldval = MIX(v96_fieldval, (uint64 )value << lsb, (uint64 )MASK1((msb1 - 1) - lsb) << lsb);
						v95_exec = _DML_M_regs__vectaddr__write(_dev, _idx0, v96_fieldval);
						if(v95_exec) {
							return 1;
						} 

					} else {
						v95_exec = _DML_M_regs__vectaddr__write(_dev, _idx0, value);
						if(v95_exec) {
							return 1;
						} 

					} 
				} 
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__vectaddr__hard_reset(vic_device_t *_dev, int _idx0)
{
	{
		{
			bool v97_exec = 0;
			UNUSED(v97_exec);
			{
				_dev->regs.vectaddr[_idx0] = 0x0;
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__vectaddr__read(vic_device_t *_dev, int _idx0, uint32 *value)
{
	{
		{
			bool v98_exec = 0;
			UNUSED(v98_exec);
			{
				*value = _dev->regs.vectaddr[_idx0];
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__vectaddr__get(vic_device_t *_dev, int _idx0, uint32 *value)
{
	{
		{
			bool v99_exec = 0;
			UNUSED(v99_exec);
			{
				{
					*value = _dev->regs.vectaddr[_idx0];
				} 
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__vectaddr__write(vic_device_t *_dev, int _idx0, uint32 value)
{
	{
		{
			bool v102_exec = 0;
			UNUSED(v102_exec);
			{
				_dev->regs.vectaddr[_idx0] = value;
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__vectprority__read_access(vic_device_t *_dev, int _idx0, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value)
{
	{
		{
			bool v87_exec = 0;
			UNUSED(v87_exec);
			{
				uint64 v88_readval;
				v87_exec = _DML_M_regs__vectprority__read_access_main(_dev, _idx0, memop, msb1, lsb, &v88_readval);
				if(v87_exec) {
					return 1;
				} 

				*value = v88_readval;
				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__vectprority__write_access(vic_device_t *_dev, int _idx0, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value)
{
	{
		{
			bool v89_exec = 0;
			UNUSED(v89_exec);
			{
				v89_exec = _DML_M_regs__vectprority__write_access_main(_dev, _idx0, memop, msb1, lsb, value);
				if(v89_exec) {
					return 1;
				} 

				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__vectprority__hard_reset_register(vic_device_t *_dev, int _idx0)
{
	{
		{
			bool v90_exec = 0;
			UNUSED(v90_exec);
			{
				{
					v90_exec = _DML_M_regs__vectprority__hard_reset(_dev, _idx0);
					if(v90_exec) {
						return 1;
					} 

				} 
				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__vectprority__soft_reset_register(vic_device_t *_dev, int _idx0)
{
	{
		{
			bool v91_exec = 0;
			UNUSED(v91_exec);
			{
				v91_exec = _DML_M_regs__vectprority__hard_reset_register(_dev, _idx0);
				if(v91_exec) {
					return 1;
				} 

				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__vectprority__read_access_main(vic_device_t *_dev, int _idx0, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value)
{
	{
		{
			bool v92_exec = 0;
			UNUSED(v92_exec);
			{
				uint32 v93_fieldval = 0;
				{
					v92_exec = _DML_M_regs__vectprority__read(_dev, _idx0, &v93_fieldval);
					if(v92_exec) {
						return 1;
					} 

				} 
				*value = v93_fieldval >> lsb & MASK1((msb1 - 1) - lsb);
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__vectprority__write_access_main(vic_device_t *_dev, int _idx0, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value)
{
	{
		{
			bool v95_exec = 0;
			UNUSED(v95_exec);
			{
				uint32 v96_fieldval = 0;
				{
					if (((lsb > 0) || ((msb1 - lsb) < 0x20))){
						v95_exec = _DML_M_regs__vectprority__get(_dev, _idx0, &v96_fieldval);
						if(v95_exec) {
							return 1;
						} 

						v96_fieldval = MIX(v96_fieldval, (uint64 )value << lsb, (uint64 )MASK1((msb1 - 1) - lsb) << lsb);
						v95_exec = _DML_M_regs__vectprority__write(_dev, _idx0, v96_fieldval);
						if(v95_exec) {
							return 1;
						} 

					} else {
						v95_exec = _DML_M_regs__vectprority__write(_dev, _idx0, value);
						if(v95_exec) {
							return 1;
						} 

					} 
				} 
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__vectprority__hard_reset(vic_device_t *_dev, int _idx0)
{
	{
		{
			bool v97_exec = 0;
			UNUSED(v97_exec);
			{
				_dev->regs.vectprority[_idx0] = 0x0;
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__vectprority__read(vic_device_t *_dev, int _idx0, uint32 *value)
{
	{
		{
			bool v98_exec = 0;
			UNUSED(v98_exec);
			{
				*value = _dev->regs.vectprority[_idx0];
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__vectprority__get(vic_device_t *_dev, int _idx0, uint32 *value)
{
	{
		{
			bool v99_exec = 0;
			UNUSED(v99_exec);
			{
				{
					*value = _dev->regs.vectprority[_idx0];
				} 
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__vectprority__write(vic_device_t *_dev, int _idx0, uint32 value)
{
	{
		{
			bool v102_exec = 0;
			UNUSED(v102_exec);
			{
				_dev->regs.vectprority[_idx0] = value;
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__periphid0__read_access(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value)
{
	{
		{
			bool v87_exec = 0;
			UNUSED(v87_exec);
			{
				uint64 v88_readval;
				v87_exec = _DML_M_regs__periphid0__read_access_main(_dev, memop, msb1, lsb, &v88_readval);
				if(v87_exec) {
					return 1;
				} 

				*value = v88_readval;
				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__periphid0__write_access(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value)
{
	{
		{
			bool v89_exec = 0;
			UNUSED(v89_exec);
			{
				v89_exec = _DML_M_regs__periphid0__write_access_main(_dev, memop, msb1, lsb, value);
				if(v89_exec) {
					return 1;
				} 

				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__periphid0__hard_reset_register(vic_device_t *_dev)
{
	{
		{
			bool v90_exec = 0;
			UNUSED(v90_exec);
			{
				{
					v90_exec = _DML_M_regs__periphid0__hard_reset(_dev);
					if(v90_exec) {
						return 1;
					} 

				} 
				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__periphid0__soft_reset_register(vic_device_t *_dev)
{
	{
		{
			bool v91_exec = 0;
			UNUSED(v91_exec);
			{
				v91_exec = _DML_M_regs__periphid0__hard_reset_register(_dev);
				if(v91_exec) {
					return 1;
				} 

				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__periphid0__read_access_main(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value)
{
	{
		{
			bool v92_exec = 0;
			UNUSED(v92_exec);
			{
				uint32 v93_fieldval = 0;
				{
					v92_exec = _DML_M_regs__periphid0__read(_dev, &v93_fieldval);
					if(v92_exec) {
						return 1;
					} 

				} 
				*value = v93_fieldval >> lsb & MASK1((msb1 - 1) - lsb);
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__periphid0__write_access_main(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value)
{
	{
		{
			bool v95_exec = 0;
			UNUSED(v95_exec);
			{
				uint32 v96_fieldval = 0;
				{
					if (((lsb > 0) || ((msb1 - lsb) < 0x20))){
						v95_exec = _DML_M_regs__periphid0__get(_dev, &v96_fieldval);
						if(v95_exec) {
							return 1;
						} 

						v96_fieldval = MIX(v96_fieldval, (uint64 )value << lsb, (uint64 )MASK1((msb1 - 1) - lsb) << lsb);
						

					} else {
						

					} 
				} 
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__periphid0__hard_reset(vic_device_t *_dev)
{
	{
		{
			bool v97_exec = 0;
			UNUSED(v97_exec);
			{
				_dev->regs.periphid0 = 0x0;
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__periphid0__read(vic_device_t *_dev, uint32 *value)
{
	{
		{
			bool v106_exec = 0;
			UNUSED(v106_exec);
			{
				*value = 0x192;
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__periphid0__get(vic_device_t *_dev, uint32 *value)
{
	{
		{
			bool v99_exec = 0;
			UNUSED(v99_exec);
			{
				{
					*value = _dev->regs.periphid0;
				} 
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__periphid1__read_access(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value)
{
	{
		{
			bool v87_exec = 0;
			UNUSED(v87_exec);
			{
				uint64 v88_readval;
				v87_exec = _DML_M_regs__periphid1__read_access_main(_dev, memop, msb1, lsb, &v88_readval);
				if(v87_exec) {
					return 1;
				} 

				*value = v88_readval;
				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__periphid1__write_access(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value)
{
	{
		{
			bool v89_exec = 0;
			UNUSED(v89_exec);
			{
				v89_exec = _DML_M_regs__periphid1__write_access_main(_dev, memop, msb1, lsb, value);
				if(v89_exec) {
					return 1;
				} 

				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__periphid1__hard_reset_register(vic_device_t *_dev)
{
	{
		{
			bool v90_exec = 0;
			UNUSED(v90_exec);
			{
				{
					v90_exec = _DML_M_regs__periphid1__hard_reset(_dev);
					if(v90_exec) {
						return 1;
					} 

				} 
				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__periphid1__soft_reset_register(vic_device_t *_dev)
{
	{
		{
			bool v91_exec = 0;
			UNUSED(v91_exec);
			{
				v91_exec = _DML_M_regs__periphid1__hard_reset_register(_dev);
				if(v91_exec) {
					return 1;
				} 

				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__periphid1__read_access_main(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value)
{
	{
		{
			bool v92_exec = 0;
			UNUSED(v92_exec);
			{
				uint32 v93_fieldval = 0;
				{
					v92_exec = _DML_M_regs__periphid1__read(_dev, &v93_fieldval);
					if(v92_exec) {
						return 1;
					} 

				} 
				*value = v93_fieldval >> lsb & MASK1((msb1 - 1) - lsb);
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__periphid1__write_access_main(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value)
{
	{
		{
			bool v95_exec = 0;
			UNUSED(v95_exec);
			{
				uint32 v96_fieldval = 0;
				{
					if (((lsb > 0) || ((msb1 - lsb) < 0x20))){
						v95_exec = _DML_M_regs__periphid1__get(_dev, &v96_fieldval);
						if(v95_exec) {
							return 1;
						} 

						v96_fieldval = MIX(v96_fieldval, (uint64 )value << lsb, (uint64 )MASK1((msb1 - 1) - lsb) << lsb);
						

					} else {
						

					} 
				} 
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__periphid1__hard_reset(vic_device_t *_dev)
{
	{
		{
			bool v97_exec = 0;
			UNUSED(v97_exec);
			{
				_dev->regs.periphid1 = 0x0;
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__periphid1__read(vic_device_t *_dev, uint32 *value)
{
	{
		{
			bool v107_exec = 0;
			UNUSED(v107_exec);
			{
				*value = 0x11;
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__periphid1__get(vic_device_t *_dev, uint32 *value)
{
	{
		{
			bool v99_exec = 0;
			UNUSED(v99_exec);
			{
				{
					*value = _dev->regs.periphid1;
				} 
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__periphid2__read_access(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value)
{
	{
		{
			bool v87_exec = 0;
			UNUSED(v87_exec);
			{
				uint64 v88_readval;
				v87_exec = _DML_M_regs__periphid2__read_access_main(_dev, memop, msb1, lsb, &v88_readval);
				if(v87_exec) {
					return 1;
				} 

				*value = v88_readval;
				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__periphid2__write_access(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value)
{
	{
		{
			bool v89_exec = 0;
			UNUSED(v89_exec);
			{
				v89_exec = _DML_M_regs__periphid2__write_access_main(_dev, memop, msb1, lsb, value);
				if(v89_exec) {
					return 1;
				} 

				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__periphid2__hard_reset_register(vic_device_t *_dev)
{
	{
		{
			bool v90_exec = 0;
			UNUSED(v90_exec);
			{
				{
					v90_exec = _DML_M_regs__periphid2__hard_reset(_dev);
					if(v90_exec) {
						return 1;
					} 

				} 
				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__periphid2__soft_reset_register(vic_device_t *_dev)
{
	{
		{
			bool v91_exec = 0;
			UNUSED(v91_exec);
			{
				v91_exec = _DML_M_regs__periphid2__hard_reset_register(_dev);
				if(v91_exec) {
					return 1;
				} 

				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__periphid2__read_access_main(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value)
{
	{
		{
			bool v92_exec = 0;
			UNUSED(v92_exec);
			{
				uint32 v93_fieldval = 0;
				{
					v92_exec = _DML_M_regs__periphid2__read(_dev, &v93_fieldval);
					if(v92_exec) {
						return 1;
					} 

				} 
				*value = v93_fieldval >> lsb & MASK1((msb1 - 1) - lsb);
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__periphid2__write_access_main(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value)
{
	{
		{
			bool v95_exec = 0;
			UNUSED(v95_exec);
			{
				uint32 v96_fieldval = 0;
				{
					if (((lsb > 0) || ((msb1 - lsb) < 0x20))){
						v95_exec = _DML_M_regs__periphid2__get(_dev, &v96_fieldval);
						if(v95_exec) {
							return 1;
						} 

						v96_fieldval = MIX(v96_fieldval, (uint64 )value << lsb, (uint64 )MASK1((msb1 - 1) - lsb) << lsb);
						

					} else {
						

					} 
				} 
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__periphid2__hard_reset(vic_device_t *_dev)
{
	{
		{
			bool v97_exec = 0;
			UNUSED(v97_exec);
			{
				_dev->regs.periphid2 = 0x0;
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__periphid2__read(vic_device_t *_dev, uint32 *value)
{
	{
		{
			bool v108_exec = 0;
			UNUSED(v108_exec);
			{
				*value = 0x04;
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__periphid2__get(vic_device_t *_dev, uint32 *value)
{
	{
		{
			bool v99_exec = 0;
			UNUSED(v99_exec);
			{
				{
					*value = _dev->regs.periphid2;
				} 
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__periphid3__read_access(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value)
{
	{
		{
			bool v87_exec = 0;
			UNUSED(v87_exec);
			{
				uint64 v88_readval;
				v87_exec = _DML_M_regs__periphid3__read_access_main(_dev, memop, msb1, lsb, &v88_readval);
				if(v87_exec) {
					return 1;
				} 

				*value = v88_readval;
				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__periphid3__write_access(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value)
{
	{
		{
			bool v89_exec = 0;
			UNUSED(v89_exec);
			{
				v89_exec = _DML_M_regs__periphid3__write_access_main(_dev, memop, msb1, lsb, value);
				if(v89_exec) {
					return 1;
				} 

				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__periphid3__hard_reset_register(vic_device_t *_dev)
{
	{
		{
			bool v90_exec = 0;
			UNUSED(v90_exec);
			{
				{
					v90_exec = _DML_M_regs__periphid3__hard_reset(_dev);
					if(v90_exec) {
						return 1;
					} 

				} 
				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__periphid3__soft_reset_register(vic_device_t *_dev)
{
	{
		{
			bool v91_exec = 0;
			UNUSED(v91_exec);
			{
				v91_exec = _DML_M_regs__periphid3__hard_reset_register(_dev);
				if(v91_exec) {
					return 1;
				} 

				

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__periphid3__read_access_main(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 *value)
{
	{
		{
			bool v92_exec = 0;
			UNUSED(v92_exec);
			{
				uint32 v93_fieldval = 0;
				{
					v92_exec = _DML_M_regs__periphid3__read(_dev, &v93_fieldval);
					if(v92_exec) {
						return 1;
					} 

				} 
				*value = v93_fieldval >> lsb & MASK1((msb1 - 1) - lsb);
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__periphid3__write_access_main(vic_device_t *_dev, generic_transaction_t *memop, uint8 msb1, uint8 lsb, uint64 value)
{
	{
		{
			bool v95_exec = 0;
			UNUSED(v95_exec);
			{
				uint32 v96_fieldval = 0;
				{
					if (((lsb > 0) || ((msb1 - lsb) < 0x20))){
						v95_exec = _DML_M_regs__periphid3__get(_dev, &v96_fieldval);
						if(v95_exec) {
							return 1;
						} 

						v96_fieldval = MIX(v96_fieldval, (uint64 )value << lsb, (uint64 )MASK1((msb1 - 1) - lsb) << lsb);
						v95_exec = _DML_M_regs__periphid3__write(_dev, v96_fieldval);
						if(v95_exec) {
							return 1;
						} 

					} else {
						v95_exec = _DML_M_regs__periphid3__write(_dev, value);
						if(v95_exec) {
							return 1;
						} 

					} 
				} 
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__periphid3__hard_reset(vic_device_t *_dev)
{
	{
		{
			bool v97_exec = 0;
			UNUSED(v97_exec);
			{
				_dev->regs.periphid3 = 0x0;
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__periphid3__read(vic_device_t *_dev, uint32 *value)
{
	{
		{
			bool v98_exec = 0;
			UNUSED(v98_exec);
			{
				*value = _dev->regs.periphid3;
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__periphid3__get(vic_device_t *_dev, uint32 *value)
{
	{
		{
			bool v99_exec = 0;
			UNUSED(v99_exec);
			{
				{
					*value = _dev->regs.periphid3;
				} 
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_regs__periphid3__write(vic_device_t *_dev, uint32 value)
{
	{
		{
			bool v102_exec = 0;
			UNUSED(v102_exec);
			{
				_dev->regs.periphid3 = value;
			} 
		}
		return 0;
	}
}

static bool				
_DML_M_int_update__int_update(vic_device_t *_dev)
{
	{
		{
			bool v109_exec = 0;
			UNUSED(v109_exec);
			{
				v109_exec = _DML_M_vic_update_irq(_dev);
				if(v109_exec) {
					return 1;
				} 

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_simple_interrupt__interrupt(vic_device_t *_dev, int num)
{
	{
		{
			bool v110_exec = 0;
			UNUSED(v110_exec);
			{
				_dev->regs.rawintr = (1 << num);
				_dev->regs.irqstatus |= (((((1 << num)) & ~(_dev->regs.intselect)) & _dev->regs.intenable));
				_dev->regs.fiqstatus |= (((((1 << num)) & (_dev->regs.intselect)) & _dev->regs.intenable));
				v110_exec = _DML_M_vic_update_irq(_dev);
				if(v110_exec) {
					return 1;
				} 

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_simple_interrupt__interrupt_clear(vic_device_t *_dev, int num)
{
	{
		{
			bool v111_exec = 0;
			UNUSED(v111_exec);
			{
				_dev->regs.irqstatus &= ~((1 << num));
				v111_exec = _DML_M_vic_update_irq(_dev);
				if(v111_exec) {
					return 1;
				} 

			} 
		}
		return 0;
	}
}

static bool				
_DML_M_vic_update_irq(vic_device_t *_dev)
{
	{
		{
			bool v112_exec = 0;
			UNUSED(v112_exec);
			{
				if ((_dev->regs.fiqstatus != 0)){
					_dev->irq.simple_interrupt->interrupt(_dev->irq.obj, 1);
				} else {
					_dev->irq.simple_interrupt->interrupt_clear(_dev->irq.obj, 1);
				} 
				if ((_dev->regs.irqstatus != 0)){
					_dev->irq.simple_interrupt->interrupt(_dev->irq.obj, 0);
				} else {
					_dev->irq.simple_interrupt->interrupt_clear(_dev->irq.obj, 0);
				} 
			} 
		}
		return 0;
	}
}

static int irq_set(void *_, conf_object_t *obj, attr_value_t *val,  attr_value_t *_index) {
	vic_device_t *_dev = (vic_device_t *)obj;
	int ret = 0;
	void const *iface = NULL;
	conf_object_t *peer = NULL;
	const char *port = NULL;
	
	if(SIM_attr_is_object(*val)){
		peer = SIM_attr_object(*val);
	} else if(SIM_attr_is_list(*val)) {
		peer = SIM_attr_object(SIM_attr_list_item(*val, 0));
		port = SIM_attr_string(SIM_attr_list_item(*val, 1));
	}
	if(_dev->irq.obj == peer && _dev->irq.port == port) {
		return 0;
	}
	_dev->irq.obj = peer;
	if(_dev->irq.port)
		MM_FREE((void *)_dev->irq.port);
	if(port) {
		_dev->irq.port = MM_STRDUP(port);
	} else { 
		_dev->irq.port = NULL;
	}
	if(port) {
		iface = SIM_c_get_port_interface(peer, "simple_interrupt", port);
	} else {
		iface = SIM_c_get_interface(peer, "simple_interrupt");
	}
	_dev->irq.simple_interrupt = iface;
	return ret;
}

static attr_value_t irq_get(void *_, conf_object_t *obj, attr_value_t *_index) {
	vic_device_t *_dev = (vic_device_t *)obj;
	int ret = 0;
	UNUSED(ret);
	attr_value_t attr;
	if(_dev->irq.port) {
		attr = SIM_alloc_attr_list(2);
		SIM_attr_list_set_item(&attr, 0, SIM_make_attr_string(_dev->irq.port));
		SIM_attr_list_set_item(&attr, 1, SIM_make_attr_obj(_dev->irq.obj));
	}
	return attr;
}

const struct ConnectDescription vic_device_connects[] = {
	[0] = (struct ConnectDescription) {
		.name = "irq",
		.set = irq_set,
		.get = irq_get,
	},
	[1] = (struct ConnectDescription) {
		.name = NULL,
		.set = NULL,
		.get = NULL,
	}
};

static const int_update_interface_t int_update_iface = {
	.int_update = _DML_IFACE_int_update__int_update,
};

static const simple_interrupt_interface_t simple_interrupt_iface = {
	.interrupt = _DML_IFACE_simple_interrupt__interrupt,
	.interrupt_clear = _DML_IFACE_simple_interrupt__interrupt_clear,
};

static const struct InterfaceDescription vic_device_ifaces[] = {
	[0] = (struct InterfaceDescription ) {
		.name = "int_update",
		.iface = &int_update_iface,
	},
	[1] = (struct InterfaceDescription ) {
		.name = "simple_interrupt",
		.iface = &simple_interrupt_iface,
	},
	[2] = {}
};

static const class_resource_t vic_device_resources = {
	.ifaces = vic_device_ifaces,
	.connects = vic_device_connects,
	.ports = NULL,
};

static const bank_access_t regs_access = {
	.read = &regs_read,
	.write = &regs_write,
};

static const struct bank_access_description vic_device_bank_access[] = {
	[0] = (struct bank_access_description) {
		.name = "regs",
		.access = &regs_access,
	},
	[1] = {}
};

static const class_data_t vic_device_class_data = {
	.new_instance = vic_device_create,
	.resources = &vic_device_resources,
	.bank_access = vic_device_bank_access,
};

void init_vic_device(void) {
	static conf_class_t class_data = {
		.cls_name = "vic_device",
		.cls_data = &vic_device_class_data,
	};
	SIM_register_conf_class(class_data.cls_name, &class_data);
}

void init_local(void) {
	init_vic_device();
}
