/* Generated by dmlc, not to edit it */
/* Fri Oct 18 17:48:44 2013
 */

#ifndef VIC_DEVICE_H
#define VIC_DEVICE_H

#include <simics/base_types.h>
#include <simics/core/object_model.h>
#include <simics/core/object_class.h>
#include <simics/generic_transaction.h>
#include <simics/bank_access.h>
#include <simics/dev_iface.h>
#include "vic_device_struct.h"

typedef enum vic_device_log_group {
	Register_Read = 1,
	Register_Write = 2
} vic_device_log_group_t;

void vic_device_hard_reset(vic_device_t *_obj);
void vic_device_soft_reset(vic_device_t *_obj);

#endif
