/*
 * skyeye_platform.c: 
 *
 * Copyright (C) 2013 alloc <alloc.young@gmail.com>
 * Skyeye Develop Group, for help please send mail to
 * <skyeye-developer@lists.gro.clinux.org>
 *
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 */
#include "platform.h"
#include "gen_utility.h"
#include <time.h>
#include "gen_method_protos.h"
#include "gen_connect.h"
#include "gen_implement.h"
#include "gen_attribute.h"
#include "gen_port.h"


extern object_t *DEV;

static void gen_headerfile(device_t *dev, FILE *f) {
    const char *name = dev->obj.name;
    time_t timep;

    time(&timep);
    fprintf(f, "/* \n");
    fprintf(f, " * %s.c\n", name);
    fprintf(f, " * Generated by dmlc, not to edit it\n");
    fprintf(f, " * %s",asctime(localtime(&timep)));
    fprintf(f, " */\n");
	fprintf(f, "\n");
    fprintf(f, "#include \"%s.h\"\n", name);
    fprintf(f, "#include \"%s_protos.c\"\n", name);
	fprintf(f, "\nstatic void %s_pre_delete_instance(conf_object_t *obj);\n", name);
	//fprintf(f, "");
}

void pre_gen_code(device_t *dev, FILE *f) {
	gen_headerfile(dev, f);
}

static void gen_bank_read_access(object_t *obj, FILE *f) {
	const char *name = obj->name;
	const char *dev_name = DEV->name;

	fprintf(f, "\nstatic exception_type_t\n");
	fprintf(f, "%s_read(conf_object_t *obj, physical_address_t addr, void *buf, size_t count) {\n", name);
	F_HEAD;
	fprintf(f, "\t%s_t *_dev = (%s_t *)obj;\n", dev_name, dev_name);
	fprintf(f, "\tgeneric_transaction_t memop;\n");
	fprintf(f, "\tbool ret = 0;\n");
	fprintf(f, "\tUNUSED(ret);\n");
	fprintf(f, "\tuint64_t val;\n");
	fprintf(f, "\n");
	fprintf(f, "\tMEMSET(&memop, 0, sizeof(memop));\n");
	fprintf(f, "\tSIM_set_mem_op(&memop, !SIM_Trn_Write);\n");
	fprintf(f, "\tret = _DML_M_%s__access(_dev, &memop, addr, (physical_address_t)count);\n",  name);
	fprintf(f, "\tval = SIM_mem_op_get_value(&memop);\n");
	fprintf(f, "\tMEMCPY(buf, &val, count);\n");
	F_END;
	fprintf(f, "\treturn No_exp;\n");
	fprintf(f, "}\n");
}

static void gen_bank_write_access(object_t *obj, FILE *f) {
	const char *name = obj->name;
	const char *dev_name = DEV->name;

	fprintf(f, "\nstatic exception_type_t\n");
	fprintf(f, "%s_write(conf_object_t *obj, physical_address_t addr, const void *buf, size_t count) {\n", name);
	F_HEAD;
	fprintf(f, "\t%s_t *_dev = (%s_t *)obj;\n", dev_name, dev_name);
	fprintf(f, "\tgeneric_transaction_t memop;\n");
	fprintf(f, "\tbool ret = 0;\n");
	fprintf(f, "\tUNUSED(ret);\n");
	fprintf(f, "\tuint64_t val = *(uint64 *)buf;\n");
	fprintf(f, "\n");
	fprintf(f, "\tmemset(&memop, 0, sizeof(memop));\n");
	fprintf(f, "\tSIM_set_mem_op(&memop, SIM_Trn_Write);\n");
	fprintf(f, "\tSIM_mem_op_set_value(&memop, val);\n");
	fprintf(f, "\tret = _DML_M_%s__access(_dev, &memop, (physical_address_t)addr, (physical_address_t)count);\n",  name);
	F_END;
	fprintf(f, "\treturn No_exp;\n");
	fprintf(f, "}\n");
}

static void gen_bank_access(object_t *obj, FILE *f) {
	gen_bank_read_access(obj, f);
	gen_bank_write_access(obj, f);
    add_object_method(obj, "access");
}

static void gen_banks_mr(device_t *dev, FILE *f) {
    int i = 0;
    object_t *obj;

    for(i = 0; i < dev->bank_count; i++) {
        obj = dev->banks[i];
        gen_bank_access(obj, f);
    }
}

static void gen_bank_access_iface(object_t *obj, FILE *f) {
	const char *name;

	name = obj->name;
	fprintf(f, "\nstatic const bank_access_t %s_access = {\n", name);
	fprintf(f, "\t.read = &%s_read,\n", name);
	fprintf(f, "\t.write = &%s_write,\n", name);
	fprintf(f, "};\n");
}

static void gen_bank_access_descriptor(device_t *dev, FILE *f) {
    int i = 0;
    object_t *obj = &dev->obj;

	fprintf(f, "\nstatic const struct bank_access_description %s_bank_access[] = {\n", obj->name);
    for(i = 0; i < dev->bank_count; i++) {
        obj = dev->banks[i];
		fprintf(f, "\t[%d] = (struct bank_access_description) {\n", i);
		fprintf(f, "\t\t.name = \"%s\",\n", obj->name);
		fprintf(f, "\t\t.access = &%s_access,\n", obj->name);
		fprintf(f, "\t},\n");
    }	
	fprintf(f, "\t[%d] = {}\n", i);
	fprintf(f, "};\n");
}

static void gen_bank_access_info(device_t *dev, FILE *f) {
    int i = 0;
    object_t *obj;

    for(i = 0; i < dev->bank_count; i++) {
        obj = dev->banks[i];
        gen_bank_access_iface(obj, f);
    }
	gen_bank_access_descriptor(dev, f);
}


static void gen_mmio_setup(device_t *dev, FILE *f) {
    const char *dev_name = dev->obj.name;
    int i = 0;
    object_t *obj;

    gen_banks_mr(dev, f);
}

void gen_device_constructor(device_t *dev, FILE *f) {
    const char *dev_name = dev->obj.name;
    int index = get_local_index();

    add_object_method(&dev->obj, "init");
	add_object_method(&dev->obj, "post_init");
    fprintf(f, "\nstatic conf_object_t  *%s_new_instance(const char *name) {\n", dev_name);
    fprintf(f, "\t%s_t *_dev = (%s_t *)MM_ZALLOC(sizeof(*_dev));\n", dev_name, dev_name);
	fprintf(f, "\tconf_object_register(&_dev->obj, name);\n");
    fprintf(f, "\tbool v%d_exec = 0;\n", index);
    fprintf(f, "\tUNUSED(v%d_exec);\n", index);
    fprintf(f, "\n\t%s_hard_reset(_dev);\n", dev_name);
    fprintf(f, "\tv%d_exec = _DML_M_init(_dev);\n", index);
    fprintf(f, "\treturn &_dev->obj;\n");
    fprintf(f, "}\n");

}

static void gen_device_destructor(device_t *dev, FILE *f) {
	const char *name = dev->obj.name;

	fprintf(f, "\nstatic void %s_finalize_instance(conf_object_t *obj) {\n", name);
	fprintf(f, "\t%s_t *_dev = (%s_t *)obj;\n", name, name);
	fprintf(f, "\tUNUSED(_dev);\n");
	fprintf(f, "\tbool exec = _DML_M_post_init(_dev);\n");
	fprintf(f, "\tUNUSED(exec)\n");
	fprintf(f, "\treturn;\n");
	fprintf(f, "}\n");

	fprintf(f, "\nstatic int %s_delete_instance(conf_object_t *obj) {\n", name);
	fprintf(f, "\tMM_FREE(obj);\n");
	fprintf(f, "\treturn 0;\n");
	fprintf(f, "}\n");
}

static void gen_device_connect(device_t *dev, FILE *f) {
    struct list_head *p;
    object_t *tmp;
    int i = 0;
    const char *name;

    gen_device_connect_code(dev, f);
    fprintf(f, "\nstatic const struct ConnectDescription %s_connects[] = {\n", dev->obj.name);
    list_for_each(p, &dev->connects) {
        tmp = list_entry(p, object_t, entry);
	if(tmp->is_array) {
		name = tmp->a_name;
	} else {
		name = tmp->name;
	}
        fprintf(f, "\t[%d] = (struct ConnectDescription) {\n", i);
        fprintf(f, "\t\t.name = \"%s\",\n", name);
        fprintf(f, "\t\t.set = %s_set,\n", name);
        fprintf(f, "\t\t.get = %s_get,\n", name);
        fprintf(f, "\t},\n");
        i++;
    }
    fprintf(f, "\t[%d] = {}\n", i);
    fprintf(f, "};\n");

}

static void gen_device_module(device_t *dev, FILE *f) {
	const char *name = dev->obj.name;
}

static void gen_local_init(device_t *dev, FILE *f) {

	fprintf(f, "\nvoid\n");
	fprintf(f, "init_local(void){\n");
	fprintf(f, "\tinitialize_%s();\n", dev->obj.name);	
	fprintf(f, "}\n");
}


static void gen_device_implement(device_t *dev, FILE *f) {
	gen_device_implement_desc(dev, f);
}

static void gen_device_resources(device_t *dev, FILE *f) {
	const char *name = dev->obj.name;

	gen_device_connect(dev, f);	
	gen_device_implement(dev, f);
	gen_device_port_description(dev, f);
	gen_device_attribute_description(dev, f);
	fprintf(f, "\nstatic const class_resource_t %s_resources = {\n", name);
	fprintf(f, "\t.ifaces = %s_ifaces,\n", name);
	fprintf(f, "\t.connects = %s_connects,\n", name);
	fprintf(f, "\t.attributes = %s_attributes,\n");
	if(!list_empty(&dev->ports)) {
		fprintf(f, "\t.ports = %s_ports,\n", name);
	} else {
		fprintf(f, "\t.ports = NULL,\n");
	}
	fprintf(f, "};\n");
}

static void gen_device_class_data(device_t *dev, FILE *f) {
	const char *name = dev->obj.name;

	gen_device_resources(dev, f);
	gen_bank_access_info(dev, f);
	fprintf(f, "\nstatic const class_data_t %s_class_data = {\n", name);
	fprintf(f, "\t.new_instance = %s_new_instance,\n", name);
	fprintf(f, "\t.finalize_instance = %s_finalize_instance,\n", name);
	fprintf(f, "\t.pre_delete_instance = %s_pre_delete_instance,\n", name);
	fprintf(f, "\t.delete_instance = %s_delete_instance,\n", name);
	fprintf(f, "\t.resources = &%s_resources,\n", name);
	fprintf(f, "\t.bank_access = %s_bank_access,\n", name);
	fprintf(f, "};\n");
}

void gen_device_type_info(device_t *dev, FILE *f) {
	const char *name = dev->obj.name;

	gen_device_class_data(dev, f);
	fprintf(f, "\nvoid initialize_%s(void) {\n", name);
	fprintf(f, "\tstatic conf_class_t conf_class = {\n");
	fprintf(f, "\t\t.cls_name = \"%s\",\n", name);	
	fprintf(f, "\t\t.cls_data = &%s_class_data,\n", name);
	fprintf(f, "\t};\n");
	fprintf(f, "\tSIM_register_conf_class(conf_class.cls_name, &conf_class);\n");
	fprintf(f, "}\n");
}

void gen_device_init(device_t *dev, FILE *f) {

	gen_device_constructor(dev, f);
	gen_device_destructor(dev, f);
	gen_mmio_setup(dev, f);
}

void gen_pre_delete(device_t *dev, FILE *f) {
	const char *name;

	name = dev->obj.name;
	fprintf(f, "\nstatic void\n");
	fprintf(f, "%s_pre_delete_instance(conf_object_t *obj){\n", name);
	fprintf(f, "\treturn ;\n");
	fprintf(f, "}\n");
}

void post_gen_code(device_t *dev, FILE *f) {
	gen_pre_delete(dev, f);
	gen_local_init(dev, f);
}
